import type { ExperienceItem } from './types';

export const experienceItems: ExperienceItem[] = [
	{
		title: '6 σ Black Belt',
		company: 'Board of Regents of University System of Georgia',
		location: '',
		services: '',
		year: '2023',
		startDate: 'Aug 2023',
		endDate: 'Dec 2023',
		duration: '5 mo',
		src: 'placeholder.png',
		color: '#fef3c7',
		url: '',
		categories: ['education'],
		description: '',
	},
	{
		title: 'BTech, Electronics and communication engineering',
		company: 'SRM University',
		location: '',
		services: '',
		year: '2019 – 2023',
		startDate: 'Sep 2019',
		endDate: 'Sep 2023',
		duration: '4 yrs',
		src: 'placeholder.png',
		color: '#dbeafe',
		url: '',
		categories: ['education'],
		description: '',
	},
	{
		title: 'Science',
		company: 'G.D Birla Centre For Education',
		location: '',
		services: '',
		year: '2017 – 2019',
		startDate: 'Jul 2017',
		endDate: 'Aug 2019',
		duration: '2 yrs 2 mo',
		src: 'placeholder.png',
		color: '#f0fdf4',
		url: '',
		categories: ['education'],
		description: '',
	},
	{
		title: 'Founder | CEO',
		company: 'NeuroAdapt, IISc',
		location: '',
		services: '',
		year: '2023',
		startDate: 'Oct 2023',
		endDate: 'Dec 2025',
		duration: '2 yrs 3 mos',
		src: 'placeholder.png',
		color: '#dbeafe',
		url: '',
		categories: ['entrepreneurship'],
		description: '',
	},
	{
		title: 'Founder | CEO',
		company: 'Ricky Kid, SRM University',
		location: '',
		services: '',
		year: '2019 – 2023',
		startDate: 'Sep 2019',
		endDate: 'Sep 2023',
		duration: '4 yrs',
		src: 'placeholder.png',
		color: '#f0fdf4',
		url: '',
		categories: ['entrepreneurship'],
		description: '',
	},
	{
		title: "Principal PM, CTO's office",
		company: 'Ixana',
		location: 'Bengaluru, Karnataka, India · Hybrid',
		services: '',
		year: '2024',
		startDate: 'Apr 2024',
		endDate: 'present',
		duration: 'Apr 24 - Present',
		src: 'p21.png',
		color: '#dbeafe',
		url: 'https://app.aphex.co/',
		categories: ['professional'],
		description: '',
	},
	{
		title: 'Senior Embedded Design Engineer',
		company: 'EEGRAB',
		location: 'Kolkata',
		services: '',
		year: '2024',
		startDate: 'Jan 2024',
		endDate: 'Apr 2024',
		duration: '4 mo',
		src: 'p22.png',
		color: '#ddd6fe',
		url: 'https://app.aphex.co/',
		categories: ['professional'],
		description: '',
	},
	{
		title: 'Electrical Engineer',
		company: 'SLB',
		location: 'Pune District, Maharashtra, India',
		services: '',
		year: '2023',
		startDate: 'Jan 2023',
		endDate: 'Dec 2023',
		duration: '1 yr',
		src: 'p24.png',
		color: '#d1d5db',
		url: '',
		categories: ['professional'],
		description: '',
	},

	{
		title: 'Project Intern | Team lead',
		company: 'ISRO, Govt. of India',
		location: 'Dehradun, Uttarakhand, India · Remote',
		services: '',
		year: '2022',
		startDate: 'Jul 2022',
		endDate: 'Jan 2023',
		duration: '7 mo',
		src: 'bigdata.webp',
		color: '#ddd6fe',
		url: 'https://bigdata.sri.com.sg',
		categories: ['professional'],
		description: '',
	},

	{
		title: 'CPS engineer | Project manager',
		company: 'SRM UAV',
		location: 'Online',
		services: '',
		year: '',
		startDate: 'Dec 2021',
		endDate: 'Jan 2023',
		duration: '1 yr 4 mo',
		src: 'bigdata.webp',
		color: '#fef3c7',
		url: '#',
		categories: ['industrial'],
		description: '',
	},
	{
		title: 'Internship trainee',
		company: 'MSME, Govt. of India',
		location: 'Agra, Uttar Pradesh',
		services: '',
		year: '',
		startDate: 'Mar 2022',
		endDate: 'Apr 2022',
		duration: '2 mo',
		src: 'placeholder.png',
		color: '#f0fdf4',
		url: '',
		categories: ['industrial'],
		description: '',
	},
	{
		title: 'Global student trainee',
		company: 'Schneider Electric',
		location: '',
		services: '',
		year: '',
		startDate: 'Jun 2022',
		endDate: 'Aug 2022',
		duration: '4 mo',
		src: 'placeholder.png',
		color: '#f0fdf4',
		url: '',
		categories: ['industrial'],
		description: '',
	},
	{
		title: 'Internship trainee',
		company: 'CoreEL Technologies',
		location: 'Bangalore, Karnataka',
		services: '',
		year: '',
		startDate: 'Jun 2022',
		endDate: 'Jul 2022',
		duration: '2 mo',
		src: 'placeholder.png',
		color: '#f0fdf4',
		url: '',
		categories: ['industrial'],
		description: '',
	},
	{
		title: 'Internship trainee',
		company: 'Vyorius',
		location: 'West Ghonda, Delhi',
		services: '',
		year: '',
		startDate: 'Nov 2021',
		endDate: 'Mar 2022',
		duration: '7 mo',
		src: 'placeholder.png',
		color: '#f0fdf4',
		url: '',
		categories: ['industrial'],
		description: '',
	},
	{
		title: 'Internship trainee',
		company: 'MSME, Govt. of India',
		location: 'Agra, Uttar Pradesh',
		services: '',
		year: '',
		startDate: 'Aug 2021',
		endDate: 'Sep 2021',
		duration: '2 mo',
		src: 'placeholder.png',
		color: '#f0fdf4',
		url: '',
		categories: ['industrial'],
		description: '',
	},
	{
		title: 'Student Ambassador',
		company: 'Techfest, IIT Bombay',
		location: '',
		services: '',
		year: '',
		startDate: 'Jun 2021',
		endDate: 'Jul 2021',
		duration: '2 mo',
		src: 'placeholder.png',
		color: '#f0fdf4',
		url: '',
		categories: ['industrial'],
		description: '',
	},
	{
		title: 'CPS trainee',
		company: 'IIT Ropar',
		location: 'Online',
		services: '',
		year: '',
		startDate: 'May 2021',
		endDate: 'Jun 2021',
		duration: '1 mo',
		src: 'placeholder.png',
		color: '#f0fdf4',
		url: '',
		categories: ['industrial'],
		description: '',
	},
	{
		title: 'Marketing intern',
		company: 'MyCaptain',
		location: 'Bengaluru, Karnataka',
		services: '',
		year: '',
		startDate: 'Apr 2020',
		endDate: 'May 2020',
		duration: '2 mo',
		src: 'placeholder.png',
		color: '#f0fdf4',
		url: '',
		categories: ['industrial'],
		description: '',
	},

	{
		title: 'Technical research team',
		company: 'Samsung India',
		location: '',
		services: '',
		year: '',
		startDate: 'Nov 2019',
		endDate: 'Nov 2019',
		duration: '1 mo',
		src: 'placeholder.png',
		color: '#f0fdf4',
		url: '',
		categories: ['industrial'],
		description: '',
	},
];

export const filters = [
	{ key: 'all', label: 'All' },
	{ key: 'professional', label: 'Professional Experience' },
	{ key: 'entrepreneurship', label: 'Entrepreneurship' },
	{ key: 'industrial', label: 'Industrial Training' },
	{ key: 'education', label: 'Education' },
] as const;

export type FilterKey = (typeof filters)[number]['key'];
