import type { ExperienceItem } from './types';

export const experienceItems: ExperienceItem[] = [
    {
        title: 'Principal PM, CTO\'s office',
        company: 'Ixana',
        location: 'Bengaluru, Karnataka, India · Hybrid',
        services: 'Cross-functional Team Leadership, Product Development and +4 skills',
        year: '2024',
        startDate: 'Apr 2024',
        endDate: 'present',
        duration: 'Apr 24 - Present',
        src: 'p21.png',
        color: '#dbeafe',
        url: 'https://app.aphex.co/',
        categories: ['professional'],
        description: 'Working closely with the CTO (founder) of Ixana. I own efficiency (PM-AI), leading AI programs, oversee the technical operations, and ensure the smooth functioning of the organization’s technological aspects.',
    },
    {
        title: 'Senior Embedded Design Engineer',
        company: 'EEGRAB',
        location: 'Kolkata',
        services: 'Fullstack Development',
        year: '2024',
        startDate: 'Jan 2024',
        endDate: 'Apr 2024',
        duration: '4 mo',
        src: 'p22.png',
        color: '#ddd6fe',
        url: 'https://app.aphex.co/',
        categories: ['professional'],
        description: 'Built scalable web applications',
    },
    {
        title: 'Electrical Engineer',
        company: 'SLB',
        location: 'Pune District, Maharashtra, India',
        services: 'Failure Analysis of PCB & PWA, R&D. Electrical Troubleshooting, Circuit Analysis and +3 skills',
        year: '2023',
        startDate: 'Jan 2023',
        endDate: 'Dec 2023',
        duration: '1 yr',
        src: 'p24.png',
        color: '#d1d5db',
        url: '',
        categories: ['professional'],
        description: 'Worked on failure analysis and electrical troubleshooting.',
    },


    {
        title: 'Project Intern | Team lead',
        company: 'ISRO, Govt. of India',
        location: 'Dehradun, Uttarakhand, India · Remote',
        services: 'IoT solutions Architect',
        year: '2022',
        startDate: 'Jul 2022',
        endDate: 'Jan 2023',
        duration: '7 mo',
        src: 'bigdata.webp',
        color: '#ddd6fe',
        url: 'https://bigdata.sri.com.sg',
        categories: ['professional'],
        description: 'Created interactive dashboards',
    },

    {
        title: 'CPS engineer | Project manager',
        company: 'SRM UAV',
        location: 'Online',
        services: 'Training & Education',
        year: '',
        startDate: 'Dec 2021',
        endDate: 'Jan 2023',
        duration: '1 yr 4 mo',
        src: 'bigdata.webp',
        color: '#fef3c7',
        url: '#',
        categories: ['industrial'],
        description: 'Completed intensive bootcamp covering modern web development',
    },
    {
        title: 'Internship trainee',
        company: 'MSME, Govt. of India',
        location: 'Agra, Uttar Pradesh',
        services: 'Computer hardware and networking',
        year: '',
        startDate: 'Mar 2022',
        endDate: 'Apr 2022',
        duration: '2 mo',
        src: 'placeholder.png',
        color: '#f0fdf4',
        url: '',
        categories: ['industrial'],
        description: '',
    },
    {
        title: 'Global student trainee',
        company: 'Schneider Electric',
        location: '',
        services: 'Sustainability as a Business, energy management and corporate sustainability',
        year: '',
        startDate: 'Jun 2022',
        endDate: 'Aug 2022',
        duration: '4 mo',
        src: 'placeholder.png',
        color: '#f0fdf4',
        url: '',
        categories: ['industrial'],
        description: '',
    },
    {
        title: 'Internship trainee',
        company: 'CoreEL Technologies',
        location: 'Bangalore, Karnataka',
        services: 'Functional Verification using System Verilog',
        year: '',
        startDate: 'Jun 2022',
        endDate: 'Jul 2022',
        duration: '2 mo',
        src: 'placeholder.png',
        color: '#f0fdf4',
        url: '',
        categories: ['industrial'],
        description: '',
    },
    {
        title: 'Internship trainee',
        company: 'Vyorius',
        location: 'West Ghonda, Delhi',
        services: 'VLSI design and IoT training with hands on simulation and 5 major/minor projects',
        year: '',
        startDate: 'Nov 2021',
        endDate: 'Mar 2022',
        duration: '7 mo',
        src: 'placeholder.png',
        color: '#f0fdf4',
        url: '',
        categories: ['industrial'],
        description: '',
    },
    {
        title: 'Internship trainee',
        company: 'MSME, Govt. of India',
        location: 'Agra, Uttar Pradesh',
        services: 'Embedded system and Internet of Things training',
        year: '',
        startDate: 'Aug 2021',
        endDate: 'Sep 2021',
        duration: '2 mo',
        src: 'placeholder.png',
        color: '#f0fdf4',
        url: '',
        categories: ['industrial'],
        description: '',
    },
    {
        title: 'Student Ambassador',
        company: 'Techfest, IIT Bombay',
        location: '',
        services: 'Student Ambassador and Network Growth',
        year: '',
        startDate: 'Jun 2021',
        endDate: 'Jul 2021',
        duration: '2 mo',
        src: 'placeholder.png',
        color: '#f0fdf4',
        url: '',
        categories: ['industrial'],
        description: 'Selected as a student ambassador by Techfest IIT Bombay in June, where I contributed towards network growth for industrial projects and training provided by many startup companies at a platform 1stop in my university.',
    },
    {
        title: 'CPS trainee',
        company: 'IIT Ropar',
        location: 'Online',
        services: 'CPS-Advance skill training workshop for Agricultural automation',
        year: '',
        startDate: 'May 2021',
        endDate: 'Jun 2021',
        duration: '1 mo',
        src: 'placeholder.png',
        color: '#f0fdf4',
        url: '',
        categories: ['industrial'],
        description: '',
    },
    {
        title: 'Marketing intern',
        company: 'MyCaptain',
        location: 'Bengaluru, Karnataka',
        services: 'Community building and creating impact in my campus, SRM Institute of Science and Technology',
        year: '',
        startDate: 'Apr 2020',
        endDate: 'May 2020',
        duration: '2 mo',
        src: 'placeholder.png',
        color: '#f0fdf4',
        url: '',
        categories: ['industrial'],
        description: '',
    },

    {
        title: 'Technical research team',
        company: 'Samsung India',
        location: '',
        services: 'Community building and creating impact in my campus, SRM Institute of Science and Technology',
        year: '',
        startDate: 'Nov 2019',
        endDate: 'Nov 2019',
        duration: '1 mo',
        src: 'placeholder.png',
        color: '#f0fdf4',
        url: '',
        categories: ['industrial'],
        description: '',
    },
];

export const filters = [
    { key: 'all', label: 'All' },
    { key: 'professional', label: 'Professional Experience' },
    { key: 'industrial', label: 'Industrial Training' },
] as const;

export type FilterKey = (typeof filters)[number]['key'];
