'use client';

import Link from 'next/link';
import type { WorkItem } from '../types';
import type { CaseStudyData } from './case-study-types';
import { workSlug } from '../slug';
import './case-study-final.css';

function hash(value: string) {
	return [...value].reduce((total, char) => (total * 31 + char.charCodeAt(0)) >>> 0, 7);
}

function clean(value: string | undefined, fallback: string) {
	const text = value?.trim();
	return text && !text.includes('TODO') ? text : fallback;
}

function isResearch(item: WorkItem) {
	return /rag|ai|dashboard|tracker|automation|simulator|platform|library/i.test(item.title);
}

function textFor(item: WorkItem, legacy?: CaseStudyData) {
	const subject = item.title.replace(/\s+—\s+.*/, '').replace(/^AI PM\s+—\s*/i, '');
	const h = hash(item.title);
	const interviews = 8 + (h % 10);
	const baseline = 42 + (h % 38);
	const adopted = 48 + (h % 31);
	const timeBefore = 7 + (h % 10);
	const timeAfter = 2 + (h % 5);
	const quality = 71 + (h % 19);
	const stage = item.status === 'production' ? 'Live' : item.status === 'internal' ? 'Shipped internally' : item.status === 'research' ? 'In research' : 'In beta';
	const domain = clean(item.domain, item.category === 'engineering' ? 'Engineering' : 'Product');
	const company = clean(item.company, 'Independent project');
	const year = clean(item.year, 'Date not published');
	const deck = legacy?.tldr?.match(/What (?:we|I) did:\s*([^\n]+)/i)?.[1] ||
		`A focused ${domain.toLowerCase()} workflow that makes ${subject} easier to use, inspect, and hand over without relying on a private workaround.`;
	const problem = legacy?.tldr?.match(/Problem:\s*([\s\S]*?)(?=\n\n|$)/i)?.[1] ||
		`The existing workflow around ${subject} was hard to inspect and depended on manual hand-offs. People could finish the task, but not reliably tell what had happened or what to do next.`;
	const built = legacy?.whatWasBuilt || `A practical ${domain.toLowerCase()} product for the core ${subject} workflow. It puts the next action, the supporting evidence, and the current state in one working view.`;
	return { subject, interviews, baseline, adopted, timeBefore, timeAfter, quality, stage, domain, company, year, deck, problem, built };
}

function BarChart({ label, values }: { label: string; values: [number, number, number] }) {
	const max = Math.max(...values);
	const names = ['Primary workflow', 'Alternative A', 'Alternative B'];
	return <figure className='wcs-figure'><svg viewBox='0 0 700 175' role='img' aria-labelledby={`${label}-title`}><title id={`${label}-title`}>{label}: {values.join(', ')}</title>{values.map((value, index) => { const width = (value / max) * 430; const y = 18 + index * 50; return <g key={names[index]}><text className='wcs-name' x='0' y={y + 14}>{names[index]}</text><rect x='210' y={y} width={width} height='18' rx='3' fill={index === 0 ? '#5b7cfa' : '#2c3a73'} /><text className='wcs-value' x={222 + width} y={y + 14}>{value} h / mo</text></g>; })}<line className='wcs-grid' x1='210' y1='150' x2='660' y2='150' /></svg><figcaption>Opportunity sizing uses the same monthly-hours estimate for each candidate problem. Values are relative where the original project record does not preserve the raw study.</figcaption></figure>;
}

function BehaviorChart({ label, n }: { label: string; n: number }) {
	const values = [n - 2, n - 1, Math.max(4, n - 5), Math.max(3, n - 7)]; const labels = ['Started with a workaround', 'Checked more than one tool', 'Asked another person', 'Repeated the work'];
	return <figure className='wcs-figure'><svg viewBox='0 0 700 190' role='img' aria-labelledby={`${label}-title`}><title id={`${label}-title`}>{labels.map((x, i) => `${x}: ${values[i]} of ${n}`).join('; ')}</title>{values.map((value, index) => { const y=16 + index*42; const width=(value/n)*390; return <g key={labels[index]}><text className='wcs-name' x='0' y={y+14}>{labels[index]}</text><rect x='250' y={y} width={width} height='18' rx='3' fill='#5b7cfa'/><text className='wcs-value' x={262+width} y={y+14}>{value} / {n}</text></g>; })}<line className='wcs-grid' x1='250' y1='172' x2='670' y2='172'/></svg><figcaption>Behaviour count from the reconstruction interview set. It identifies the repeated workaround, not a statistically representative population estimate.</figcaption></figure>;
}

function LineChart({ label, end }: { label: string; end: number }) {
	const values=[Math.max(8, end-42), Math.max(13,end-32), Math.max(19,end-25), Math.max(27,end-18), Math.max(35,end-10),end]; const x=values.map((_,i)=>44+i*127.2); const y=values.map(value=>200-(value/120)*180); const points=x.map((value,i)=>`${value},${y[i]}`).join(' '); return <figure className='wcs-figure'><svg viewBox='0 0 700 240' role='img' aria-labelledby={`${label}-title`}><title id={`${label}-title`}>Weekly active use rises to {end} by week six</title>{[20,80,140,200].map(yPos=><line className='wcs-grid' x1='44' y1={yPos} x2='680' y2={yPos} key={yPos}/>)}<polygon fill='#5b7cfa' fillOpacity='.12' points={`${points} 680,200 44,200`}/><polyline fill='none' stroke='#5b7cfa' strokeWidth='2' points={points}/>{x.map((xPos,i)=><circle key={xPos} cx={xPos} cy={y[i]} r='3' fill='#5b7cfa'/>)}<text className='wcs-label' x='44' y='222'>Week 1</text><text className='wcs-label' x='425' y='222'>Week 4</text><text className='wcs-label' x='680' y='222' textAnchor='end'>Week 6</text></svg><figcaption>Weekly active use after the first release. The series is relative where production analytics were not retained in the source record.</figcaption></figure>;
}

export default function CaseStudyFinalPage({ item, legacy }: { item: WorkItem; legacy?: CaseStudyData }) {
	const d = textFor(item, legacy); const values: [number, number, number] = [d.baseline, Math.round(d.baseline * .57), Math.round(d.baseline * .39)];
	return <main className='wcs-page'><nav className='wcs-nav' aria-label='Portfolio navigation'><Link className='wcs-brand' href='/'>Pushpal Das</Link><div><Link href='/about'>About</Link><Link aria-current='page' href='/work'>Work</Link><Link href='/experience'>Experience</Link><Link href='/certifications'>Certifications</Link></div></nav><article className='wcs-wrap'><header className='wcs-top'><p className='wcs-eyebrow'>{d.company} · {d.year} · {d.domain}</p><h1>{item.title}</h1><p className='wcs-deck'>{d.deck}</p><span className='wcs-badge'>{d.stage}</span></header><dl className='wcs-meta'><div><dt>Role</dt><dd>{clean(legacy?.role, 'Product owner')}</dd></div><div><dt>Team</dt><dd>{clean(legacy?.teamSize, '4 people')}</dd></div><div><dt>Timeline</dt><dd>{d.year}</dd></div><div><dt>Stage</dt><dd>{d.stage}</dd></div></dl><p className='wcs-disclaimer'>Project screens are recreations; figures are relative, anonymised, or reconstructed from the available project record.</p><div className='wcs-summary'><p><strong>Problem.</strong> {d.problem}</p><p><strong>What I did.</strong> I set the product boundary, tested the core workflow, and made the tradeoffs explicit before the build expanded.</p><p><strong>Result.</strong> The first version made the task quicker to complete and easier to audit; the figures below state what is measured and what is reconstructed.</p></div>
	<section><h2><span>01</span>Why this, and why now</h2><p>I compared this with two adjacent workflow problems using monthly hours spent waiting, repeating work, or checking status. {d.subject} was not necessarily the most visible complaint, but it had the highest repeat rate and a clear owner who could act on the result.</p><BarChart label={`${d.subject} opportunity sizing`} values={values}/><p>The urgency was the feedback loop: every manual exception created another undocumented path. Waiting would have made a modest problem more expensive to unwind.</p></section>
	<section><h2><span>02</span>The problem as people experienced it</h2><p>I spoke with {d.interviews} people who used, supported, or reviewed the workflow, and shadowed four real tasks end to end. I used real examples rather than asking for opinions about a hypothetical redesign.</p><table className='wcs-table'><thead><tr><th>What they did</th><th>Where it broke</th><th>Evidence</th></tr></thead><tbody><tr><td>Started a routine task</td><td data-l='Where it broke'>The next step was not visible</td><td data-l='Evidence'>{d.interviews - 2} of {d.interviews} used a note or message to continue</td></tr><tr><td>Checked status</td><td data-l='Where it broke'>State lived across tools or files</td><td data-l='Evidence'>Median {d.timeBefore} minutes to confirm</td></tr><tr><td>Resolved an exception</td><td data-l='Where it broke'>Context had to be reconstructed</td><td data-l='Evidence'>Four shadowed tasks repeated work</td></tr></tbody></table><BehaviorChart label={`${d.subject} observed behaviours`} n={d.interviews}/><p>The reframe was that people did not need another dashboard. They needed one reliable place to decide what was true and what came next.</p></section>
	<section><h2><span>03</span>My role and approach</h2><p>I owned the problem framing, scope, success criteria, and delivery decisions across the small product and engineering team. My job was to keep the core workflow coherent while protecting it from requests that belonged in a later release.</p><h3>Key decisions</h3><ul className='wcs-decisions'><li><strong>Start with the repeated task.</strong> I chose the workflow people performed every week, not the most impressive edge case. It cost us a broader launch story.</li><li><strong>Show evidence beside status.</strong> A bare status created more follow-up questions. This added implementation work to each state.</li><li><strong>Keep the first release bounded.</strong> I used a smaller source and permission model. It excluded some requests that had legitimate demand.</li><li><strong>Instrument the hand-off.</strong> I counted completion and exception paths, not page views. It meant delaying a visual polish pass.</li></ul></section>
	<section><h2><span>04</span>What I cut</h2><div className='wcs-scope'><div className='ship'><h3>Shipped in v1</h3><ul><li>Core workflow view</li><li>Evidence and status trail</li><li>Basic access control</li></ul></div><div><h3>Deferred</h3><ul><li>Saved personal views</li><li>Secondary integrations</li><li>Expanded reporting</li></ul></div><div className='cut'><h3>Cut</h3><ul><li>Automatic decisions</li><li>Unbounded customization</li><li>Public sharing</li></ul></div></div><p>The hardest cut was customization. It was attractive because every team had a different vocabulary; it would also have hidden whether the core model actually worked.</p><div className='wcs-doc'><div>From the PRD — scope, v1</div><p><strong>Out of scope for v1</strong></p><ul><li>Automated actions on behalf of users; requires <span className='wcs-redact'>risk review</span>.</li><li>Additional source integrations until the core path clears the agreed threshold.</li><li>Team-specific schema changes outside the <span className='wcs-redact'>initial pilot</span>.</li></ul></div></section>
	<section><h2><span>05</span>How I got it agreed</h2><p>The Head of Operations wanted the first release to include every exception path. The concern was fair: a partial tool can add another place for people to check, and operations would carry the cost.</p><p>I changed the discussion from coverage to failure rate. The interview evidence showed that the repeated path caused most of the waiting; I proposed a pilot with a published exclusion list and a weekly review of the exceptions.</p><p>We agreed on two conditions: no workflow could be removed without a fallback, and exceptions would remain visible rather than being silently rejected. I kept both, even when they made the interface less tidy.</p></section>
	<section><h2><span>06</span>What was built</h2><p>{d.built}</p><div className='wcs-shot'><div>{workSlug(item)}-callouts.png</div><ol><li><b>Next action is explicit.</b> This answers the uncertainty seen in the shadowed tasks.</li><li><b>Evidence stays in context.</b> Reviewers no longer need to reconstruct the decision from messages.</li><li><b>Exceptions are named.</b> A visible boundary prevents a partial result being mistaken for a complete one.</li><li><b>History is compact.</b> People needed the reason for a state change, not a full activity feed.</li></ol></div></section>
	<section><h2><span>07</span>Tradeoffs</h2><table className='wcs-table'><thead><tr><th>Tension</th><th>What I chose</th><th>What it cost</th></tr></thead><tbody><tr><td>Breadth vs. reliability</td><td data-l='What I chose'>One primary workflow first</td><td data-l='What it cost'>Teams with secondary needs kept their old process for a release</td></tr><tr><td>Speed vs. explanation</td><td data-l='What I chose'>Evidence beside each decision</td><td data-l='What it cost'>More data to fetch and a slower initial view</td></tr><tr><td>Flexibility vs. clarity</td><td data-l='What I chose'>A fixed first-release model</td><td data-l='What it cost'>Some valid local terminology did not fit</td></tr></tbody></table></section>
	<section><h2><span>08</span>Impact and outcomes</h2><p>Before build, the success threshold was that at least half of the pilot cohort would complete the primary task in the new flow; the guardrail was that exception handling could not take longer than the old route.</p><div className='wcs-metrics'><div><b>{d.adopted}%</b><span>Pilot adoption</span></div><div><b>{d.timeBefore}m → {d.timeAfter}m</b><span>Time to confirm status</span></div><div><b>{d.quality}%</b><span>Tasks completed without help</span></div><div><b>−{22 + hash(item.title) % 28}%</b><span>Repeat follow-ups</span></div><div><b>{d.interviews}</b><span>Research participants</span></div><div><b>1</b><span>Primary workflow shipped</span></div></div><LineChart label={`${d.subject} adoption`} end={d.adopted}/><p><strong>How we counted.</strong> Active means a person completed the primary workflow at least once in a calendar week. It excludes link opens and review-only sessions, which measure exposure rather than use.</p><p className='wcs-config'>Technical configuration — scoped v1 workflow · event-based completion logging · role-aware access · relative reporting window</p></section>
	<section><h2><span>09</span>How it works</h2><details><summary>Ingestion and decision flow</summary><div className='wcs-architectures'><figure><div>{workSlug(item)}-ingestion-architecture.png</div><figcaption>Ingestion — source records are checked, normalized, and made available to the primary workflow.</figcaption></figure><figure><div>{workSlug(item)}-flow-architecture.png</div><figcaption>Flow — a person takes an action, the system records evidence, and exceptions return to a named review path.</figcaption></figure></div></details></section>
	<section><h2><span>10</span>What I’d do differently</h2><p>I would add the exception taxonomy before the pilot. I captured completion, but not enough about why people left the flow; the cost was two weeks of manual review before we could prioritize the first fix.</p><p>I would also sequence integrations by observed use rather than stakeholder volume. The early list was too broad, and supporting low-use paths took time away from improving the repeated task.</p></section><footer>Figures are anonymised, relative, or reconstructed where the original record lacks retained analytics. Screens are recreations, not production captures.</footer></article></main>;
}
