import type { WorkItem } from './types';

export const workItems: WorkItem[] = [
    {
        title: 'YR31',
        company: 'Ixana',
        year: '2024 - 2026',
        domain: 'Silicon',
        category: 'product',
        status: 'production',
        outcome: 'Wi-R Body Area Network (BAN) ',
        image: 'Image__2_.jpg',
        color: '#dbeafe',
    },
    {
        title: 'Dev Kits — Wi-R Body Area Network (BAN) YR23 & Wi-R Near Field Electric (NFE) XA-NFE2001',
        company: 'Ixana',
        year: '2023',
        domain: 'TODO: domain',
        category: 'product',
        status: null,
        outcome: 'TODO: outcome line',
        image: 'Image__10_.jpg',
        color: '#dbeafe',
    },
    {
        title: 'XANA — Multifile RAG based Data Singularity Platform',
        company: 'Ixana',
        year: 'TODO: year',
        domain: 'TODO: domain',
        category: 'product',
        status: null,
        outcome: 'TODO: outcome line',
        image: 'Gemini_Generated_Image_anlzx7anlzx7anlz.png',
        href: 'https://github.com/PushpalDas/Ixana-Wiki',
        slug: 'xana-multifile-rag-based-data-singularity-platform',
        color: '#dbeafe',
    },
    {
        title: 'Dāsa',
        company: 'ISKCON (International Society for Krishna Consciousness) ',
        year: '2026 - present',
        domain: 'AI',
        category: 'product',
        status: 'research',
        outcome: 'Generative AI Engine for a Guided Spiritual Path',
        image: 'Image__1_.jpg',
        color: '#dbeafe',
    },
    {
        title: 'Wi-R Body Area Network (BAN) — YR23',
        company: 'Ixana',
        year: '2024 - 2026',
        domain: 'TODO: domain',
        category: 'product',
        status: 'production',
        outcome: 'TODO: outcome line',
        image: 'Image__3_.jpg',
        href: 'https://www.ixana.ai/products/chips/wi-r-ban',
        color: '#ffedd5',
    },
    {
        title: 'NeuroAdapt — Agentic RAG Engine for Neuroscience Research',
        company: 'NeuroAdapt, IISc Bangalore',
        year: '2023-2025',
        domain: 'TODO: domain',
        category: 'product',
        status: null,
        outcome: 'TODO: outcome line',
        image: 'Gemini_Generated_Image_xejg8vxejg8vxejg.png',
        href: 'https://drive.google.com/drive/u/0/folders/1B0mtA9-xkNbbo6ZUXztuHZiMmlovNtLw',
        slug: 'neuroadapt-agentic-rag-engine-for-neuroscience-research',
        color: '#dbeafe',
    },
    {
        title: 'Wi-R Near Field Electric (NFE) — XA-NFE3001',
        company: 'Ixana',
        year: 'TODO: year',
        domain: 'TODO: domain',
        category: 'product',
        status: null,
        outcome: 'TODO: outcome line',
        image: 'Image__8_.jpg',
        color: '#dbeafe',
    },
    {
        title: 'Wi-R Near Field Electric (NFE) — XA-NFE2001',
        company: 'Ixana',
        year: '2024 - 2026',
        domain: 'TODO: domain',
        category: 'product',
        status: 'production',
        outcome: 'TODO: outcome line',
        image: 'Image__9_.jpg',
        href: 'https://www.ixana.ai/products/dev-kits',
        color: '#dbeafe',
    },
    {
        title: 'Data application — Accurate estimation of mineral present in soil',
        company: 'IIRS-ISRO, Govt. of India',
        year: 'TODO: year',
        domain: 'TODO: domain',
        category: 'product',
        status: null,
        outcome: 'TODO: outcome line',
        image: 'Image__5_.jpg',
        href: 'https://drive.google.com/drive/u/0/folders/1tYViz5kUrsL5PZ_9DsghxZ1uno1qYQzs',
        color: '#dbeafe',
    },
    {
        title: 'Quantum Circuit Simulator — Interactive 10-Qubit Delivering Real-Time 3D Bloch Visualizations',
        company: 'Personal',
        year: 'TODO: year',
        domain: 'TODO: domain',
        category: 'product',
        status: null,
        outcome: 'TODO: outcome line',
        image: 'Gemini_Generated_Image_dafj5odafj5odafj.png',
        slug: 'quantum-circuit-simulator-interactive-10-qubit-delivering-re',
        color: '#dbeafe',
    },
    {
        title: 'Procurement Orchestrator — Procurement Process Automation with M365',
        company: 'Ixana',
        year: 'TODO: year',
        domain: 'TODO: domain',
        category: 'product',
        status: null,
        outcome: 'TODO: outcome line',
        image: 'Gemini_Generated_Image_ene5eiene5eiene5__1_.png',
        slug: 'procurement-orchestrator-procurement-process-automation-with',
        color: '',
    },
    {
        title: 'WishKey — Key Management System',
        company: 'EEGRAB',
        year: 'TODO: year',
        domain: 'TODO: domain',
        category: 'product',
        status: null,
        outcome: 'TODO: outcome line',
        image: 'Image__1_.png',
        href: 'https://eegrab.com/wp-content/uploads/2021/brochure/Wishkey_brochure.pdf',
        color: '#dbeafe',
    },
    {
        title: 'Wi-R — Video Streaming Smartglasses & Tactical Headphone to Radio Communication',
        company: 'Ixana',
        year: '2024 - 2026',
        domain: 'TODO: domain',
        category: 'product',
        status: null,
        outcome: 'TODO: outcome line',
        image: 'Gemini_Generated_Image_ef658pef658pef65.png',
        href: 'https://www.ixana.ai/products/reference-designs',
        color: '#dbeafe',
    },
    {
        title: 'Cost-effective Smart watch',
        company: 'EEGRAB',
        year: 'TODO: year',
        domain: 'TODO: domain',
        category: 'product',
        status: null,
        outcome: 'TODO: outcome line',
        image: 'Gemini_Generated_Image_io6t60io6t60io6t.png',
        color: '#dbeafe',
    },
    {
        title: 'AI PM — Generative AI Engine for RCA Report Automation',
        company: 'Ixana',
        year: '2025',
        domain: 'TODO: domain',
        category: 'product',
        status: null,
        outcome: 'TODO: outcome line',
        image: 'Image__14_.jpg',
        href: 'https://10xar-my.sharepoint.com/my?id=%2Fpersonal%2Fpushpal%5Fdas%5Fixana%5Fai%2FDocuments%2FAnuj%20tasks%2FProject%20Management%20Agentic%20Ai%2FRoot%20Cause%20Analyse&viewid=c9c2956f%2D87bf%2D415b%2D8b2a%2D598c7b0a1b99&csf=1&FolderCTID=0x012000D839801D2B34804CB13555A64E4ECD83',
        slug: 'ai-pm-generative-ai-engine-for-rca-report-automation',
        color: '#ddd6fe',
    },
    {
        title: 'AI PM — Generative AI Engine for Resource Allocation',
        company: 'Ixana',
        year: '2025',
        domain: 'TODO: domain',
        category: 'product',
        status: null,
        outcome: 'TODO: outcome line',
        image: 'Gemini_Generated_Image_gqlkm8gqlkm8gqlk.png',
        href: 'https://10xar-my.sharepoint.com/personal/pushpal_das_ixana_ai/_layouts/15/onedrive.aspx?csf=1&web=1&e=f1nILS&CID=94ad2e4c-6d67-4625-91bf-23a89e96df3d&id=%2fpersonal%2fpushpal_das_ixana_ai%2fDocuments%2fAnuj+tasks%2fProject+Management+Agentic+Ai%2fResource+allocation&FolderCTID=0x012000D839801D2B34804CB13555A64E4ECD83&view=0',
        slug: 'ai-pm-generative-ai-engine-for-resource-allocation',
        color: '#fae8ff',
    },
    {
        title: 'AI PM — Generative AI Engine for Scrum Ecosystem',
        company: 'Ixana',
        year: '2025',
        domain: 'TODO: domain',
        category: 'product',
        status: null,
        outcome: 'TODO: outcome line',
        image: 'Image__15_.jpg',
        href: 'https://10xar-my.sharepoint.com/personal/pushpal_das_ixana_ai/_layouts/15/onedrive.aspx?csf=1&web=1&e=f1nILS&CID=94ad2e4c-6d67-4625-91bf-23a89e96df3d&id=%2fpersonal%2fpushpal_das_ixana_ai%2fDocuments%2fAnuj+tasks%2fProject+Management+Agentic+Ai%2fResource+allocation&FolderCTID=0x012000D839801D2B34804CB13555A64E4ECD83&view=0',
        color: '#fae8ff',
    },
    {
        title: 'AI PM — Generative AI Engine for Real-Time Pipeline Diagnostics and Strategic Engineering',
        company: 'Ixana',
        year: 'TODO: year',
        domain: 'TODO: domain',
        category: 'product',
        status: null,
        outcome: 'TODO: outcome line',
        image: 'Gemini_Generated_Image_8c4hfs8c4hfs8c4h.png',
        slug: 'ai-pm-generative-ai-engine-for-real-time-pipeline-diagnostic',
        color: '#fae8ff',
    },
    {
        title: '"Github for ClickUp" — Automation on the changes going outside PMO framework',
        company: 'Ixana',
        year: 'Coming soon...',
        domain: 'TODO: domain',
        category: 'product',
        status: null,
        outcome: 'TODO: outcome line',
        image: 'Image__16_.jpg',
        href: 'https://10xar-my.sharepoint.com/personal/pushpal_das_ixana_ai/_layouts/15/onedrive.aspx?csf=1&web=1&e=f1nILS&CID=94ad2e4c-6d67-4625-91bf-23a89e96df3d&id=%2fpersonal%2fpushpal_das_ixana_ai%2fDocuments%2fAnuj+tasks%2fProject+Management+Agentic+Ai%2fResource+allocation&FolderCTID=0x012000D839801D2B34804CB13555A64E4ECD83&view=0',
        slug: 'github-for-clickup-automation-on-the-changes-going-outside-p',
        color: '#fae8ff',
    },
    {
        title: 'IXANA Video Library — Automated Company Video Library',
        company: 'Ixana',
        year: 'Coming soon...',
        domain: 'TODO: domain',
        category: 'product',
        status: null,
        outcome: 'TODO: outcome line',
        image: 'Gemini_Generated_Image_i9dz41i9dz41i9dz.png',
        href: 'https://10xar-my.sharepoint.com/my?csf=1&web=1&e=VPo0gz&id=%2Fpersonal%2Fpushpal%5Fdas%5Fixana%5Fai%2FDocuments%2FAnuj%20tasks%2FVideo%20lib%20automation&FolderCTID=0x012000D839801D2B34804CB13555A64E4ECD83',
        slug: 'ixana-video-library-automated-company-video-library',
        color: '#fae8ff',
    },
    {
        title: 'Calendar Automation — Real-Time, Bi-Directional Sync Engine with Gmail & Outlook Calendar',
        company: 'Ixana',
        year: '2025',
        domain: 'TODO: domain',
        category: 'product',
        status: null,
        outcome: 'TODO: outcome line',
        image: 'Gemini_Generated_Image_18w83818w83818w8.png',
        href: 'https://10xar-my.sharepoint.com/my?csf=1&web=1&e=3pGPGD&id=%2Fpersonal%2Fpushpal%5Fdas%5Fixana%5Fai%2FDocuments%2FAyush%20tasks%2FProject%20%2D%20Calender%20Operations&FolderCTID=0x012000D839801D2B34804CB13555A64E4ECD83',
        slug: 'calendar-automation-real-time-bi-directional-sync-engine-wit',
        color: '#fae8ff',
    },
    {
        title: 'AI Salary Generator — In progress..',
        company: 'Ixana',
        year: '2024-coming soon...',
        domain: 'TODO: domain',
        category: 'product',
        status: null,
        outcome: 'TODO: outcome line',
        image: 'Image__17_.jpg',
        href: 'https://www.ixana.ai/products',
        color: '#fee2e2',
    },
    {
        title: 'AI PRD — Multi Agent, Multi LLM Shared Memory Generative System',
        company: 'Ixana',
        year: 'TODO: year',
        domain: 'TODO: domain',
        category: 'product',
        status: null,
        outcome: 'TODO: outcome line',
        image: 'Gemini_Generated_Image_6dagw16dagw16dag.png',
        slug: 'ai-prd-multi-agent-multi-llm-shared-memory-generative-system',
        color: '#dbeafe',
    },
    {
        title: 'AI Lawyer — Multi Agent, Multi LLM Shared Memory Generative System',
        company: 'Ixana',
        year: 'TODO: year',
        domain: 'TODO: domain',
        category: 'product',
        status: null,
        outcome: 'TODO: outcome line',
        image: 'Gemini_Generated_Image_1i9ozk1i9ozk1i9o.png',
        slug: 'ai-lawyer-multi-agent-multi-llm-shared-memory-generative-sys',
        color: '#dbeafe',
    },
    {
        title: 'AI PM — Customized Multi View for PM\'s',
        company: 'Ixana',
        year: 'TODO: year',
        domain: 'TODO: domain',
        category: 'product',
        status: null,
        outcome: 'TODO: outcome line',
        image: 'Gemini_Generated_Image_h59yuyh59yuyh59y.png',
        slug: 'ai-pm-customized-multi-view-for-pms',
        color: '#dbeafe',
    },
    {
        title: 'Ixana\'s "Fireflies" — Generative AI engine for taking meeting notes and answering question',
        company: 'Ixana',
        year: 'TODO: year',
        domain: 'TODO: domain',
        category: 'product',
        status: null,
        outcome: 'TODO: outcome line',
        image: 'Image__18_.jpg',
        color: '#dbeafe',
    },
    {
        title: 'Patent tracker — Generative AI Engine for Data Extraction',
        company: 'Ixana',
        year: 'TODO: year',
        domain: 'TODO: domain',
        category: 'product',
        status: null,
        outcome: 'TODO: outcome line',
        image: 'Image__19_.jpg',
        slug: 'patent-tracker-generative-ai-engine-for-data-extraction',
        color: '#dbeafe',
    },
    {
        title: 'PM TOOL Document Tracker — Data extraction, easy visibility for doc users',
        company: 'Ixana',
        year: 'TODO: year',
        domain: 'TODO: domain',
        category: 'product',
        status: null,
        outcome: 'TODO: outcome line',
        image: 'Image__21_.jpg',
        color: '#dbeafe',
    },
    {
        title: 'Condenser microphone',
        company: 'EEGRAB',
        year: 'TODO: year',
        domain: 'TODO: domain',
        category: 'product',
        status: null,
        outcome: 'TODO: outcome line',
        image: 'Gemini_Generated_Image_cqoga8cqoga8cqog.png',
        color: '#dbeafe',
    },
    {
        title: 'Failure Analysis (PWA-PCB, 5x) main ones (resonant converter, power supply and post regulator.',
        company: 'Failure Analysis | SLB',
        year: 'TODO: year',
        domain: 'TODO: domain',
        category: 'engineering',
        status: null,
        outcome: 'TODO: outcome line',
        image: '82674a56-a5c4-4667-90ed-0f1a3046776b.jpg',
        color: '#dbeafe',
    },
    {
        title: 'Sensor Signal generator',
        company: 'SLB',
        year: 'TODO: year',
        domain: 'TODO: domain',
        category: 'product',
        status: null,
        outcome: 'TODO: outcome line',
        image: 'Gemini_Generated_Image_dwoxzldwoxzldwox.png',
        color: '#dbeafe',
    },
    {
        title: 'Ornithopter for Surveillance',
        company: 'SRM UAV ',
        year: 'TODO: year',
        domain: 'TODO: domain',
        category: 'product',
        status: null,
        outcome: 'TODO: outcome line',
        image: 'Image__20_.jpg',
        href: 'https://drive.google.com/drive/u/0/folders/1v5Woj-5XMv07hJ-PMSneMdFDRAmq5nQs',
        color: '#dbeafe',
    },
    {
        title: 'Carbon Positive e-car',
        company: 'Ricky Kids',
        year: 'TODO: year',
        domain: 'TODO: domain',
        category: 'product',
        status: null,
        outcome: 'TODO: outcome line',
        image: 'Gemini_Generated_Image_y44ktyy44ktyy44k.png',
        href: 'https://drive.google.com/drive/u/0/folders/1UFIFRPfj_T6rlZwSt5imc6q1aBv4Wm-e',
        color: '#dbeafe',
    },
    {
        title: 'UAV-Aided Weather Radar Calibration',
        company: 'NIT Tiruchirapalli  & SRM University ',
        year: 'TODO: year',
        domain: 'TODO: domain',
        category: 'product',
        status: null,
        outcome: 'TODO: outcome line',
        image: 'Gemini_Generated_Image_wzokgjwzokgjwzok.png',
        href: 'https://drive.google.com/drive/u/0/folders/1rDmPZo8yHV0OFcVruwNqiDJHfU8SeUED',
        color: '#dbeafe',
    },
    {
        title: 'Non contact based COVID patient monitoring system',
        company: 'Ricky Kids',
        year: 'TODO: year',
        domain: 'TODO: domain',
        category: 'product',
        status: null,
        outcome: 'TODO: outcome line',
        image: 'Gemini_Generated_Image_fpkpjsfpkpjsfpkp.png',
        href: 'https://drive.google.com/drive/u/0/folders/198wp9t5QOvHIX3rZbVzw9IehQD7HToc5',
        color: '#dbeafe',
    },
    {
        title: 'Triple riding avoidance',
        company: 'Ricky Kids ',
        year: 'TODO: year',
        domain: 'TODO: domain',
        category: 'product',
        status: null,
        outcome: 'TODO: outcome line',
        image: 'Gemini_Generated_Image_6d6qur6d6qur6d6q.png',
        href: 'https://drive.google.com/drive/u/0/folders/11Bx3DJGQsSQoCqb6T8OjxarnfehbDbIk',
        color: '#dbeafe',
    },
    {
        title: 'Toys for autistic kids',
        company: 'Ricky Kids ',
        year: 'TODO: year',
        domain: 'TODO: domain',
        category: 'product',
        status: null,
        outcome: 'TODO: outcome line',
        image: 'Screenshot_2026-07-06_161758.png',
        href: 'https://drive.google.com/drive/u/0/folders/14Cx5kE8ckME3dmSky9t9Eryn2wERSMcC',
        color: '#dbeafe',
    },
    {
        title: 'Sludge-Traversing ROV',
        company: 'Ricky Kids ',
        year: 'TODO: year',
        domain: 'TODO: domain',
        category: 'product',
        status: null,
        outcome: 'TODO: outcome line',
        image: 'Gemini_Generated_Image_gx3u69gx3u69gx3u.png',
        href: 'https://drive.google.com/drive/u/0/folders/1xcXPJ-9sD7xQWy-5TUwYhE5nlHJs1pqI',
        color: '#dbeafe',
    },
    {
        title: 'Testing of AD 8232 with NI instruments & LABVIEW',
        company: 'Ricky Kids ',
        year: 'TODO: year',
        domain: 'TODO: domain',
        category: 'engineering',
        status: null,
        outcome: 'TODO: outcome line',
        image: 'Screenshot_2026-07-06_162431.png',
        href: 'https://docs.google.com/document/d/1qxaBf6EwlEZ8k95nHYRiDybBt1BD-BExT1NqvUNzVHg/edit?tab=t.0',
        color: '#dbeafe',
    },
    {
        title: 'Obstacle Avoidance Robot using Ultrasonic Sensor',
        company: 'Vyorius ',
        year: 'TODO: year',
        domain: 'TODO: domain',
        category: 'engineering',
        status: null,
        outcome: 'TODO: outcome line',
        image: 'Gemini_Generated_Image_2gvvx02gvvx02gvv.png',
        href: 'https://docs.google.com/document/d/1NrzaG24wBFJQj_O4VZSROqNsbwcyjNw5/edit',
        color: '#dbeafe',
    },
    {
        title: 'FSM Designs: Mealy & Moore Machines and Up Down Counter',
        company: 'Vyorius ',
        year: 'TODO: year',
        domain: 'TODO: domain',
        category: 'engineering',
        status: null,
        outcome: 'TODO: outcome line',
        image: 'Screenshot_2026-07-06_174001.png',
        href: 'https://docs.google.com/document/d/1DM0qEisVqD07y9ZpJcE0AUy-JdPhbibj/edit',
        color: '#dbeafe',
    },
    {
        title: 'Circuits written in Verilog/VHDL, simulated and implemented on the FPGA',
        company: 'Vyorius ',
        year: 'TODO: year',
        domain: 'TODO: domain',
        category: 'engineering',
        status: null,
        outcome: 'TODO: outcome line',
        image: 'Screenshot_2026-07-06_174606.png',
        href: 'https://docs.google.com/document/d/10xzoWqieysAcCH_9pJP21YPoNWrjT9b8/edit',
        color: '#dbeafe',
    },
    {
        title: 'UART communication to print a single character',
        company: 'Vyorius ',
        year: 'TODO: year',
        domain: 'TODO: domain',
        category: 'engineering',
        status: null,
        outcome: 'TODO: outcome line',
        image: 'Screenshot_2026-07-06_182741.png',
        href: 'https://docs.google.com/document/d/1nay8EmttD2w6yuVMpCoJUHsu2UNGEPJL/edit',
        color: '#dbeafe',
    },
    {
        title: '16-Bit RISC Processor',
        company: 'Vyorius ',
        year: 'TODO: year',
        domain: 'TODO: domain',
        category: 'engineering',
        status: null,
        outcome: 'TODO: outcome line',
        image: 'Screenshot_2026-07-06_183032.png',
        href: 'https://docs.google.com/document/d/1zCY0TZJ2UW7helKCK5UhQJ9bhLdnA0_H/edit',
        color: '#dbeafe',
    },
    {
        title: 'IoT based on smart Agriculture System',
        company: 'Vyorius ',
        year: 'TODO: year',
        domain: 'TODO: domain',
        category: 'engineering',
        status: null,
        outcome: 'TODO: outcome line',
        image: 'Screenshot_2026-07-06_183307.png',
        href: 'https://docs.google.com/document/d/1fnXjTPe5c2aOFD0W8ZlrmUC8LkFHQJ_f/edit',
        color: '#dbeafe',
    },
    {
        title: 'RGB Pattern',
        company: 'Vyorius ',
        year: 'TODO: year',
        domain: 'TODO: domain',
        category: 'engineering',
        status: null,
        outcome: 'TODO: outcome line',
        image: 'Screenshot_2026-07-06_183600.png',
        href: 'https://docs.google.com/document/d/1FE9loSRYIwWPt6Q2_5IB_jqJ_VY7rI9-/edit',
        color: '#dbeafe',
    },
    {
        title: 'World map covid-19 dashboard',
        company: 'Vyorius ',
        year: 'TODO: year',
        domain: 'TODO: domain',
        category: 'engineering',
        status: null,
        outcome: 'TODO: outcome line',
        image: 'Screenshot_2026-07-06_183826.png',
        href: 'https://docs.google.com/document/d/1aQkLDDcX5mvwUBzbkiDYodOWn6N6M5cM/edit',
        color: '#dbeafe',
    },
    {
        title: 'Voice Control Home Automation',
        company: 'Vyorius ',
        year: 'TODO: year',
        domain: 'TODO: domain',
        category: 'engineering',
        status: null,
        outcome: 'TODO: outcome line',
        image: 'Screenshot_2026-07-06_184124.png',
        href: 'https://docs.google.com/document/d/1hOuPP4wIkxm0z535LyFsi8bingr9xNQB/edit',
        color: '#dbeafe',
    },
    {
        title: 'Home automation with Automatic Room Temperature Controller',
        company: 'MSME Technology Development Centre, Govt. of India',
        year: 'TODO: year',
        domain: 'TODO: domain',
        category: 'engineering',
        status: null,
        outcome: 'TODO: outcome line',
        image: 'Screenshot_2026-07-06_192816.png',
        href: 'https://docs.google.com/presentation/d/1eF7KPmWUSfztWLRwHLzZ_9DMAFwMe8KW/edit?slide=id.p11#slide=id.p11',
        color: '#dbeafe',
    },
    {
        title: '3-bit Binary to Grey Code Converter using Low Voltage XOR Gates',
        company: 'Hackathon | IIT Hyderabad',
        year: 'TODO: year',
        domain: 'TODO: domain',
        category: 'engineering',
        status: null,
        outcome: 'TODO: outcome line',
        image: 'Screenshot_2026-07-06_185716.png',
        href: 'https://drive.google.com/drive/u/0/folders/1nP-K9XsWjmGpQfBTMgybo-LYUvGGbYTO',
        color: '#dbeafe',
    },
    {
        title: 'FIRST ROBOT',
        company: 'Intern | MSME Technology Development Centre, Govt. of India',
        year: 'TODO: year',
        domain: 'TODO: domain',
        category: 'engineering',
        status: null,
        outcome: 'TODO: outcome line',
        image: 'Screenshot_2026-07-06_190925.png',
        color: '#dbeafe',
    },
    {
        title: 'LCD',
        company: 'Intern | MSME Technology Development Centre, Govt. of India',
        year: 'TODO: year',
        domain: 'TODO: domain',
        category: 'engineering',
        status: null,
        outcome: 'TODO: outcome line',
        image: 'Screenshot_2026-07-06_191645.png',
        href: 'https://drive.google.com/drive/u/0/search?q=MSME',
        color: '#dbeafe',
    },
    {
        title: 'Timer',
        company: 'Intern | MSME Technology Development Centre, Govt. of India',
        year: 'TODO: year',
        domain: 'TODO: domain',
        category: 'engineering',
        status: null,
        outcome: 'TODO: outcome line',
        image: 'Screenshot_2026-07-06_191902.png',
        href: 'https://drive.google.com/drive/u/0/search?q=MSME',
        color: '#dbeafe',
    },
    {
        title: 'First signal',
        company: 'Intern | MSME Technology Development Centre, Govt. of India',
        year: 'TODO: year',
        domain: 'TODO: domain',
        category: 'engineering',
        status: null,
        outcome: 'TODO: outcome line',
        image: 'Screenshot_2026-07-06_192015.png',
        href: 'https://drive.google.com/drive/u/0/search?q=MSME',
        color: '#dbeafe',
    },
    {
        title: 'ENVI-City — Vision of a sustainable smart city of the future',
        company: 'Ricky Kids',
        year: 'TODO: year',
        domain: 'TODO: domain',
        category: 'product',
        status: null,
        outcome: 'TODO: outcome line',
        image: 'Gemini_Generated_Image_orqf1borqf1borqf.png',
        href: 'https://drive.google.com/drive/u/0/folders/1XhqFiIQJZtQN9ZVzuRBbMfDo5szeg9W0',
        color: '#dbeafe',
    },
];

export const filters = [
    { key: 'all', label: 'All' },
    { key: 'product', label: 'Product' },
    { key: 'engineering', label: 'Engineering' },
] as const;

export type FilterKey = (typeof filters)[number]['key'];
