import type { WorkItem } from './types';

/**
 * Status system — the ONLY valid values are the five below plus `null`.
 * Colour encodes how far the work went, not what kind of thing it is,
 * so there are three colour families across five statuses.
 *
 * Adding a sixth status should be a one-line change here, not a hunt
 * through components. Both the grid badge and the case-study badge read
 * from this object.
 */
export const STATUS_CONFIG: Record<
	NonNullable<WorkItem['status']>,
	{ label: string; colorClass: string }
> = {
	production: { label: 'In production', colorClass: 'status-green' },
	internal: { label: 'Shipped internally', colorClass: 'status-green' },
	'customer-testing': {
		label: 'In customer testing',
		colorClass: 'status-amber',
	},
	prototype: { label: 'Prototype', colorClass: 'status-muted' },
	research: { label: 'Research', colorClass: 'status-muted' },
};

/**
 * Grid sort order. Because every card is the same size, sort carries the
 * hierarchy: status group first, newest year first inside each group,
 * then data-file order so it can be hand-tuned. Applies in every filter view.
 */
export const STATUS_ORDER: Record<string, number> = {
	production: 1,
	internal: 2,
	'customer-testing': 3,
	prototype: 4,
	research: 5,
	null: 6,
};

export const workItems: WorkItem[] = [
	{
		title: 'Wi-R Body Area Network — YR31',
		company: 'Ixana',
		year: '2024 - present',
		domain: 'Silicon',
		category: 'product',
		track: 'silicon',
		status: 'production',
		outcome:
			'Second-generation body-area silicon that holds an on-body link in the single-digit milliwatt class, roughly a tenth of the radio budget it replaces.',
		image: 'Image__2_.jpg',
		href: 'https://www.ixana.ai/products/chips/wi-r-ban',
		slug: 'wi-r-ban-yr31',
		tier: 1,
		demoUrl: 'https://www.ixana.ai/products/chips/wi-r-ban',
		color: '#dbeafe',
	},
	{
		title: 'Wi-R Dev Kits — BAN YR23 and NFE XA-NFE2001',
		company: 'Ixana',
		year: '2024 - present',
		domain: 'Developer hardware',
		category: 'product',
		track: 'silicon',
		status: 'production',
		outcome:
			'Turned Wi-R eval silicon into a shipping dev kit built around one acceptance bar: open the box, reach an on-body link the same day — every variable that killed early bring-ups fixed inside it.',
		image: 'Image__10_.jpg',
		href: 'https://www.ixana.ai/products/dev-kits',
		slug: 'wi-r-dev-kits-ban-yr23-and-nfe-xa-nfe2001',
		tier: 3,
		demoUrl: 'https://www.ixana.ai/products/dev-kits',
		color: '#dbeafe',
	},
	{
		title: 'Ixana-Wiki — multifile RAG knowledge platform',
		company: 'Ixana',
		year: '2025',
		domain: 'Internal platform',
		category: 'product',
		track: 'ai',
		status: 'internal',
		outcome:
			'Cut the median hunt for a document from nine minutes to under one, and put 118 of 140 employees on a single search box.',
		image: 'Gemini_Generated_Image_anlzx7anlzx7anlz.png',
		slug: 'xana-multifile-rag-based-data-singularity-platform',
		tier: 1,
		demoUrl: 'https://xana-nine.vercel.app/',
		color: '#dbeafe',
	},
	{
		title: 'Dāsa — citation-grounded scripture engine',
		company: 'ISKCON (International Society for Krishna Consciousness) ',
		year: '2026 - present',
		domain: 'Applied AI',
		category: 'product',
		track: 'ai',
		status: 'research',
		outcome:
			'A deterministic guard strips any citation retrieval never returned — fabrication is prevented by architecture, not reduced by prompting — and a distance gate makes refusal a first-class answer.',
		image: 'Image__1_.jpg',
		slug: 'dsa-generative-ai-engine-for-a-guided-spiritual-path',
		tier: 1,
		color: '#dbeafe',
	},
	{
		title: 'Wi-R Body Area Network — YR23',
		company: 'Ixana',
		year: '2024 - present',
		domain: 'Silicon',
		category: 'product',
		track: 'silicon',
		status: 'production',
		outcome:
			'The first Wi-R body-area part to reach customer hardware — the silicon under the BAN dev kit and every on-body reference design that followed.',
		image: 'Image__3_.jpg',
		href: 'https://www.ixana.ai/products/chips/wi-r-ban',
		slug: 'wi-r-ban-yr23',
		tier: 3,
		demoUrl: 'https://www.ixana.ai/products/chips/wi-r-ban',
		color: '#ffedd5',
	},
	{
		title: 'NeuroAdapt — spike-train feature extraction for a science compiler',
		company: 'NeuroAdapt, IISc Bangalore',
		year: '2023 - present',
		domain: 'Research tooling',
		category: 'product',
		track: 'ai',
		status: 'research',
		outcome:
			'Replaced ad-hoc spike-train scripts with one standardized feature set, so two labs computing "burst index" finally mean the same thing.',
		image: 'demo-card-neuroadapt.jpg',
		href: 'https://drive.google.com/drive/u/0/folders/1B0mtA9-xkNbbo6ZUXztuHZiMmlovNtLw',
		demoUrl: '/demo/neuroadapt',
		slug: 'neuroadapt-agentic-rag-engine-for-neuroscience-research',
		tier: 3,
		color: '#dbeafe',
	},
	{
		title: 'Wi-R Near Field Electric — XA-NFE3001',
		company: 'Ixana',
		year: '2024 - present',
		domain: 'Silicon',
		category: 'product',
		track: 'silicon',
		status: 'production',
		outcome:
			'Successor near-field part: 20 Mbit/s PHY, ~13.5 Mbit/s real throughput — a 100 MB firmware image inside a one-minute service window, on the same sub-6 mW budget.',
		image: 'Image__8_.jpg',
		href: 'https://www.ixana.ai/products/chips/wi-r-nfe',
		slug: 'wi-r-nfe-xa-nfe3001',
		tier: 3,
		demoUrl: 'https://www.ixana.ai/products/chips/wi-r-nfe',
		color: '#dbeafe',
	},
	{
		title: 'Wi-R Near Field Electric — XA-NFE2001',
		company: 'Ixana',
		year: '2024 - 2026',
		domain: 'Silicon',
		category: 'product',
		track: 'silicon',
		status: 'production',
		outcome:
			'The near-field electric part that moved Wi-R from a lab demonstration to a component a partner could design into a product.',
		image: 'Image__9_.jpg',
		href: 'https://www.ixana.ai/products/chips/wi-r-nfe',
		slug: 'wi-r-nfe-xa-nfe2001',
		tier: 3,
		demoUrl: 'https://www.ixana.ai/products/chips/wi-r-nfe',
		color: '#dbeafe',
	},
	{
		title: 'Accurate estimation of mineral present in soil',
		company: 'IIRS-ISRO, Govt. of India',
		year: '2022',
		domain: 'Remote sensing',
		category: 'product',
		track: 'ai',
		status: 'internal',
		outcome:
			'Hyperspectral workflow that estimated surface mineral abundance from satellite bands, taking a field-sampling round out of the survey loop.',
		tier: 4,
		image: 'Image__5_.jpg',
		href: 'https://drive.google.com/drive/u/0/folders/1tYViz5kUrsL5PZ_9DsghxZ1uno1qYQzs',
		color: '#dbeafe',
	},
	{
		title: 'Quantum Gate Simulator — interactive 10-qubit circuit builder',
		company: 'Personal',
		year: '2026 - present',
		domain: 'Learning tools',
		category: 'product',
		track: 'ai',
		status: 'prototype',
		outcome:
			'A working 10-qubit simulator with real-time 3D Bloch rendering; it stayed a prototype and never went out to learners.',
		image: 'demo-card-quantum-simulator.jpg',
		slug: 'quantum-circuit-simulator-interactive-10-qubit-delivering-re',
		tier: 3,
		demoUrl: '/demo/quantum-simulator',
		color: '#dbeafe',
	},
	{
		title: 'Procurement Orchestrator — M365-native request workflow',
		company: 'Ixana',
		year: '2026 ',
		domain: 'Procurement ops',
		category: 'product',
		track: 'ai',
		status: 'customer-testing',
		outcome:
			'In pilot: the operating contract names one accountable owner within a business day, and a status transition cannot be written without evidence.',
		image: 'demo-card-procurement-desk.jpg',
		slug: 'procurement-orchestrator-procurement-process-automation-with',
		tier: 2,
		demoUrl: '/demo/procurement-desk',
		color: '',
	},
	{
		title: 'WishKey — Key Management System',
		company: 'EEGRAB',
		year: '2023',
		domain: 'Access control',
		category: 'product',
		track: 'silicon',
		status: 'production',
		outcome:
			'Replaced a paper key register with an audited electronic cabinet, shipped as a catalogue product with per-key accountability.',
		image: 'Image__1_.png',
		href: 'https://eegrab.com/wp-content/uploads/2021/brochure/Wishkey_brochure.pdf',
		slug: 'eegrab-wishkey',
		tier: 3,
		demoUrl: 'https://www.youtube.com/watch?v=8etIl_0wj0I',
		color: '#dbeafe',
	},
	{
		title: 'Wi-R reference designs — video smartglasses and tactical headset',
		company: 'Ixana',
		year: '2024 - 2026',
		domain: 'Wearable systems',
		category: 'product',
		track: 'silicon',
		status: 'production',
		outcome:
			'Reference designs proving Wi-R carries live video to smartglasses and voice to a tactical radio over the body rather than the air.',
		image: 'Gemini_Generated_Image_ef658pef658pef65.png',
		href: 'https://www.ixana.ai/products/reference-designs',
		slug: 'wi-r-reference-designs',
		tier: 3,
		demoUrl: 'https://www.ixana.ai/products/reference-designs',
		color: '#dbeafe',
	},
	{
		title: 'Cost-effective smart watch',
		company: 'EEGRAB',
		year: '2023',
		domain: 'Consumer wearable',
		category: 'product',
		track: 'silicon',
		status: 'production',
		outcome:
			'Cut the smartwatch bill of materials to a price Indian retail could carry while keeping heart-rate sensing and phone notifications.',
		image: 'Gemini_Generated_Image_io6t60io6t60io6t.png',
		slug: 'eegrab-smart-watch',
		tier: 3,
		color: '#dbeafe',
	},
	{
		title: 'The internal AI program — fourteen tools, one doctrine',
		company: 'Ixana',
		year: '2025 - 2026',
		domain: 'Internal platform',
		category: 'product',
		track: 'ai',
		status: 'internal',
		tier: 2,
		programHead: true,
		outcome:
			'What it is to build the internal AI operating system of a silicon company: fourteen tools under one doctrine — deterministic counts, model-written prose, provenance on every claim, and refusal where the data runs out.',
		image: 'ixana-wiki-search.jpg',
		slug: 'ixana-internal-ai-program',
		demoUrl: 'https://xana-nine.vercel.app/',
		color: '#dbeafe',
	},
	{
		title: 'Team performance reporting — five teams, three windows',
		company: 'Ixana',
		year: '2026 ',
		domain: 'Delivery reporting',
		category: 'product',
		track: 'ai',
		status: 'internal',
		outcome:
			'One engine produces the weekly, monthly and quarterly performance report for all five delivery teams — four of which had no standing report at all.',
		image: 'demo-card-team-performance.jpg',
		slug: 'team-performance-reporting',
		tier: 2,
		demoUrl: '/demo/team-performance',
		color: '#ddd6fe',
	},
	{
		title: 'Scrum ecosystem — one workspace for sprint ceremonies',
		company: 'Ixana',
		year: '2026',
		domain: 'Agile tooling',
		category: 'product',
		track: 'ai',
		status: 'internal',
		outcome:
			'Standup, backlog and burndown now read from the same task data instead of three separately maintained views.',
		image: 'demo-card-scrum-desk.jpg',
		slug: 'ixana-scrum-ecosystem',
		tier: 2,
		demoUrl: '/demo/scrum-desk',
		color: '#fae8ff',
	},
	{
		title: 'Flow Tracker — real-time delivery pipeline diagnostics',
		company: 'Ixana',
		year: '2026',
		domain: 'Engineering ops',
		category: 'product',
		track: 'ai',
		status: 'internal',
		outcome:
			'One live view across the PS, AMS and RTL pipelines — three stage vocabularies kept, one shared surface, and an assistant that answers from filtered records or refuses.',
		image: 'Gemini_Generated_Image_8c4hfs8c4hfs8c4h.png',
		slug: 'ai-pm-generative-ai-engine-for-real-time-pipeline-diagnostic',
		tier: 1,
		demoUrl: 'https://xana-nine.vercel.app/efficiency?view=tracker',
		color: '#fae8ff',
	},
	{
		title: 'ClickUp Activity Tracker — task change audit trail',
		company: 'Ixana',
		year: '2026',
		domain: 'Audit tooling',
		category: 'product',
		track: 'ai',
		status: 'internal',
		outcome:
			'Turned a raw activity feed into a searchable who-changed-what timeline — previous values retained, raw payloads stored before parsing, every retry deduplicated.',
		image: 'demo-card-clickup-audit.jpg',
		slug: 'github-for-clickup-automation-on-the-changes-going-outside-p',
		tier: 2,
		demoUrl: '/demo/clickup-audit',
		color: '#fae8ff',
	},
	{
		title: 'Video library and meeting recordings',
		company: 'Ixana',
		year: '2026',
		domain: 'Meeting intelligence',
		category: 'product',
		track: 'ai',
		status: 'internal',
		outcome:
			'Made every recording searchable by transcript, so people jump to the minute that matters instead of scrubbing an hour of video.',
		image: 'Gemini_Generated_Image_i9dz41i9dz41i9dz.png',
		slug: 'ixana-video-library-automated-company-video-library',
		tier: 2,
		demoUrl: 'https://xana-nine.vercel.app/videolibrary',
		color: '#fae8ff',
	},
	{
		title: 'Calendar sync — Outlook and Gmail without leaking detail',
		company: 'Ixana',
		year: '2025',
		domain: 'Workplace automation',
		category: 'product',
		track: 'ai',
		status: 'internal',
		outcome:
			'Kept two calendar tenants in step without a single event title able to cross - reflected time is an opaque block by design, and every write previews before it lands.',
		image: 'Gemini_Generated_Image_18w83818w83818w8.png',
		slug: 'calendar-automation-real-time-bi-directional-sync-engine-wit',
		tier: 2,
		color: '#fae8ff',
	},
	{
		title: 'AI Salary Generator',
		company: 'Ixana',
		year: '2026 - present',
		domain: 'HR tooling',
		category: 'product',
		track: 'ai',
		status: 'customer-testing',
		outcome:
			'In pilot: benchmarks a role against market bands and drafts an offer range where every figure traces back to its source.',
		image: 'demo-card-salary-bands.jpg',
		slug: 'ai-salary-generator',
		tier: 2,
		href: 'https://www.ixana.ai/products',
		demoUrl: '/demo/salary-bands',
		color: '#fee2e2',
	},
	{
		title: 'AI product planning operating system',
		company: 'Ixana',
		year: '2026',
		domain: 'Planning tooling',
		category: 'product',
		track: 'ai',
		status: 'internal',
		outcome:
			'Turns a raw brief into a reviewed, execution-ready plan — a different model must approve the planner\'s work, enforced in code, and unknowns stop the pipeline instead of being papered over.',
		image: 'demo-card-prd-os.jpg',
		slug: 'ai-prd-multi-agent-multi-llm-shared-memory-generative-system',
		tier: 2,
		demoUrl: '/demo/prd-os',
		color: '#dbeafe',
	},
	{
		title: 'AI Lawyer — multi-agent patent drafting system',
		company: 'Ixana',
		year: '2026',
		domain: 'Legal tooling',
		category: 'product',
		track: 'ai',
		status: 'prototype',
		outcome:
			'Drafts an attorney-review filing package — and refuses a novelty conclusion when the search looked in the wrong art, with the roadmap-deciding corpus measurement real and computed over public patent data.',
		image: 'demo-card-ai-lawyer.jpg',
		slug: 'ai-lawyer-multi-agent-multi-llm-shared-memory-generative-sys',
		tier: 1,
		demoUrl: '/demo/ai-lawyer',
		color: '#dbeafe',
	},
	{
		title: 'ClickUp reporting and Gantt dashboard',
		company: 'Ixana',
		year: '2026',
		domain: 'PM tooling',
		category: 'product',
		track: 'ai',
		status: 'internal',
		outcome:
			'Gave leads a read-only Gantt and bandwidth view over live task data, with AI explaining why each late task actually slipped.',
		image: 'demo-card-clickup-gantt.jpg',
		slug: 'ai-pm-customized-multi-view-for-pms',
		tier: 2,
		demoUrl: '/demo/clickup-gantt',
		color: '#dbeafe',
	},
	{
		title: 'In-house meeting notetaker',
		company: 'Ixana',
		year: '2026',
		domain: 'Meeting intelligence',
		category: 'product',
		track: 'ai',
		status: 'internal',
		outcome:
			'Kept transcripts and minutes inside the tenant instead of routing every internal meeting through a third-party bot.',
		image: 'Image__18_.jpg',
		slug: 'ixana-meeting-notetaker',
		tier: 2,
		demoUrl: 'https://xana-nine.vercel.app/meetingrecordings',
		color: '#dbeafe',
	},
	{
		title: 'Patent program operations',
		company: 'Ixana',
		year: '2026',
		domain: 'Patent operations',
		category: 'product',
		track: 'ai',
		status: 'internal',
		outcome:
			'Owned 50+ filings across six Wi-R product lines end to end - what to protect, how broadly, when to file - with filing decisions anchored to the tapeout calendar.',
		image: 'Gemini_Generated_Image_strjxvstrjxvstrj.png',
		slug: 'ixana-patent-program',
		tier: 2,
		demoUrl: 'https://xana-nine.vercel.app/patents',
		color: '#dbeafe',
	},
	{
		title: 'Document change intelligence',
		company: 'Ixana',
		year: '2026',
		domain: 'Documentation ops',
		category: 'product',
		track: 'ai',
		status: 'internal',
		outcome:
			'A daily sync that versions and diffs every workspace document - immutable versions only on real content change, and nothing tracked is ever pruned.',
		image: 'Gemini_Generated_Image_jt9prtjt9prtjt9p.png',
		slug: 'clickup-document-tracker-data-extraction-easy-visibility-for',
		tier: 2,
		demoUrl: 'https://xana-nine.vercel.app/myfiles?tab=clickup',
		color: '#dbeafe',
	},
	{
		title: 'Condenser microphone',
		company: 'EEGRAB',
		year: '2024',
		domain: 'Audio hardware',
		category: 'product',
		track: 'silicon',
		status: 'production',
		outcome:
			'Refused to sort capsules and calibrated every unit instead — gain taken passively in a transformer before any active part, and a trim that may correct but never rescue.',
		image: 'Gemini_Generated_Image_cqoga8cqoga8cqog.png',
		slug: 'eegrab-condenser-microphone',
		tier: 3,
		color: '#dbeafe',
	},
	{
		title:
			'Board failure analysis — resonant converter, supply and post regulator',
		company: 'Failure Analysis | SLB',
		year: '2023',
		domain: 'Failure analysis',
		category: 'engineering',
		status: null,
		outcome:
			'Root-caused five recurring board failures and fed each fix back into the build standard so the next revision stopped repeating them.',
		image: '82674a56-a5c4-4667-90ed-0f1a3046776b.jpg',
		color: '#dbeafe',
	},
	{
		slug: 'slb-sensor-signal-generator',
		tier: 3,
		title: 'Sensor signal generator',
		company: 'SLB',
		year: '2023',
		domain: 'Test engineering',
		category: 'product',
		track: 'silicon',
		status: 'production',
		outcome:
			'Bench instrument that synthesised downhole sensor signals, so tool electronics could be tested without waiting on a well.',
		image: 'Gemini_Generated_Image_dwoxzldwoxzldwox.png',
		color: '#dbeafe',
	},
	{
		title: 'Ornithopter for surveillance',
		company: 'SRM UAV ',
		year: '2021 - 2023',
		domain: 'Aerial robotics',
		category: 'product',
		track: 'silicon',
		status: 'prototype',
		outcome:
			'Flapping-wing surveillance airframe that flew a stable circuit; it stayed in the lab and never went to an operator.',
		image: 'Image__20_.jpg',
		slug: 'srm-uav-ornithopter-for-surveillance',
		tier: 3,
		demoUrl: '/demo/ornithopter-concept',
		href: 'https://drive.google.com/drive/u/0/folders/1v5Woj-5XMv07hJ-PMSneMdFDRAmq5nQs',
		color: '#dbeafe',
	},
	{
		title: 'Carbon positive e-car',
		company: 'Ricky Kids',
		year: '2020',
		domain: 'Sustainable mobility',
		category: 'product',
		track: 'silicon',
		status: 'research',
		outcome:
			'Feasibility study on whether a small EV could offset more carbon than it embodied — the answer turned entirely on grid mix.',
		image: 'Gemini_Generated_Image_y44ktyy44ktyy44k.png',
		slug: 'ricky-kids-carbon-positive-ev',
		tier: 3,
		href: 'https://drive.google.com/drive/u/0/folders/1UFIFRPfj_T6rlZwSt5imc6q1aBv4Wm-e',
		color: '#dbeafe',
	},
	{
		title: 'UAV-aided weather radar calibration',
		company: 'NIT Tiruchirapalli  & SRM University ',
		year: '2022',
		domain: 'Weather instrumentation',
		category: 'product',
		track: 'silicon',
		status: 'research',
		outcome:
			'Tested whether a UAV-carried reflector could calibrate ground weather radar in place, instead of a fixed tower reference.',
		image: 'demo-card-radar.jpg',
		slug: 'ricky-kids-uav-weather-radar-calibration',
		tier: 3,
		demoUrl: '/demo/radar-error-budget',
		href: 'https://drive.google.com/drive/u/0/folders/1rDmPZo8yHV0OFcVruwNqiDJHfU8SeUED',
		color: '#dbeafe',
	},
	{
		title: 'Non-contact COVID patient monitoring',
		company: 'Ricky Kids',
		year: '2021',
		domain: 'Health sensing',
		category: 'product',
		track: 'silicon',
		status: 'research',
		outcome:
			'Bench-tested which vital signs survive distance: temperature and respiration have a non-contact route; the two staff escalate on do not — a study that concluded against its own premise.',
		image: 'demo-card-covid-bench.jpg',
		slug: 'ricky-kids-noncontact-covid-monitoring',
		tier: 3,
		demoUrl: '/demo/covid-bench',
		href: 'https://drive.google.com/drive/u/0/folders/198wp9t5QOvHIX3rZbVzw9IehQD7HToc5',
		color: '#dbeafe',
	},
	{
		title: 'Triple riding avoidance',
		company: 'Ricky Kids ',
		year: '2022',
		domain: 'Road safety',
		category: 'product',
		track: 'ai',
		status: 'internal',
		outcome:
			'Vision model that flagged three-up motorcycle riding in roadside footage, used internally to score road-safety survey clips.',
		image: 'demo-card-rider-count.jpg',
		slug: 'ricky-kids-triple-riding-avoidance',
		tier: 1,
		demoUrl: '/demo/rider-count',
		href: 'https://drive.google.com/drive/u/0/folders/11Bx3DJGQsSQoCqb6T8OjxarnfehbDbIk',
		color: '#dbeafe',
	},
	{
		title: 'Toys for autistic kids',
		company: 'Ricky Kids ',
		year: '2021 - 2023',
		domain: 'Assistive play',
		category: 'product',
		track: 'silicon',
		status: 'prototype',
		outcome:
			'Sensory play prototypes designed with two special-education teachers — built and demonstrated, never taken past the workshop.',
		image: 'demo-card-autism-bench.jpg',
		slug: 'ricky-kids-toys-for-autistic-kids',
		tier: 3,
		demoUrl: '/demo/autism-bench',
		href: 'https://drive.google.com/drive/u/0/folders/14Cx5kE8ckME3dmSky9t9Eryn2wERSMcC',
		color: '#dbeafe',
	},
	{
		title: 'Sludge-traversing ROV',
		company: 'Ricky Kids ',
		year: '2022',
		domain: 'Field robotics',
		category: 'product',
		track: 'silicon',
		status: 'research',
		outcome:
			'Studied whether a tracked ROV could cross settled sludge without fluidising it — traction failed below a density threshold.',
		image: 'demo-card-sludge.jpg',
		slug: 'ricky-kids-sludge-traversing-rov',
		tier: 3,
		demoUrl: '/demo/sludge-envelope',
		href: 'https://drive.google.com/drive/u/0/folders/1xcXPJ-9sD7xQWy-5TUwYhE5nlHJs1pqI',
		color: '#dbeafe',
	},
	{
		title: 'Testing AD8232 with NI instruments and LabVIEW',
		company: 'Ricky Kids ',
		year: '2021',
		domain: 'Test engineering',
		category: 'engineering',
		status: null,
		outcome:
			'Characterised an ECG front end against NI instrumentation and documented where its datasheet bandwidth claims actually held.',
		image: 'Screenshot_2026-07-06_162431.png',
		href: 'https://docs.google.com/document/d/1qxaBf6EwlEZ8k95nHYRiDybBt1BD-BExT1NqvUNzVHg/edit?tab=t.0',
		color: '#dbeafe',
	},
	{
		title: 'Obstacle avoidance robot using ultrasonic sensing',
		company: 'Vyorius ',
		year: '2021',
		domain: 'Embedded systems',
		category: 'engineering',
		status: null,
		outcome:
			'Ultrasonic obstacle-avoidance rover built to learn sensing, filtering and motor control end to end on one platform.',
		image: 'Gemini_Generated_Image_2gvvx02gvvx02gvv.png',
		href: 'https://docs.google.com/document/d/1NrzaG24wBFJQj_O4VZSROqNsbwcyjNw5/edit',
		color: '#dbeafe',
	},
	{
		title: 'FSM designs — Mealy, Moore and an up-down counter',
		company: 'Vyorius ',
		year: '2021',
		domain: 'Digital design',
		category: 'engineering',
		status: null,
		outcome:
			'Mealy and Moore machines plus an up-down counter, simulated and checked against a written test plan rather than by eye.',
		image: 'Screenshot_2026-07-06_174001.png',
		href: 'https://docs.google.com/document/d/1DM0qEisVqD07y9ZpJcE0AUy-JdPhbibj/edit',
		color: '#dbeafe',
	},
	{
		title: 'Verilog and VHDL circuits implemented on FPGA',
		company: 'Vyorius ',
		year: '2021',
		domain: 'Digital design',
		category: 'engineering',
		status: null,
		outcome:
			'Closed the loop from RTL to hardware on a set of standard circuits — written, simulated, synthesised and run on the board.',
		image: 'Screenshot_2026-07-06_174606.png',
		href: 'https://docs.google.com/document/d/10xzoWqieysAcCH_9pJP21YPoNWrjT9b8/edit',
		color: '#dbeafe',
	},
	{
		title: 'UART transmitter printing a single character',
		company: 'Vyorius ',
		year: '2021',
		domain: 'Digital design',
		category: 'engineering',
		status: null,
		outcome:
			'Built a UART transmitter from scratch and proved the framing on a scope before trusting a vendor IP block.',
		image: 'Screenshot_2026-07-06_182741.png',
		href: 'https://docs.google.com/document/d/1nay8EmttD2w6yuVMpCoJUHsu2UNGEPJL/edit',
		color: '#dbeafe',
	},
	{
		title: '16-bit RISC processor',
		company: 'Vyorius ',
		year: '2022',
		domain: 'Digital design',
		category: 'engineering',
		status: null,
		outcome:
			'Designed a 16-bit RISC core with its own instruction set and ran real programs on it in simulation.',
		image: 'Screenshot_2026-07-06_183032.png',
		href: 'https://docs.google.com/document/d/1zCY0TZJ2UW7helKCK5UhQJ9bhLdnA0_H/edit',
		color: '#dbeafe',
	},
	{
		title: 'IoT-based smart agriculture system',
		company: 'Vyorius ',
		year: '2021',
		domain: 'IoT systems',
		category: 'engineering',
		status: null,
		outcome:
			'Soil-moisture and weather sensing that only triggered irrigation when both readings agreed, to cut false watering.',
		image: 'Screenshot_2026-07-06_183307.png',
		href: 'https://docs.google.com/document/d/1fnXjTPe5c2aOFD0W8ZlrmUC8LkFHQJ_f/edit',
		color: '#dbeafe',
	},
	{
		title: 'RGB pattern generator',
		company: 'Vyorius ',
		year: '2021',
		domain: 'Digital design',
		category: 'engineering',
		status: null,
		outcome:
			'Timing-driven RGB pattern generator, written to practise clock division and state encoding on real hardware.',
		image: 'Screenshot_2026-07-06_183600.png',
		href: 'https://docs.google.com/document/d/1FE9loSRYIwWPt6Q2_5IB_jqJ_VY7rI9-/edit',
		color: '#dbeafe',
	},
	{
		title: 'World map COVID-19 dashboard',
		company: 'Vyorius ',
		year: '2021',
		domain: 'Data visualization',
		category: 'engineering',
		status: null,
		outcome:
			'Choropleth dashboard over public COVID feeds, built to learn how to keep a dense map readable at a glance.',
		image: 'Screenshot_2026-07-06_183826.png',
		href: 'https://docs.google.com/document/d/1aQkLDDcX5mvwUBzbkiDYodOWn6N6M5cM/edit',
		color: '#dbeafe',
	},
	{
		title: 'Voice-controlled home automation',
		company: 'Vyorius ',
		year: '2021',
		domain: 'Home automation',
		category: 'engineering',
		status: null,
		outcome:
			'Voice-triggered relay control with a hardware interlock, so a misheard command could not latch a load on.',
		image: 'Screenshot_2026-07-06_184124.png',
		href: 'https://docs.google.com/document/d/1hOuPP4wIkxm0z535LyFsi8bingr9xNQB/edit',
		color: '#dbeafe',
	},
	{
		title: 'Home automation with automatic room temperature control',
		company: 'MSME Technology Development Centre, Govt. of India',
		year: '2020',
		domain: 'Home automation',
		category: 'engineering',
		status: null,
		outcome:
			'Closed-loop room temperature control on a scheduled setpoint, built during an MSME development centre internship.',
		image: 'Screenshot_2026-07-06_192816.png',
		href: 'https://docs.google.com/presentation/d/1eF7KPmWUSfztWLRwHLzZ_9DMAFwMe8KW/edit?slide=id.p11#slide=id.p11',
		color: '#dbeafe',
	},
	{
		title: '3-bit binary to grey code converter using low-voltage XOR gates',
		company: 'Hackathon | IIT Hyderabad',
		year: '2021',
		domain: 'Digital design',
		category: 'engineering',
		status: null,
		outcome:
			'Low-voltage XOR implementation of a 3-bit grey code converter, entered and defended at an IIT Hyderabad hackathon.',
		image: 'Screenshot_2026-07-06_185716.png',
		href: 'https://drive.google.com/drive/u/0/folders/1nP-K9XsWjmGpQfBTMgybo-LYUvGGbYTO',
		color: '#dbeafe',
	},
	{
		title: 'First robot',
		company: 'Intern | MSME Technology Development Centre, Govt. of India',
		year: '2019',
		domain: 'Embedded systems',
		category: 'engineering',
		status: null,
		outcome:
			'A line-following robot — the first build that turned electronics from a subject into something I did on weekends.',
		image: 'Screenshot_2026-07-06_190925.png',
		color: '#dbeafe',
	},
	{
		title: 'Character LCD driver',
		company: 'Intern | MSME Technology Development Centre, Govt. of India',
		year: '2019',
		domain: 'Embedded systems',
		category: 'engineering',
		status: null,
		outcome:
			'Drove a character LCD straight from a bare microcontroller, timing every instruction delay by hand against the datasheet.',
		image: 'Screenshot_2026-07-06_191645.png',
		href: 'https://drive.google.com/drive/u/0/search?q=MSME',
		color: '#dbeafe',
	},
	{
		title: 'Hardware timer',
		company: 'Intern | MSME Technology Development Centre, Govt. of India',
		year: '2019',
		domain: 'Embedded systems',
		category: 'engineering',
		status: null,
		outcome:
			'Countdown timer built on hardware timer peripherals rather than delay loops, to learn why that distinction matters.',
		image: 'Screenshot_2026-07-06_191902.png',
		href: 'https://drive.google.com/drive/u/0/search?q=MSME',
		color: '#dbeafe',
	},
	{
		title: 'First signal',
		company: 'Intern | MSME Technology Development Centre, Govt. of India',
		year: '2019',
		domain: 'Embedded systems',
		category: 'engineering',
		status: null,
		outcome:
			'The first circuit I built that produced a signal I could see on a scope and explain line by line.',
		image: 'Screenshot_2026-07-06_192015.png',
		href: 'https://drive.google.com/drive/u/0/search?q=MSME',
		color: '#dbeafe',
	},
	{
		title: 'ENVI-City — sustainable smart city concept',
		company: 'Ricky Kids',
		year: '2022',
		domain: 'Urban concept',
		category: 'product',
		track: 'silicon',
		status: 'research',
		outcome:
			'Concept study modelling water, power and waste for a city block as one loop rather than three separate utilities.',
		image: 'demo-card-envi-city.jpg',
		slug: 'ricky-kids-envi-city',
		tier: 3,
		demoUrl: '/demo/envi-city',
		href: 'https://drive.google.com/drive/u/0/folders/1XhqFiIQJZtQN9ZVzuRBbMfDo5szeg9W0',
		color: '#dbeafe',
	},
];

export const filters = [
	{ key: 'all', label: 'All' },
	{ key: 'product', label: 'Product' },
	{ key: 'engineering', label: 'Engineering' },
] as const;

export type FilterKey = (typeof filters)[number]['key'];
