export const workItems = [
	{
		title: 'Dāsa | Generative AI Engine for a Guided Spiritual Path',
		location: '',
		services: 'ISKCON (International Society for Krishna Consciousness) ',
		year: '',
		src: 'Image__1_.jpg',
		color: '#dbeafe',
		url: '',
		slug: 'dsa-generative-ai-engine-for-a-guided-spiritual-path',
		categories: ['products'],
	},
	{
		title: 'Wi-R Body Area Network (BAN) | YR31 (In Testing)',
		location: '',
		services: 'Ixana',
		year: '',
		src: 'Image__2_.jpg',
		color: '#dbeafe',
		url: '',
		categories: ['products'],
	},
	{
		title: 'XANA | Multifile RAG based Data Singularity Platform ',
		location: 'Ixana',
		services: 'Ixana',
		year: '',
		src: 'Gemini_Generated_Image_anlzx7anlzx7anlz.png',
		color: '#dbeafe',
		url: '',
		slug: 'xana-multifile-rag-based-data-singularity-platform',
		categories: ['products'],
	},
	{
		title: 'Wi-R Body Area Network (BAN) | YR23 (In Production)',
		location: 'Personal Project',
		services: 'Ixana',
		year: '2024 - 2026',
		src: 'Image__3_.jpg',
		color: '#ffedd5',
		url: 'https://www.ixana.ai/products/chips/wi-r-ban',
		categories: [
			'product management',
			'project management',
			'hardware',
			'products',
		],
	},
	{
		title:
			'Dev Kits | Wi-R Body Area Network (BAN) YR23 & Wi-R Near Field Electric (NFE) XA-NFE2001',
		location: '',
		services: 'Ixana',
		year: '',
		src: 'Image__10_.jpg',
		color: '#dbeafe',
		url: '',
		categories: ['products'],
	},
	{
		title: 'NeuroAdapt | Agentic RAG Engine for Neuroscience Research',
		location: 'India',
		services: 'NeuroAdapt, IISc Bangalore',
		year: '2023-2025',
		src: 'Gemini_Generated_Image_xejg8vxejg8vxejg.png',
		color: '#dbeafe',
		url: 'https://drive.google.com/drive/u/0/folders/1B0mtA9-xkNbbo6ZUXztuHZiMmlovNtLw',
		slug: 'neuroadapt-agentic-rag-engine-for-neuroscience-research',
		categories: ['product management', 'project management', 'ai', 'products'],
	},
	{
		title: 'Wi-R Near Field Electric (NFE) | XA-NFE3001 (Sampling)',
		location: '',
		services: 'Ixana',
		year: '',
		src: 'Image__8_.jpg',
		color: '#dbeafe',
		url: '',
		categories: ['products'],
	},
	{
		title: 'Wi-R Near Field Electric (NFE) | XA-NFE2001 (In Production)',
		location: 'India',
		services: 'Ixana',
		year: '2024 - 2026',
		src: 'Image__9_.jpg',
		color: '#dbeafe',
		url: 'https://www.ixana.ai/products/dev-kits',
		categories: [
			'product management',
			'project management',
			'hardware',
			'products',
		],
	},
	{
		title: 'Data application | Accurate estimation of mineral present in soil',
		location: '',
		services: 'IIRS-ISRO, Govt. of India',
		year: '',
		src: 'Image__5_.jpg',
		color: '#dbeafe',
		url: 'https://drive.google.com/drive/u/0/folders/1tYViz5kUrsL5PZ_9DsghxZ1uno1qYQzs',
		categories: ['products'],
	},
	{
		title:
			'Quantum Circuit Simulator | Interactive 10-Qubit Delivering Real-Time 3D Bloch Visualizations',
		location: '',
		services: 'Personal',
		year: '',
		src: 'Gemini_Generated_Image_dafj5odafj5odafj.png',
		color: '#dbeafe',
		url: '',
		slug: 'quantum-circuit-simulator-interactive-10-qubit-delivering-re',
		categories: ['products'],
	},
	{
		title:
			'Procurement Orchestrator | Procurement Process Automation with M365',
		location: '',
		services: 'Ixana',
		year: '',
		src: 'Gemini_Generated_Image_ene5eiene5eiene5__1_.png',
		color: '',
		url: '',
		slug: 'procurement-orchestrator-procurement-process-automation-with',
		categories: ['products'],
	},
	{
		title: 'WishKey | Key Management System',
		location: '',
		services: 'EEGRAB',
		year: '',
		src: 'Image__1_.png',
		color: '#dbeafe',
		url: 'https://eegrab.com/wp-content/uploads/2021/brochure/Wishkey_brochure.pdf',
		categories: ['products', 'core'],
	},
	{
		title:
			'Wi-R | Video Streaming Smartglasses & Tactical Headphone to Radio Communication ',
		location: 'India',
		services: 'Ixana',
		year: '2024 - 2026',
		src: 'Gemini_Generated_Image_ef658pef658pef65.png',
		color: '#dbeafe',
		url: 'https://www.ixana.ai/products/reference-designs',
		categories: [
			'product management',
			'project management',
			'hardware',
			'products',
		],
	},
	{
		title: 'Cost-effective Smart watch ',
		location: '',
		services: 'EEGRAB',
		year: '',
		src: 'Gemini_Generated_Image_io6t60io6t60io6t.png',
		color: '#dbeafe',
		url: '',
		categories: ['core', 'products'],
	},
	{
		title: 'AI PM | Generative AI Engine for RCA Report Automation ',
		location: 'India',
		services: 'Ixana',
		year: '2025',
		src: 'Image__14_.jpg',
		color: '#ddd6fe',
		url: 'https://10xar-my.sharepoint.com/my?id=%2Fpersonal%2Fpushpal%5Fdas%5Fixana%5Fai%2FDocuments%2FAnuj%20tasks%2FProject%20Management%20Agentic%20Ai%2FRoot%20Cause%20Analyse&viewid=c9c2956f%2D87bf%2D415b%2D8b2a%2D598c7b0a1b99&csf=1&FolderCTID=0x012000D839801D2B34804CB13555A64E4ECD83',
		slug: 'ai-pm-generative-ai-engine-for-rca-report-automation',
		categories: ['product management', 'project management', 'ai', 'products'],
	},
	{
		title: 'AI PM | Generative AI Engine for Resource Allocation',
		location: 'India',
		services: 'Ixana',
		year: '2025',
		src: 'Gemini_Generated_Image_gqlkm8gqlkm8gqlk.png',
		color: '#fae8ff',
		url: 'https://10xar-my.sharepoint.com/personal/pushpal_das_ixana_ai/_layouts/15/onedrive.aspx?csf=1&web=1&e=f1nILS&CID=94ad2e4c-6d67-4625-91bf-23a89e96df3d&id=%2fpersonal%2fpushpal_das_ixana_ai%2fDocuments%2fAnuj+tasks%2fProject+Management+Agentic+Ai%2fResource+allocation&FolderCTID=0x012000D839801D2B34804CB13555A64E4ECD83&view=0',
		categories: ['product management', 'project management', 'ai', 'products'],
	},
	{
		title: 'AI PM | Generative AI Engine for Scrum Ecosystem',
		location: 'India',
		services: 'Ixana',
		year: '2025',
		src: 'Image__15_.jpg',
		color: '#fae8ff',
		url: 'https://10xar-my.sharepoint.com/personal/pushpal_das_ixana_ai/_layouts/15/onedrive.aspx?csf=1&web=1&e=f1nILS&CID=94ad2e4c-6d67-4625-91bf-23a89e96df3d&id=%2fpersonal%2fpushpal_das_ixana_ai%2fDocuments%2fAnuj+tasks%2fProject+Management+Agentic+Ai%2fResource+allocation&FolderCTID=0x012000D839801D2B34804CB13555A64E4ECD83&view=0',
		categories: ['product management', 'project management', 'ai', 'products'],
	},
	{
		title:
			'AI PM | Generative AI Engine for Real-Time Pipeline Diagnostics and Strategic Engineering ',
		location: 'India',
		services: 'Ixana',
		year: '',
		src: 'Gemini_Generated_Image_8c4hfs8c4hfs8c4h.png',
		color: '#fae8ff',
		url: '',
		slug: 'ai-pm-generative-ai-engine-for-real-time-pipeline-diagnostic',
		categories: ['product management', 'project management', 'ai', 'products'],
	},
	{
		title:
			'"Github for ClickUp" | Automation on the changes going outside PMO framework ',
		location: 'India',
		services: 'Ixana',
		year: 'Coming soon...',
		src: 'Image__16_.jpg',
		color: '#fae8ff',
		url: 'https://10xar-my.sharepoint.com/personal/pushpal_das_ixana_ai/_layouts/15/onedrive.aspx?csf=1&web=1&e=f1nILS&CID=94ad2e4c-6d67-4625-91bf-23a89e96df3d&id=%2fpersonal%2fpushpal_das_ixana_ai%2fDocuments%2fAnuj+tasks%2fProject+Management+Agentic+Ai%2fResource+allocation&FolderCTID=0x012000D839801D2B34804CB13555A64E4ECD83&view=0',
		categories: ['product management', 'project management', 'ai', 'products'],
	},
	{
		title: 'IXANA Video Library | Automated Company Video Library ',
		location: 'India',
		services: 'Ixana',
		year: 'Coming soon...',
		src: 'Gemini_Generated_Image_i9dz41i9dz41i9dz.png',
		color: '#fae8ff',
		url: 'https://10xar-my.sharepoint.com/my?csf=1&web=1&e=VPo0gz&id=%2Fpersonal%2Fpushpal%5Fdas%5Fixana%5Fai%2FDocuments%2FAnuj%20tasks%2FVideo%20lib%20automation&FolderCTID=0x012000D839801D2B34804CB13555A64E4ECD83',
		slug: 'ixana-video-library-automated-company-video-library',
		categories: ['product management', 'project management', 'ai', 'products'],
	},
	{
		title:
			'Calendar Automation | Real-Time, Bi-Directional Sync Engine with Gmail & Outlook Calendar ',
		location: 'India',
		services: 'Ixana',
		year: '2025',
		src: 'Gemini_Generated_Image_18w83818w83818w8.png',
		color: '#fae8ff',
		url: 'https://10xar-my.sharepoint.com/my?csf=1&web=1&e=3pGPGD&id=%2Fpersonal%2Fpushpal%5Fdas%5Fixana%5Fai%2FDocuments%2FAyush%20tasks%2FProject%20%2D%20Calender%20Operations&FolderCTID=0x012000D839801D2B34804CB13555A64E4ECD83',
		slug: 'calendar-automation-real-time-bi-directional-sync-engine-wit',
		categories: ['product management', 'project management', 'ai', 'products'],
	},
	{
		title: 'AI Salary Generator | In progress.. ',
		location: 'India',
		services: 'Ixana',
		year: '2024-coming soon...',
		src: 'Image__17_.jpg',
		color: '#fee2e2',
		url: 'https://www.ixana.ai/products',
		categories: [
			'product management',
			'project management',
			'hardware',
			'products',
		],
	},
	{
		title: 'AI PRD | Multi Agent, Multi LLM Shared Memory Generative System',
		location: '',
		services: 'Ixana',
		year: '',
		src: 'Gemini_Generated_Image_6dagw16dagw16dag.png',
		color: '#dbeafe',
		url: '',
		slug: 'ai-prd-multi-agent-multi-llm-shared-memory-generative-system',
		categories: ['product management', 'project management', 'ai', 'products'],
	},
	{
		title:
			'AI Lawyer | Multi Agent, Multi LLM Shared Memory Generative System ',
		location: 'Ixana',
		services: 'Ixana',
		year: '',
		src: 'Gemini_Generated_Image_1i9ozk1i9ozk1i9o.png',
		color: '#dbeafe',
		url: '',
		slug: 'ai-lawyer-multi-agent-multi-llm-shared-memory-generative-sys',
		categories: ['products'],
	},
	{
		title: "AI PM | Customized Multi View for PM's",
		location: 'Ixana',
		services: 'Ixana',
		year: '',
		src: 'Gemini_Generated_Image_h59yuyh59yuyh59y.png',
		color: '#dbeafe',
		url: '',
		slug: 'ai-pm-customized-multi-view-for-pms',
		categories: ['products'],
	},
	{
		title:
			'Ixana\'s "Fireflies" | Generative AI engine for taking meeting notes and answering question',
		location: '',
		services: 'Ixana',
		year: '',
		src: 'Image__18_.jpg',
		color: '#dbeafe',
		url: '',
		categories: ['products'],
	},
	{
		title: 'Patent tracker | Generative AI Engine for Data Extraction ',
		location: '',
		services: 'Ixana',
		year: '',
		src: 'Image__19_.jpg',
		color: '#dbeafe',
		url: '',
		slug: 'patent-tracker-generative-ai-engine-for-data-extraction',
		categories: ['products'],
	},
	{
		title:
			'PM TOOL Document Tracker | Data extraction, easy visibility for doc users',
		location: '',
		services: 'Ixana',
		year: '',
		src: 'Image__21_.jpg',
		color: '#dbeafe',
		url: '',
		categories: ['products'],
	},
	{
		title: 'Condenser microphone ',
		location: '',
		services: 'EEGRAB',
		year: '',
		src: 'IMG_0404.PNG',
		color: '#dbeafe',
		url: '',
		categories: ['core work', 'products'],
	},
	{
		title:
			'Failure Analysis (PWA-PCB, 5x) main ones (resonant converter, power supply and post regulator.',
		location: '',
		services: 'Failure Analysis | SLB',
		year: '',
		src: '82674a56-a5c4-4667-90ed-0f1a3046776b.jpg',
		color: '#dbeafe',
		url: '',
		categories: ['core'],
	},
	{
		title:
			'Sensor Signal generator (97.2% eff & 40+ global lab implementation)  ',
		location: '',
		services: 'SLB',
		year: '',
		src: 'IMG_3638.HEIC.jpg',
		color: '#dbeafe',
		url: '',
		categories: ['core', 'products'],
	},
	{
		title: 'Ornithopter for Surveillance',
		location: '',
		services: 'SRM UAV ',
		year: '',
		src: 'Image__20_.jpg',
		color: '#dbeafe',
		url: 'https://drive.google.com/drive/u/0/folders/1v5Woj-5XMv07hJ-PMSneMdFDRAmq5nQs',
		categories: ['products'],
	},
	{
		title: 'Carbon Positive e-car (concept) ',
		location: '',
		services: 'Ricky Kids',
		year: '',
		src: 'Screenshot 2026-07-06 152543.png',
		color: '#dbeafe',
		url: 'https://drive.google.com/drive/u/0/folders/1UFIFRPfj_T6rlZwSt5imc6q1aBv4Wm-e',
		categories: ['products'],
	},
	{
		title: 'UAV-Aided Weather Radar Calibration',
		location: '',
		services: 'NIT Tiruchirapalli  & SRM University ',
		year: '',
		src: 'Screenshot 2026-07-06 155348.png',
		color: '#dbeafe',
		url: 'https://drive.google.com/drive/u/0/folders/1rDmPZo8yHV0OFcVruwNqiDJHfU8SeUED',
		categories: ['products'],
	},
	{
		title: 'Non contact based COVID patient monitoring system ',
		location: '',
		services: 'Ricky Kids',
		year: '',
		src: 'Screenshot_2026-07-06_160217.png',
		color: '#dbeafe',
		url: 'https://drive.google.com/drive/u/0/folders/198wp9t5QOvHIX3rZbVzw9IehQD7HToc5',
		categories: ['products'],
	},
	{
		title: 'Triple riding avoidance ',
		location: '',
		services: 'Ricky Kids ',
		year: '',
		src: 'Screenshot_2026-07-06_161350.png',
		color: '#dbeafe',
		url: 'https://drive.google.com/drive/u/0/folders/11Bx3DJGQsSQoCqb6T8OjxarnfehbDbIk',
		categories: ['products'],
	},
	{
		title: 'Toys for autistic kids',
		location: '',
		services: 'Ricky Kids ',
		year: '',
		src: 'Screenshot_2026-07-06_161758.png',
		color: '#dbeafe',
		url: 'https://drive.google.com/drive/u/0/folders/14Cx5kE8ckME3dmSky9t9Eryn2wERSMcC',
		categories: ['products'],
	},
	{
		title: ' Sludge-Traversing ROV ',
		location: '',
		services: 'Ricky Kids ',
		year: '',
		src: 'Screenshot_2026-07-06_161943.png',
		color: '#dbeafe',
		url: 'https://drive.google.com/drive/u/0/folders/1xcXPJ-9sD7xQWy-5TUwYhE5nlHJs1pqI',
		categories: ['products'],
	},
	{
		title: 'Testing of AD 8232 with NI instruments & LABVIEW',
		location: '',
		services: 'Ricky Kids ',
		year: '',
		src: 'Screenshot_2026-07-06_162431.png',
		color: '#dbeafe',
		url: 'https://docs.google.com/document/d/1qxaBf6EwlEZ8k95nHYRiDybBt1BD-BExT1NqvUNzVHg/edit?tab=t.0',
		categories: ['core'],
	},
	{
		title: 'Obstacle Avoidance Robot using Ultrasonic Sensor',
		location: '',
		services: 'Vyorius ',
		year: '',
		src: 'Gemini_Generated_Image_2gvvx02gvvx02gvv.png',
		color: '#dbeafe',
		url: 'https://docs.google.com/document/d/1NrzaG24wBFJQj_O4VZSROqNsbwcyjNw5/edit',
		categories: ['core'],
	},
	{
		title: 'FSM Designs: Mealy & Moore Machines and Up Down Counter',
		location: '',
		services: 'Vyorius ',
		year: '',
		src: 'Screenshot_2026-07-06_174001.png',
		color: '#dbeafe',
		url: 'https://docs.google.com/document/d/1DM0qEisVqD07y9ZpJcE0AUy-JdPhbibj/edit',
		categories: ['core'],
	},
	{
		title:
			'Circuits written in Verilog/VHDL, simulated and implemented on the FPGA',
		location: '',
		services: 'Vyorius ',
		year: '',
		src: 'Screenshot_2026-07-06_174606.png',
		color: '#dbeafe',
		url: 'https://docs.google.com/document/d/10xzoWqieysAcCH_9pJP21YPoNWrjT9b8/edit',
		categories: ['core'],
	},
	{
		title: 'UART communication to print a single character ',
		location: '',
		services: 'Vyorius ',
		year: '',
		src: 'Screenshot_2026-07-06_182741.png',
		color: '#dbeafe',
		url: 'https://docs.google.com/document/d/1nay8EmttD2w6yuVMpCoJUHsu2UNGEPJL/edit',
		categories: ['core'],
	},
	{
		title: '16-Bit RISC Processor',
		location: '',
		services: 'Vyorius ',
		year: '',
		src: 'Screenshot_2026-07-06_183032.png',
		color: '#dbeafe',
		url: 'https://docs.google.com/document/d/1zCY0TZJ2UW7helKCK5UhQJ9bhLdnA0_H/edit',
		categories: ['core'],
	},
	{
		title: 'IoT based on smart Agriculture System',
		location: '',
		services: 'Vyorius ',
		year: '',
		src: 'Screenshot_2026-07-06_183307.png',
		color: '#dbeafe',
		url: 'https://docs.google.com/document/d/1fnXjTPe5c2aOFD0W8ZlrmUC8LkFHQJ_f/edit',
		categories: ['core'],
	},
	{
		title: 'RGB Pattern',
		location: '',
		services: 'Vyorius ',
		year: '',
		src: 'Screenshot_2026-07-06_183600.png',
		color: '#dbeafe',
		url: 'https://docs.google.com/document/d/1FE9loSRYIwWPt6Q2_5IB_jqJ_VY7rI9-/edit',
		categories: ['core'],
	},
	{
		title: 'World map covid-19 dashboard',
		location: '',
		services: 'Vyorius ',
		year: '',
		src: 'Screenshot_2026-07-06_183826.png',
		color: '#dbeafe',
		url: 'https://docs.google.com/document/d/1aQkLDDcX5mvwUBzbkiDYodOWn6N6M5cM/edit',
		categories: ['core'],
	},
	{
		title: 'Voice Control Home Automation ',
		location: '',
		services: 'Vyorius ',
		year: '',
		src: 'Screenshot_2026-07-06_184124.png',
		color: '#dbeafe',
		url: 'https://docs.google.com/document/d/1hOuPP4wIkxm0z535LyFsi8bingr9xNQB/edit',
		categories: ['core'],
	},
	{
		title: 'Home automation with Automatic Room Temperature Controller',
		location: '',
		services: 'MSME Technology Development Centre, Govt. of India',
		year: '',
		src: 'Screenshot_2026-07-06_192816.png',
		color: '#dbeafe',
		url: 'https://docs.google.com/presentation/d/1eF7KPmWUSfztWLRwHLzZ_9DMAFwMe8KW/edit?slide=id.p11#slide=id.p11',
		categories: ['core'],
	},
	{
		title: '3-bit Binary to Grey Code Converter using Low Voltage XOR Gates',
		location: '',
		services: 'Hackathon | IIT Hyderabad',
		year: '',
		src: 'Screenshot_2026-07-06_185716.png',
		color: '#dbeafe',
		url: 'https://drive.google.com/drive/u/0/folders/1nP-K9XsWjmGpQfBTMgybo-LYUvGGbYTO',
		categories: ['core'],
	},
	{
		title: 'FIRST ROBOT',
		location: '',
		services: 'Intern | MSME Technology Development Centre, Govt. of India',
		year: '',
		src: 'Screenshot_2026-07-06_190925.png',
		color: '#dbeafe',
		url: '',
		categories: ['core'],
	},
	{
		title: 'LCD',
		location: '',
		services: 'Intern | MSME Technology Development Centre, Govt. of India',
		year: '',
		src: 'Screenshot_2026-07-06_191645.png',
		color: '#dbeafe',
		url: 'https://drive.google.com/drive/u/0/search?q=MSME',
		categories: ['core'],
	},
	{
		title: 'Timer',
		location: '',
		services: 'Intern | MSME Technology Development Centre, Govt. of India',
		year: '',
		src: 'Screenshot_2026-07-06_191902.png',
		color: '#dbeafe',
		url: 'https://drive.google.com/drive/u/0/search?q=MSME',
		categories: ['core'],
	},
	{
		title: 'First signal (PWM)',
		location: '',
		services: 'Intern | MSME Technology Development Centre, Govt. of India',
		year: '',
		src: 'Screenshot_2026-07-06_192015.png',
		color: '#dbeafe',
		url: 'https://drive.google.com/drive/u/0/search?q=MSME',
		categories: ['core'],
	},
	{
		title: 'ENVI-City | Vision of a sustainable smart city of the future ',
		location: '',
		services: 'Ricky Kids',
		year: '',
		src: 'Screenshot_2026-07-06_193247.png',
		color: '#dbeafe',
		url: 'https://drive.google.com/drive/u/0/folders/1XhqFiIQJZtQN9ZVzuRBbMfDo5szeg9W0',
		categories: ['products'],
	},
];

export const filters = [
	{ key: 'all', label: 'All' },
	{ key: 'products', label: 'Product' },
	{ key: 'core', label: 'Core' },
	{ key: 'others', label: 'Others' },
] as const;

export type FilterKey = (typeof filters)[number]['key'];
