import type { CertificationItem } from './types';

export const certificationItems: CertificationItem[] = [
	{
		title: 'Six Sigma Black Belt certification',
		location: 'Cloud Native Computing Foundation',
		services: 'Board of Regents of University System of Georgia',
		year: '2023',
		src: 'Screenshot_2026-07-08_135955.png',
		color: '#fae8ff',
		url: 'https://drive.google.com/drive/u/0/folders/1-TjIeN--GT5WFDnu_pqU6xD5QCLOo6yx',
		categories: ['devops', 'containers', 'management'],
	},
	{
		title: 'PMI Agile Certified Practitioner (PMI-ACP)',
		location: 'Null',
		services: 'Packt',
		year: '2023',
		src: 'Screenshot_2026-07-08_135720.png',
		color: '#dbeafe',
		url: 'https://drive.google.com/drive/u/0/folders/1-TjIeN--GT5WFDnu_pqU6xD5QCLOo6yx',
		categories: ['cloud', 'architecture', 'management'],
	},
	{
		title: 'Product Manager | AI ',
		location: '',
		services: 'IBM ',
		year: '',
		src: 'Gemini_Generated_Image_anrtg0anrtg0anrt.png',
		color: '#dbeafe',
		url: '',
		categories: ['Management', 'management'],
	},
	{
		title: 'PMP | AI',
		location: '',
		services: 'Google',
		year: '',
		src: 'Gemini_Generated_Image_anrtg0anrtg0anrt.png',
		color: '#dbeafe',
		url: '',
		categories: ['management'],
	},
	{
		title: 'Global Student Trainee',
		location: '',
		services: 'Schneider Electric ',
		year: '',
		src: 'Screenshot_2026-07-08_135146.png',
		color: '',
		url: '',
		categories: ['development', 'frontend', 'management'],
	},
	{
		title: 'Generative AI Leader',
		location: '',
		services: 'Google',
		year: '',
		src: 'Screenshot_2026-07-12_144203.png',
		color: '#dbeafe',
		url: '',
		categories: ['skills'],
	},
	{
		title: 'Microsoft 365 | Generative AI',
		location: '',
		services: 'Microsoft ',
		year: '',
		src: 'Screenshot_2026-07-12_145319.png',
		color: '#dbeafe',
		url: '',
		categories: ['skills'],
	},
	{
		title: 'AI from the data center to the edge an optimized path',
		location: '',
		services: 'Intel\u00AE AI Academy',
		year: '',
		src: 'Screenshot_2026-07-08_140748.png',
		color: '#dbeafe',
		url: '',
		categories: ['skills'],
	},
	{
		title:
			'AWS Cloud Practitioner Essentials | Building modern python application on Amazon Web Service',
		location: '',
		services: 'AWS',
		year: '',
		src: 'Screenshot_2026-07-09_113850.png',
		color: '#dbeafe',
		url: '',
		categories: ['skills'],
	},
	{
		title:
			'Build a Face Recognition Application using Python | AI-For-India Event ',
		location: '',
		services: 'GUVI',
		year: '',
		src: 'Screenshot_2026-07-12_125729.png',
		color: '#dbeafe',
		url: '',
		categories: ['skills'],
	},
	{
		title: 'Introduction to iot',
		location: '',
		services: 'Cisco Networking Academy',
		year: '',
		src: 'Screenshot_2026-07-08_140354.png',
		color: '#dbeafe',
		url: '',
		categories: ['skills'],
	},
	{
		title: 'Geospatial Technologies for Archeological Studies ',
		location: '',
		services: 'Indian Institute of Remote Sensing, Dehradun, ISRO',
		year: '',
		src: 'Screenshot_2026-07-08_135602.png',
		color: '#ddd6fe',
		url: '',
		categories: ['development', 'backend', 'skills'],
	},
	{
		title: 'Professional Development Program on Total Digital Transformation',
		location: '',
		services: 'MSME Technology Development Centre, Govt. of India',
		year: '',
		src: 'Screenshot_2026-07-08_135351.png',
		color: '#dbeafe',
		url: 'https://drive.google.com/drive/u/0/folders/1-TjIeN--GT5WFDnu_pqU6xD5QCLOo6yx',
		categories: ['frontend', 'development', 'management'],
	},
	{
		title: 'Agriculture automation, CPS -Advance Skill Training workshop',
		location: '',
		services: '',
		year: '',
		src: 'Screenshot_2026-07-08_140133.png',
		color: '#dbeafe',
		url: 'IIT Ropar',
		categories: ['skills'],
	},
	{
		title: 'Internship Training on IoT',
		location: '',
		services: ' MSME Technology Development Centre, Govt. of India',
		year: '',
		src: 'Screenshot_2026-07-09_113437.png',
		color: '#dbeafe',
		url: '',
		categories: ['skills'],
	},
	{
		title:
			'Internship Program on Functional Verification using System Verilog ',
		location: '',
		services: 'CoreEL Technologies ',
		year: '',
		src: 'Screenshot_2026-07-09_113557.png',
		color: '#dbeafe',
		url: '',
		categories: ['skills'],
	},
	{
		title: 'Internship Training on Microcontroller programming',
		location: '',
		services: ' MSME Technology Development Centre, Govt. of India',
		year: '',
		src: 'Screenshot_2026-07-09_113959.png',
		color: '#dbeafe',
		url: '',
		categories: ['skills'],
	},
	{
		title: 'Internship Training on Computer Hardware & Networking',
		location: '',
		services: '  MSME Technology Development Centre, Govt. of India',
		year: '',
		src: 'Screenshot_2026-07-09_114351.png',
		color: '#dbeafe',
		url: '',
		categories: ['skills'],
	},
	{
		title: 'Internship Program on VLSI',
		location: '',
		services: 'Vyorius',
		year: '',
		src: 'Screenshot_2026-07-09_114605.png',
		color: '#dbeafe',
		url: '',
		categories: ['skills'],
	},
	{
		title: 'Internship Program on IoT ',
		location: '',
		services: 'Vyorius',
		year: '',
		src: 'Screenshot_2026-07-09_114813.png',
		color: '#dbeafe',
		url: '',
		categories: ['skills'],
	},
	{
		title: 'Student Ambassador  ',
		location: '',
		services: 'IIT Bombay',
		year: '',
		src: 'Screenshot_2026-07-09_115606.png',
		color: '#dbeafe',
		url: '',
		categories: ['management'],
	},
	{
		title: 'Training course on introduction of Hydraulics Pneumatics and PLCs ',
		location: '',
		services: 'SRM University ',
		year: '',
		src: 'Screenshot_2026-07-12_125121.png',
		color: '#dbeafe',
		url: '',
		categories: ['skills'],
	},
	{
		title: 'AI',
		location: '',
		services: 'My Captain',
		year: '',
		src: 'Screenshot_2026-05-11_172942.png',
		color: '#dbeafe',
		url: '',
		categories: ['skills'],
	},
	{
		title: 'Introduction to Cybersecurity course',
		location: '',
		services: 'Cisco Networking Academy\u00AE ',
		year: '',
		src: 'Screenshot_2026-07-12_125345.png',
		color: '#dbeafe',
		url: '',
		categories: ['skills'],
	},
	{
		title: '3rd PLACE WINNER | NATO INNOVATION CHALLENGE',
		location: '',
		services: 'Ixana',
		year: '',
		src: 'Screenshot_2026-07-17_154453.png',
		color: '#dbeafe',
		url: 'https://www.act.nato.int/article/17th-innovation-challenge-concludes/',
		categories: ['achievements'],
	},
	{
		title: 'EE Times Silicon 100 (2x) ',
		location: '',
		services: 'Ixana',
		year: '',
		src: '1752875231267.jpg',
		color: '#dbeafe',
		url: 'https://drive.google.com/drive/u/0/folders/1-TjIeN--GT5WFDnu_pqU6xD5QCLOo6yx',
		categories: ['achievements'],
	},
	{
		title: 'IoT Breakthrough Award, IoT Wearables Innovation of the Year',
		location: '',
		services: 'Ixana',
		year: '',
		src: 'Screenshot_2026-07-17_152136.png',
		color: '#dbeafe',
		url: 'https://iotbreakthrough.com/2024-winners/',
		categories: ['achievements'],
	},
	{
		title: 'CES Innovation Award ',
		location: '',
		services: 'Ixana',
		year: '',
		src: 'Screenshot_2026-07-17_184538.png',
		color: '#dbeafe',
		url: 'https://www.ces.tech/ces-innovation-awards/2024/ixanas-wi-r-100x-lower-power-4mbps-chip-for-wearables/',
		categories: ['achievements'],
	},
	{
		title:
			'Talk | Industry 4.0 and connecting the dots with electronic sector ',
		location: '',
		services: 'IISc - EnTIISc',
		year: '',
		src: 'Screenshot_2026-07-12_135049.png',
		color: '#dbeafe',
		url: '',
		categories: ['achievements'],
	},
	{
		title: 'Silver medalist | ECE 2023',
		location: '',
		services: 'SRM University',
		year: '',
		src: 'Screenshot_2026-07-17_115248.png',
		color: '#dbeafe',
		url: '',
		categories: ['achievements'],
	},
	{
		title: '1st Prize |  Toys for Autistic kids',
		location: '',
		services:
			'Indo Universal Collaboration for Engineering Education ( IUCEE ) ',
		year: '',
		src: 'Screenshot_2026-07-12_135605.png',
		color: '#dbeafe',
		url: '',
		categories: ['achievements'],
	},
	{
		title: 'Silver Medal | Research Day',
		location: '',
		services: 'SRM University ',
		year: '',
		src: 'Screenshot_2026-07-12_140558.png',
		color: '#dbeafe',
		url: '',
		categories: ['achievements'],
	},
	{
		title: 'Winner | Cloud based Analog IC Design Hackathon ',
		location: '',
		services: 'IIT Hyderabad',
		year: '',
		src: 'Screenshot_2026-07-12_140421.png',
		color: '#dbeafe',
		url: '',
		categories: ['achievements'],
	},
	{
		title:
			'Sachetna | Talk series for disabilities, accessibility, advocacy and awareness by parents professionals or professionals ',
		location: '',
		services: 'Sunshine Autism Care society ',
		year: '',
		src: 'Screenshot_2026-07-12_141345.png',
		color: '#dbeafe',
		url: '',
		categories: ['achievements'],
	},
	{
		title:
			'Attempt for most users to take an online computer programming lesson in 24 hours',
		location: '',
		services: 'Guinness world records',
		year: '',
		src: 'Screenshot_2026-07-12_125530.png',
		color: '#dbeafe',
		url: '',
		categories: ['achievements'],
	},
	{
		title: 'Python',
		location: '',
		services: 'Google',
		year: '',
		src: 'Screenshot_2026-07-12_130148.png',
		color: '#dbeafe',
		url: '',
		categories: ['skills'],
	},
	{
		title: 'Appreciation | Toys for Autistic kids',
		location: '',
		services:
			'Indo Universal Collaboration for Engineering Education ( IUCEE )',
		year: '',
		src: 'Screenshot_2026-07-12_140048.png',
		color: '#dbeafe',
		url: '',
		categories: ['achievements'],
	},
	{
		title: '2nd runner up | THINKTECH2K21 ',
		location: '',
		services: 'Don bosco college of engineering',
		year: '',
		src: 'Screenshot_2026-07-12_142646.png',
		color: '#dbeafe',
		url: '',
		categories: ['achievements'],
	},
	{
		title: 'Idea Generation challenge | Sanrachna',
		location: '',
		services: 'BHEL',
		year: '',
		src: 'Screenshot_2026-07-12_141154.png',
		color: '#dbeafe',
		url: '',
		categories: ['achievements'],
	},
	{
		title: 'SRM PROJECT EXPO’21',
		location: '',
		services: 'SRM University ',
		year: '',
		src: 'Screenshot_2026-07-12_142422.png',
		color: '#dbeafe',
		url: '',
		categories: ['achievements'],
	},
	{
		title: '2nd runner up | Milaap',
		location: '',
		services: 'Milaap 2018',
		year: '',
		src: 'Screenshot_2026-07-12_133513.png',
		color: '#dbeafe',
		url: '',
		categories: ['achievements'],
	},
	{
		title: '2nd runner up | Literaria ',
		location: '',
		services: 'Xavotsav ',
		year: '',
		src: 'Screenshot_2026-07-12_132817.png',
		color: '#dbeafe',
		url: '',
		categories: ['achievements'],
	},
	{
		title: 'INFRAME | Photography workshop',
		location: '',
		services: 'SRM University ',
		year: '',
		src: 'Screenshot_2026-07-12_130512.png',
		color: '#dbeafe',
		url: '',
		categories: ['achievements'],
	},
	{
		title:
			'YouthRep/Marketing | Business Development, marketing and sales, community building by creating impact in my college',
		location: '',
		services: 'MyCaptain | SRM University ',
		year: '',
		src: 'Screenshot_2026-07-12_130735.png',
		color: '#dbeafe',
		url: '',
		categories: ['skills'],
	},
	{
		title: 'Christmas photography contest ',
		location: '',
		services: 'Kolkata sutra',
		year: '',
		src: 'Screenshot_2026-07-12_132544.png',
		color: '#dbeafe',
		url: '',
		categories: ['achievements'],
	},
	{
		title: 'C Programming Course ',
		location: '',
		services: 'My Captain ',
		year: '',
		src: 'Screenshot_2026-07-12_133943.png',
		color: '#dbeafe',
		url: '',
		categories: ['skills'],
	},
	{
		title: 'Android App Development ',
		location: '',
		services: 'My Captain',
		year: '',
		src: 'Screenshot_2026-07-12_134242.png',
		color: '#dbeafe',
		url: '',
		categories: ['skills'],
	},
	{
		title: 'Graphic Design',
		location: '',
		services: 'My Captain',
		year: '',
		src: 'Screenshot_2026-07-12_134357.png',
		color: '#dbeafe',
		url: '',
		categories: ['skills'],
	},
	{
		title: 'Web Development',
		location: '',
		services: 'My Captain',
		year: '',
		src: 'Screenshot_2026-07-12_134526.png',
		color: '#dbeafe',
		url: '',
		categories: ['skills'],
	},
	{
		title: 'Python',
		location: '',
		services: 'My Captain',
		year: '',
		src: 'Screenshot_2026-07-12_134638.png',
		color: '#dbeafe',
		url: '',
		categories: ['skills'],
	},
	{
		title: 'Data collection workshop | R&D project ',
		location: '',
		services: 'Samsung Research Institute',
		year: '',
		src: 'Screenshot_2026-07-12_140803.png',
		color: '#dbeafe',
		url: '',
		categories: ['skills'],
	},
	{
		title:
			'Research Paper | First international conference on technologies for smart green connected society 2021',
		location: '',
		services: 'SPAST',
		year: '',
		src: 'Screenshot_2026-07-12_142257.png',
		color: '#dbeafe',
		url: '',
		categories: ['skills'],
	},
	{
		title:
			'Training Program on “Incident Response System: Basic & Intermediate” ',
		location: '',
		services:
			'National Institute of Disaster Management, Ministry of Home Affairs, Govt. of India ',
		year: '',
		src: 'Screenshot_2026-07-12_142914.png',
		color: '#dbeafe',
		url: '',
		categories: ['skills'],
	},
	{
		title:
			'Consumer outreach program | Discussion of network usage and 5G with its efficiency',
		location: '',
		services: 'TRAI- Telecom Regulatory Authority of India, Govt. of India',
		year: '',
		src: 'Screenshot_2026-07-12_143106.png',
		color: '#dbeafe',
		url: '',
		categories: ['skills'],
	},
	{
		title: 'Webinar | Hybrid electric technology',
		location: '',
		services: 'Toyota Kirloskar Motor pvt.Ltd',
		year: '',
		src: 'Screenshot_2026-07-12_143455.png',
		color: '#dbeafe',
		url: '',
		categories: ['skills'],
	},
	{
		title: 'Pro MFG Plant Maintenance and Asset Management Summit  2021',
		location: '',
		services: 'Pro MFG Media',
		year: '',
		src: 'Screenshot_2026-07-12_143616.png',
		color: '#dbeafe',
		url: '',
		categories: ['skills'],
	},
];

export const filters = [
	{ key: 'all', label: 'All' },
	{ key: 'management', label: 'Management' },
	{ key: 'skills', label: 'Skills' },
	{ key: 'achievements', label: 'Achievements' },
] as const;

export type FilterKey = (typeof filters)[number]['key'];
