import type { CertificationItem } from './types';

/**
 * Certificate artwork lives under /static/images/certificates/.
 *
 * `docs/…` files are the certificates themselves — PDFs rasterised at print
 * resolution and images re-encoded to one ceiling, trimmed of the dead paper
 * margin a scan leaves behind. The bare `Screenshot_…` files are the older
 * screen grabs, kept only where no original document exists. `docs/ixana/…`
 * are title cards, not documents: those recognitions have no certificate to
 * scan, and a card is the honest stand-in for one.
 *
 * Every record carries a `slug` and opens as a page of its own at
 * /certifications/<slug>. `documents` is set only where a record holds more
 * than one certificate; otherwise the page composes a single plate out of
 * `src`, `title` and `url`.
 *
 * `summary` is the brief on that page. It is written against the certificate
 * itself — what the programme was, who ran it, what it attests to — and never
 * beyond what the document supports.
 */
export const certificationItems: CertificationItem[] = [
	{
		title: 'Six Sigma Black Belt certification',
		location: 'Cloud Native Computing Foundation',
		services: 'Board of Regents of University System of Georgia',
		year: '2023',
		src: 'docs/six-sigma-black-belt/specialization.jpg',
		color: '#fae8ff',
		url: 'https://coursera.org/verify/specialization/RQC75LWY4XJ2',
		categories: ['devops', 'containers', 'management'],
		slug: 'six-sigma-black-belt',
		summary:
			'A nine-certificate specialisation covering the full DMAIC process — define, measure, analyse, improve and control — alongside organisational planning, team management and Design for Six Sigma. Taught by Kennesaw State University and assessed through a peer-reviewed capstone carried end to end rather than through quizzes alone.',
		documents: [
			{
				src: 'docs/six-sigma-black-belt/specialization.jpg',
				title: 'Six Sigma Black Belt',
				kind: 'Specialization',
				date: 'Oct 30, 2023',
				url: 'https://coursera.org/verify/specialization/RQC75LWY4XJ2',
			},
			{
				src: 'docs/six-sigma-black-belt/organization-planning.jpg',
				title: 'Organization Planning and Development for the 6σ Black Belt',
				kind: 'Course',
				date: 'Oct 14, 2023',
				url: 'https://coursera.org/verify/MPMYG89U5RC2',
			},
			{
				src: 'docs/six-sigma-black-belt/team-management.jpg',
				title: 'Team Management for the 6σ Black Belt',
				kind: 'Course',
				date: 'Oct 14, 2023',
				url: 'https://coursera.org/verify/YXRW6V8JQN3W',
			},
			{
				src: 'docs/six-sigma-black-belt/define-phase.jpg',
				title: 'The Define Phase for the 6σ Black Belt',
				kind: 'Course',
				date: 'Oct 15, 2023',
				url: 'https://coursera.org/verify/9R2TUSGABYWW',
			},
			{
				src: 'docs/six-sigma-black-belt/measure-phase.jpg',
				title: 'The Measure Phase for the 6σ Black Belt',
				kind: 'Course',
				date: 'Oct 18, 2023',
				url: 'https://coursera.org/verify/EG6RESTNJGUC',
			},
			{
				src: 'docs/six-sigma-black-belt/analyze-phase.jpg',
				title: 'The Analyze Phase for the 6σ Black Belt',
				kind: 'Course',
				date: 'Oct 19, 2023',
				url: 'https://coursera.org/verify/HA7DH6ZVSQSV',
			},
			{
				src: 'docs/six-sigma-black-belt/improve-phase.jpg',
				title: 'The Improve Phase for the 6σ Black Belt',
				kind: 'Course',
				date: 'Oct 18, 2023',
				url: 'https://coursera.org/verify/QZPGV3MJMJWU',
			},
			{
				src: 'docs/six-sigma-black-belt/control-phase.jpg',
				title: 'The Control Phase for the 6σ Black Belt',
				kind: 'Course',
				date: 'Oct 21, 2023',
				url: 'https://coursera.org/verify/RAUVSA44WVX5',
			},
			{
				src: 'docs/six-sigma-black-belt/dfss.jpg',
				title: 'DFSS for the 6σ Black Belt',
				kind: 'Course',
				date: 'Oct 30, 2023',
				url: 'https://coursera.org/verify/VAPS9J87V2AQ',
			},
		],
	},
	{
		title: 'PMI Agile Certified Practitioner (PMI-ACP)',
		location: 'Null',
		services: 'Packt',
		year: '2023',
		src: 'docs/pmi-acp/specialization.jpg',
		color: '#dbeafe',
		url: 'https://coursera.org/verify/specialization/HR24814MFFFF',
		categories: ['cloud', 'architecture', 'management'],
		slug: 'pmi-acp',
		summary:
			'A four-part programme covering Agile principles and the frameworks built on them — Scrum, Kanban and Lean — through to stakeholder management, adaptive planning and continuous improvement. The syllabus maps to the PMI-ACP exam, and each course is assessed on its own.',
		documents: [
			{
				src: 'docs/pmi-acp/specialization.jpg',
				title: 'PMI Agile Certified Practitioner (PMI-ACP)',
				kind: 'Specialization',
				date: 'Feb 23, 2026',
				url: 'https://coursera.org/verify/specialization/HR24814MFFFF',
			},
			{
				src: 'docs/pmi-acp/foundations.jpg',
				title: 'Foundations of Agile and Exam Preparation',
				kind: 'Course',
				date: 'Feb 11, 2026',
				url: 'https://coursera.org/verify/73APBBO88RLQ',
			},
			{
				src: 'docs/pmi-acp/value-stakeholders.jpg',
				title: 'Delivering Value and Managing Stakeholders in Agile',
				kind: 'Course',
				date: 'Feb 11, 2026',
				url: 'https://coursera.org/verify/XFUK9AR8CG03',
			},
			{
				src: 'docs/pmi-acp/advanced-practices.jpg',
				title: 'Advanced Agile Practices and Continuous Improvement',
				kind: 'Course',
				date: 'Feb 23, 2026',
				url: 'https://coursera.org/verify/KBPGDH53FF0S',
			},
		],
	},
	{
		title: 'Product Manager | AI ',
		location: '',
		services: 'IBM ',
		year: '',
		src: 'Image__4_.jpg',
		color: '#dbeafe',
		url: '',
		categories: ['Management', 'management'],
		slug: 'product-manager-ai-ibm',
		titleCard: true,
		summary:
			"IBM's AI product management track, still in progress. The plate stands in until the certificate is issued; nothing is claimed here that the programme has not yet awarded.",
	},
	{
		title: 'PMP | AI',
		location: '',
		services: 'Google',
		year: '',
		src: 'docs/pmp-ai/professional-certificate.jpg',
		color: '#dbeafe',
		url: 'https://coursera.org/verify/professional-cert/VKAXX7XP10AE',
		categories: ['management'],
		slug: 'pmp-ai',
		summary:
			"Google's Project Management Professional Certificate, taken as seven courses and the certificate that closes them. It runs the full project lifecycle — initiation, planning, execution and close — across both traditional and Agile delivery, and finishes with an applied capstone.",
		documents: [
			{
				src: 'docs/pmp-ai/professional-certificate.jpg',
				title: 'Google Project Management',
				kind: 'Professional Certificate',
				date: 'Aug 4, 2026',
				url: 'https://coursera.org/verify/professional-cert/VKAXX7XP10AE',
			},
			{
				src: 'docs/pmp-ai/foundations.jpg',
				title: 'Foundations of Project Management',
				kind: 'Course',
				date: 'Feb 11, 2026',
				url: 'https://coursera.org/verify/B56VVN5N93ME',
			},
			{
				src: 'docs/pmp-ai/initiation.jpg',
				title: 'Project Initiation: Starting a Successful Project',
				kind: 'Course',
				date: 'Mar 5, 2026',
				url: 'https://coursera.org/verify/VYSS2B7AV4X9',
			},
			{
				src: 'docs/pmp-ai/planning.jpg',
				title: 'Project Planning: Putting It All Together',
				kind: 'Course',
				date: 'Aug 4, 2026',
				url: 'https://coursera.org/verify/3PUMDR7C6LPM',
			},
			{
				src: 'docs/pmp-ai/execution.jpg',
				title: 'Project Execution: Running the Project',
				kind: 'Course',
				date: 'Aug 4, 2026',
				url: 'https://coursera.org/verify/H89HCWEQODCM',
			},
			{
				src: 'docs/pmp-ai/agile.jpg',
				title: 'Agile Project Management',
				kind: 'Course',
				date: 'Aug 4, 2026',
				url: 'https://coursera.org/verify/340I8YNSNKV4',
			},
			{
				src: 'docs/pmp-ai/capstone.jpg',
				title: 'Capstone: Applying Project Management in the Real World',
				kind: 'Course',
				date: 'Aug 4, 2026',
				url: 'https://coursera.org/verify/3QWKHS63LKDN',
			},
			{
				src: 'docs/pmp-ai/job-search-ai.jpg',
				title: 'Accelerate Your Job Search with AI',
				kind: 'Course',
				date: 'Aug 4, 2026',
				url: 'https://coursera.org/verify/DDFE48DGKGTG',
			},
		],
	},
	{
		title: 'Global Student Trainee',
		location: '',
		services: 'Schneider Electric ',
		year: '2022',
		src: 'docs/schneider-global-student-experience.jpg',
		color: '',
		url: '',
		categories: ['development', 'frontend', 'management'],
		slug: 'schneider-global-student-trainee',
		summary:
			"Schneider Electric's Global Student Experience, run June to August 2022. The programme draws its courses from the company's own employee learning library, so the material is the energy and automation industry as Schneider teaches it internally rather than a general survey.",
	},
	{
		title: 'Generative AI Leader',
		location: '',
		services: 'Google',
		year: '',
		src: 'docs/generative-ai-leader/professional-certificate.jpg',
		color: '#dbeafe',
		url: 'https://coursera.org/verify/professional-cert/OVKLY5LL3T9D',
		categories: ['skills'],
		slug: 'generative-ai-leader',
		summary:
			"Google Cloud's Generative AI Leader path, taken as five courses and the professional certificate that closes them. It works through foundational concepts and the wider model landscape, then through the practical use of generative AI apps and agents inside an organisation.",
		documents: [
			{
				src: 'docs/generative-ai-leader/professional-certificate.jpg',
				title: 'Generative AI Leader',
				kind: 'Professional Certificate',
				date: 'Feb 24, 2026',
				url: 'https://coursera.org/verify/professional-cert/OVKLY5LL3T9D',
			},
			{
				src: 'docs/generative-ai-leader/beyond-the-chatbot.jpg',
				title: 'Gen AI: Beyond the Chatbot',
				kind: 'Course',
				date: 'Feb 24, 2026',
				url: 'https://coursera.org/verify/T8N2Q9PG29DE',
			},
			{
				src: 'docs/generative-ai-leader/foundational-concepts.jpg',
				title: 'Gen AI: Unlock Foundational Concepts',
				kind: 'Course',
				date: 'Feb 24, 2026',
				url: 'https://coursera.org/verify/AS4R0VGJDHKU',
			},
			{
				src: 'docs/generative-ai-leader/navigate-the-landscape.jpg',
				title: 'Gen AI: Navigate the Landscape',
				kind: 'Course',
				date: 'Feb 24, 2026',
				url: 'https://coursera.org/verify/HOT4TLCBAXN0',
			},
			{
				src: 'docs/generative-ai-leader/gen-ai-apps.jpg',
				title: 'Gen AI Apps: Transform Your Work',
				kind: 'Course',
				date: 'Feb 24, 2026',
				url: 'https://coursera.org/verify/9EB8209VYFOF',
			},
			{
				src: 'docs/generative-ai-leader/gen-ai-agents.jpg',
				title: 'Gen AI Agents: Transform Your Organization',
				kind: 'Course',
				date: 'Feb 24, 2026',
				url: 'https://coursera.org/verify/5MIF1W4WQYPN',
			},
		],
	},
	{
		title: 'Google AI',
		location: '',
		services: 'Google',
		year: '',
		src: 'docs/google-ai/professional-certificate.jpg',
		color: '#dbeafe',
		url: 'https://coursera.org/verify/professional-cert/XA4UKVE5E1HF',
		categories: ['skills'],
		slug: 'google-ai',
		summary:
			"Google's AI Professional Certificate, taken as seven courses and the certificate that closes them. Each course applies AI to a different part of everyday work — research, writing, content, data analysis and app building — and is assessed on the artefacts produced rather than on recall.",
		documents: [
			{
				src: 'docs/google-ai/professional-certificate.jpg',
				title: 'Google AI',
				kind: 'Professional Certificate',
				date: 'Mar 5, 2026',
				url: 'https://coursera.org/verify/professional-cert/XA4UKVE5E1HF',
			},
			{
				src: 'docs/google-ai/ai-fundamentals.jpg',
				title: 'AI Fundamentals',
				kind: 'Course',
				date: 'Mar 5, 2026',
				url: 'https://coursera.org/verify/LYYH712ZECCV',
			},
			{
				src: 'docs/google-ai/brainstorming-planning.jpg',
				title: 'AI for Brainstorming and Planning',
				kind: 'Course',
				date: 'Mar 5, 2026',
				url: 'https://coursera.org/verify/9ZHM69JDTJDM',
			},
			{
				src: 'docs/google-ai/research-insights.jpg',
				title: 'AI for Research and Insights',
				kind: 'Course',
				date: 'Mar 5, 2026',
				url: 'https://coursera.org/verify/RVHQ8AYFBMOL',
			},
			{
				src: 'docs/google-ai/writing-communicating.jpg',
				title: 'AI for Writing and Communicating',
				kind: 'Course',
				date: 'Mar 5, 2026',
				url: 'https://coursera.org/verify/2NQX1ZK9XHWD',
			},
			{
				src: 'docs/google-ai/content-creation.jpg',
				title: 'AI for Content Creation',
				kind: 'Course',
				date: 'Mar 5, 2026',
				url: 'https://coursera.org/verify/98IBF44Z2HSW',
			},
			{
				src: 'docs/google-ai/data-analysis.jpg',
				title: 'AI for Data Analysis',
				kind: 'Course',
				date: 'Mar 5, 2026',
				url: 'https://coursera.org/verify/CFDQ112N06OQ',
			},
			{
				src: 'docs/google-ai/app-building.jpg',
				title: 'AI for App Building',
				kind: 'Course',
				date: 'Mar 5, 2026',
				url: 'https://coursera.org/verify/KMEBMPL174CP',
			},
		],
	},
	{
		title: 'Microsoft 365 | Generative AI',
		location: '',
		services: 'Microsoft ',
		year: '',
		src: 'docs/microsoft-365-generative-ai/professional-certificate.jpg',
		color: '#dbeafe',
		url: 'https://coursera.org/verify/professional-cert/X7QXFIEEJ7QP',
		categories: ['skills'],
		slug: 'microsoft-365-generative-ai',
		summary:
			"Microsoft's generative AI path across Microsoft 365, taken as four courses and the professional certificate that closes them. It covers Copilot in Excel, in PowerPoint and Word, and in Teams and Outlook, with the emphasis on day-to-day workflow rather than on the tooling itself.",
		documents: [
			{
				src: 'docs/microsoft-365-generative-ai/professional-certificate.jpg',
				title: 'Microsoft 365 with Generative AI',
				kind: 'Professional Certificate',
				date: 'May 13, 2026',
				url: 'https://coursera.org/verify/professional-cert/X7QXFIEEJ7QP',
			},
			{
				src: 'docs/microsoft-365-generative-ai/fundamentals.jpg',
				title: 'Fundamentals of Microsoft 365 Generative AI',
				kind: 'Course',
				date: 'Feb 16, 2026',
				url: 'https://coursera.org/verify/QIVE35SIVDBV',
			},
			{
				src: 'docs/microsoft-365-generative-ai/excel.jpg',
				title: 'Data Analysis and Visualization with Generative AI in Excel',
				kind: 'Course',
				date: 'Feb 23, 2026',
				url: 'https://coursera.org/verify/Z9UP07O252N6',
			},
			{
				src: 'docs/microsoft-365-generative-ai/powerpoint-word.jpg',
				title:
					'Generative AI for PowerPoint and Word to Optimize Content Creation',
				kind: 'Course',
				date: 'Mar 5, 2026',
				url: 'https://coursera.org/verify/AO8K3HMJOXZ5',
			},
			{
				src: 'docs/microsoft-365-generative-ai/teams-outlook.jpg',
				title: 'Generative AI for Advanced Collaboration in Teams and Outlook',
				kind: 'Course',
				date: 'May 13, 2026',
				url: 'https://coursera.org/verify/1EP4P38RL5VR',
			},
		],
	},
	{
		title: 'AI from the data center to the edge an optimized path',
		location: '',
		services: 'Intel® AI Academy',
		year: '',
		src: 'docs/intel-ai-data-center-to-edge.jpg',
		color: '#dbeafe',
		url: 'https://www.credly.com/badges/f115a421-40e7-40f5-b0eb-3c643b72c26a',
		categories: ['skills'],
		slug: 'intel-ai-data-center-to-edge',
		summary:
			'An Intel AI Academy track on where an AI workload should actually run, and what changes as it moves from the data centre out to the edge. Issued as a verifiable Credly badge rather than a paper certificate.',
	},
	{
		title:
			'AWS Cloud Practitioner Essentials | Building modern python application on Amazon Web Service',
		location: '',
		services: 'AWS',
		year: '',
		src: 'docs/aws-cloud-practitioner/cloud-practitioner-essentials.jpg',
		color: '#dbeafe',
		url: 'https://coursera.org/verify/A9ZQ3VE2D7A8',
		categories: ['skills'],
		slug: 'aws-cloud-practitioner',
		summary:
			'Two AWS certificates the title already joins: the Cloud Practitioner Essentials foundation, and a Coursera course on building modern Python applications on AWS. One covers the platform — its services, its pricing model, its shape — and the other the practice of shipping on it.',
		documents: [
			{
				src: 'docs/aws-cloud-practitioner/cloud-practitioner-essentials.jpg',
				title: 'AWS Cloud Practitioner Essentials',
				kind: 'Course',
			},
			{
				src: 'docs/aws-cloud-practitioner/modern-python-on-aws.jpg',
				title: 'Building Modern Python Applications on AWS',
				kind: 'Course',
				date: 'Apr 24, 2021',
				url: 'https://coursera.org/verify/A9ZQ3VE2D7A8',
			},
		],
	},
	{
		title:
			'Build a Face Recognition Application using Python | AI-For-India Event ',
		location: '',
		services: 'GUVI',
		year: '2021',
		src: 'docs/guvi-face-recognition.jpg',
		color: '#dbeafe',
		url: 'https://www.guvi.in/certificate?id=6n39934IFA6v3xj114',
		categories: ['skills'],
		slug: 'guvi-face-recognition',
		summary:
			'A build-along session at GUVI’s AI-For-India event, ending in a working face recognition application written in Python. Issued as a certificate of achievement in April 2021 and verifiable against GUVI’s own record.',
	},
	{
		title: 'Introduction to iot',
		location: '',
		services: 'Cisco Networking Academy',
		year: '',
		src: 'docs/cisco-introduction-to-iot.jpg',
		color: '#dbeafe',
		url: 'https://www.credly.com/badges/62a78b2a-b09f-4a37-bac2-21794bcdc258',
		categories: ['skills'],
		slug: 'cisco-introduction-to-iot',
		summary:
			'Cisco Networking Academy’s introduction to the Internet of Things — how connected devices are put together, what they do with the data they gather, and where the security boundaries sit. Issued as a verified Credly badge.',
	},
	{
		title: 'Geospatial Technologies for Archeological Studies ',
		location: '',
		services: 'Indian Institute of Remote Sensing, Dehradun, ISRO',
		year: '2021',
		src: 'docs/iirs-geospatial-technologies.jpg',
		color: '#ddd6fe',
		url: 'https://certificate.iirs.gov.in',
		categories: ['development', 'backend', 'skills'],
		slug: 'iirs-geospatial-technologies',
		summary:
			'A short online course from IIRS Dehradun, under ISRO and the Department of Space, on applying remote sensing and geospatial method to archaeological survey. Run 17–21 May 2021 across seven and a half hours, and validated against the institute’s own certificate portal.',
	},
	{
		title: 'Professional Development Program on Total Digital Transformation',
		location: '',
		services: 'MSME Technology Development Centre, Govt. of India',
		year: '2021',
		src: 'docs/msme-total-digital-transformation.jpg',
		color: '#dbeafe',
		url: 'https://drive.google.com/drive/u/0/folders/1-TjIeN--GT5WFDnu_pqU6xD5QCLOo6yx',
		categories: ['frontend', 'development', 'management'],
		slug: 'msme-total-digital-transformation',
		summary:
			'A professional development programme run by MSME-PPDC Agra with the Centre for Lean and Six Sigma at SRM, 15–20 November 2021. It treats digital transformation as an operations problem — process before tooling — rather than as a technology rollout.',
	},
	{
		title: 'Agriculture automation, CPS -Advance Skill Training workshop',
		location: '',
		// The issuer had been sitting in `url`, where it rendered as a link that
		// went nowhere. It belongs here.
		services: 'IIT Ropar',
		year: '2021',
		src: 'docs/iit-ropar-agriculture-automation.jpg',
		color: '#dbeafe',
		url: '',
		categories: ['skills'],
		slug: 'iit-ropar-agriculture-automation',
		summary:
			'A cyber-physical systems skill workshop for agriculture automation, run 24 May to 1 June 2021 by IIT Ropar’s Technology and Innovation Foundation through its Agriculture and Water Technology Development Hub.',
	},
	{
		title: 'Internship Training on IoT',
		location: '',
		services: ' MSME Technology Development Centre, Govt. of India',
		year: '2021',
		src: 'docs/msme-iot-internship.jpg',
		color: '#dbeafe',
		url: '',
		categories: ['skills'],
		slug: 'msme-iot-internship',
		summary:
			'A month of online training in the Internet of Things at MSME-PPDC Agra, a Government of India organisation, from 4 August to 3 September 2021.',
	},
	{
		title:
			'Internship Program on Functional Verification using System Verilog ',
		location: '',
		services: 'CoreEL Technologies ',
		year: '2022',
		src: 'docs/systemverilog-functional-verification.jpg',
		color: '#dbeafe',
		url: '',
		categories: ['skills'],
		slug: 'systemverilog-functional-verification',
		summary:
			'A month at Sandeepani School of Embedded System Design in Bangalore, CoreEL’s training arm, on functional verification in SystemVerilog — the discipline of proving a design does what it claims before it reaches silicon. Held 27 June to 26 July 2022.',
	},
	{
		title: 'Internship Training on Microcontroller programming',
		location: '',
		services: ' MSME Technology Development Centre, Govt. of India',
		year: '2021',
		src: 'docs/msme-microcontroller-programming.jpg',
		color: '#dbeafe',
		url: '',
		categories: ['skills'],
		slug: 'msme-microcontroller-programming',
		summary:
			'A month of online training in microcontroller programming at MSME-PPDC Agra, a Government of India organisation, from 4 August to 3 September 2021.',
	},
	{
		title: 'Internship Training on Computer Hardware & Networking',
		location: '',
		services: '  MSME Technology Development Centre, Govt. of India',
		year: '2022',
		src: 'docs/msme-computer-hardware-networking.jpg',
		color: '#dbeafe',
		url: '',
		categories: ['skills'],
		slug: 'msme-computer-hardware-networking',
		summary:
			'Ninety-six hours of online training in computer hardware and networking at MSME-PPDC Agra, certified at NSQF level 2 and run from 11 March to 10 April 2022.',
	},
	{
		title: 'Internship Program on VLSI',
		location: '',
		services: 'Vyorius',
		year: '2022',
		src: 'docs/vyorius-vlsi.jpg',
		color: '#dbeafe',
		url: '',
		categories: ['skills'],
		slug: 'vyorius-vlsi',
		summary:
			'A two-month industrial programme with Vyorius, November 2021 to January 2022, delivered as working hardware: Verilog circuits on an FPGA, UART character transmission, and Mealy, Moore and up-down counter state machines.',
	},
	{
		title: 'Internship Program on IoT ',
		location: '',
		services: 'Vyorius',
		year: '2022',
		src: 'docs/vyorius-iot.jpg',
		color: '#dbeafe',
		url: '',
		categories: ['skills'],
		slug: 'vyorius-iot',
		summary:
			'A two-month industrial programme with Vyorius, November 2021 to January 2022, assessed on built projects — an IoT smart agriculture system, an ultrasonic obstacle-avoidance robot, and an RGB pattern driver.',
	},
	{
		title: 'Student Ambassador  ',
		location: '',
		services: 'IIT Bombay',
		year: '2021',
		// The tile carries the October certificate; the page carries both.
		src: 'docs/student-ambassador/languify.jpg',
		color: '#dbeafe',
		url: '',
		categories: ['management'],
		slug: 'student-ambassador',
		summary:
			'Two Student Ambassador terms run through 1Stop — the first with Techfest at IIT Bombay, the second with Languify. Both were campus-facing: running outreach, building a cohort, and carrying a programme through to the end of its term.',
		documents: [
			{
				src: 'docs/student-ambassador/languify.jpg',
				title: 'Student Ambassador Program — Languify',
				kind: 'Certificate of Excellence',
				date: '21-10-2021',
			},
			{
				src: 'Screenshot_2026-07-09_115606.png',
				title: 'Student Ambassador Program — Techfest, IIT Bombay',
				kind: 'Certificate of Excellence',
				date: '02-07-2021',
			},
		],
	},
	{
		title: 'Training course on introduction of Hydraulics Pneumatics and PLCs ',
		location: '',
		services: 'SRM University ',
		year: '2019',
		src: 'docs/hydraulics-pneumatics-plcs.jpg',
		color: '#dbeafe',
		url: '',
		categories: ['skills'],
		slug: 'hydraulics-pneumatics-plcs',
		summary:
			'A ten-hour Tech Track course on hydraulics, pneumatics and programmable logic controllers, run 19–23 August as part of Aaruush, SRM’s national techno-management festival.',
	},
	{
		title: 'AI',
		location: '',
		services: 'My Captain',
		year: '2020',
		src: 'docs/mycaptain-ai.jpg',
		color: '#dbeafe',
		url: '',
		categories: ['skills'],
		slug: 'mycaptain-ai',
		summary:
			'MyCaptain’s artificial intelligence course, completed in June 2020 under a mentor rather than as self-study. MyCaptain runs as a Climber Knowledge and Careers initiative incubated at NSRCEL, IIM Bangalore.',
	},
	{
		title: 'Introduction to Cybersecurity course',
		location: '',
		services: 'Cisco Networking Academy® ',
		year: '',
		src: 'docs/cisco-introduction-to-cybersecurity.jpg',
		color: '#dbeafe',
		url: '',
		categories: ['skills'],
		slug: 'cisco-introduction-to-cybersecurity',
		summary:
			'Cisco Networking Academy’s introduction to cybersecurity — the shape of common attacks, how organisations defend against them, and where the practice sits as a career. Issued as a verified digital badge.',
	},
	{
		title: '3rd PLACE WINNER | NATO INNOVATION CHALLENGE',
		location: '',
		services: 'Ixana',
		year: '',
		src: 'Screenshot_2026-07-17_154453.png',
		color: '#dbeafe',
		url: 'https://www.act.nato.int/article/17th-innovation-challenge-concludes/',
		categories: ['achievements'],
		slug: 'nato-innovation-challenge',
		summary:
			'Third place in NATO’s 17th Innovation Challenge, run by Allied Command Transformation. Ixana entered Wi-R for combat casualty care — moving medical data along the body at a fraction of a radio’s detectable signature.',
	},
	{
		title: 'EE Times Silicon 100 (2x) ',
		location: '',
		services: 'Ixana',
		year: '',
		src: '1752875231267.jpg',
		color: '#dbeafe',
		url: 'https://drive.google.com/drive/u/0/folders/1-TjIeN--GT5WFDnu_pqU6xD5QCLOo6yx',
		categories: ['achievements'],
		slug: 'ee-times-silicon-100',
		summary:
			'EE Times’ Silicon 100 is its annual list of emerging semiconductor companies worth watching. Ixana has been named to it twice, for Wi-R — near-field electric communication at a fraction of the power a radio needs.',
	},
	{
		title: 'IoT Breakthrough Award, IoT Wearables Innovation of the Year',
		location: '',
		services: 'Ixana',
		year: '',
		src: 'Screenshot_2026-07-17_152136.png',
		color: '#dbeafe',
		url: 'https://iotbreakthrough.com/2024-winners/',
		categories: ['achievements'],
		slug: 'iot-breakthrough-award',
		summary:
			'IoT Wearables Innovation of the Year in the 2024 IoT Breakthrough Awards, which recognise products and companies across the connected-device market. Awarded to Ixana for Wi-R.',
	},
	{
		title: 'CES Innovation Award ',
		location: '',
		services: 'Ixana',
		year: '',
		src: 'Screenshot_2026-07-17_184538.png',
		color: '#dbeafe',
		url: 'https://www.ces.tech/ces-innovation-awards/2024/ixanas-wi-r-100x-lower-power-4mbps-chip-for-wearables/',
		categories: ['achievements'],
		slug: 'ces-innovation-award',
		summary:
			'A CES Innovation Award honoree for Ixana’s Wi-R chip — 4 Mbit/s to a wearable at roughly a hundredth of the power a conventional radio link would draw. The awards are judged ahead of the show by an independent panel.',
	},
	{
		title:
			'Talk | Industry 4.0 and connecting the dots with electronic sector ',
		location: '',
		services: 'IISc - EnTIISc',
		year: '',
		src: 'Screenshot_2026-07-12_135049.png',
		color: '#dbeafe',
		url: '',
		categories: ['achievements'],
		slug: 'iisc-industry-4-0-talk',
		summary:
			'An invited talk at EnTIISc, the entrepreneurship cell at the Indian Institute of Science, on 13 December 2023 — Industry 4.0 and where the electronics sector connects to it, given as founder of Ricky Kids.',
	},
	{
		title: 'Silver medalist | ECE 2023',
		location: '',
		services: 'SRM University',
		year: '',
		src: 'Screenshot_2026-07-17_115248.png',
		color: '#dbeafe',
		url: '',
		categories: ['achievements'],
		slug: 'srm-silver-medalist-ece',
		summary:
			'Silver medal for the 2023 Electronics and Communication Engineering cohort at SRM Institute of Science and Technology — an academic ranking across the full degree, not a single result.',
	},
	{
		title: 'CNET | Wi-R and the personal body network',
		location: '',
		services: 'Ixana',
		year: '2026',
		src: 'docs/ixana/cnet-personal-body-network.png',
		titleCard: true,
		color: '#dbeafe',
		url: 'https://www.cnet.com/tech/computing/i-just-saw-the-wireless-body-transmitting-network-my-future-wearables-need/',
		categories: ['achievements'],
		slug: 'ixana-cnet-feature',
		summary:
			'A January 2026 CNET feature on Wi-R — “I Just Saw the Wireless Body Transmitting Network My Future Wearables Need”. Consumer-press coverage of a body-area network is rare; this one was written from a live demonstration.',
	},
	{
		title: 'Power Electronics News | Transmitting data through E-fields',
		location: '',
		services: 'Ixana',
		year: '2026',
		src: 'docs/ixana/power-electronics-news-e-fields.png',
		titleCard: true,
		color: '#dbeafe',
		url: 'https://www.powerelectronicsnews.com/a-new-wireless-paradigm-transmitting-data-through-e-fields/',
		categories: ['achievements'],
		slug: 'ixana-power-electronics-news',
		summary:
			'“A New Wireless Paradigm: Transmitting Data Through E-fields”, Power Electronics News, January 2026. A trade-press treatment of Wi-R written for engineers, on why a near-field electric link behaves differently from a radio one.',
	},
	{
		title: '1st Prize |  Toys for Autistic kids',
		location: '',
		services:
			'Indo Universal Collaboration for Engineering Education ( IUCEE ) ',
		year: '2022',
		src: 'docs/iucee-toys-first-prize.jpg',
		color: '#dbeafe',
		url: '',
		categories: ['achievements'],
		slug: 'iucee-toys-first-prize',
		summary:
			'Recognised by the IUCEE Foundation at ICTIEE 2022 for Toys for Autistic Kids, a team project graded A through the Project Oriented Problem Based Learning programme run August to December 2021.',
	},
	{
		title: 'Silver Medal | Research Day',
		location: '',
		services: 'SRM University ',
		year: '2022',
		src: 'docs/srm-research-day.jpg',
		color: '#dbeafe',
		url: '',
		categories: ['achievements'],
		slug: 'srm-research-day',
		summary:
			'Presented a paper at SRM Research Day on 28 February 2022, representing the Department of Electronics and Communication Engineering.',
	},
	{
		title: 'Winner | Cloud based Analog IC Design Hackathon ',
		location: '',
		services: 'IIT Hyderabad',
		year: '2022',
		src: 'docs/analog-ic-hackathon.jpg',
		color: '#dbeafe',
		url: 'https://hackathoniith.in',
		categories: ['achievements'],
		slug: 'analog-ic-hackathon',
		summary:
			'A cloud-based analog IC design hackathon run 15 February to 1 March 2022 by IIT Hyderabad, sponsored by Synopsys with VLSI System Design. The entry was a 3-bit binary-to-Gray code converter built on the Synopsys Custom Compiler platform.',
	},
	{
		title:
			'Sachetna | Talk series for disabilities, accessibility, advocacy and awareness by parents professionals or professionals ',
		location: '',
		services: 'Sunshine Autism Care society ',
		year: '',
		src: 'docs/sachetna-talk-series.jpg',
		color: '#dbeafe',
		url: '',
		categories: ['achievements'],
		slug: 'sachetna-talk-series',
		summary:
			'Sachetna is a talk series on disability, accessibility and advocacy run by the Sunshine Autism Care Society. This certificate recognises the creation of an assistive device for e-learning, presented into that series.',
	},
	{
		title:
			'Attempt for most users to take an online computer programming lesson in 24 hours',
		location: '',
		services: 'Guinness world records',
		year: '2021',
		src: 'docs/guinness-world-record-attempt.jpg',
		color: '#dbeafe',
		url: '',
		categories: ['achievements'],
		slug: 'guinness-world-record-attempt',
		summary:
			'An official Guinness World Records attempt on 24 April 2021, organised by GUVI with AICTE India: the most users to take an online computer programming lesson within twenty-four hours.',
	},
	{
		title: 'Python',
		location: '',
		services: 'Google',
		year: '2021',
		src: 'docs/google-python-crash-course.jpg',
		color: '#dbeafe',
		url: 'https://coursera.org/verify/9749Y8RQR6RW',
		categories: ['skills'],
		slug: 'google-python-crash-course',
		summary:
			'Google’s Crash Course on Python, completed February 2021 through Coursera — the first course of its IT automation track, covering the language from syntax through to writing scripts that do real work.',
	},
	{
		title: 'Appreciation | Toys for Autistic kids',
		location: '',
		services:
			'Indo Universal Collaboration for Engineering Education ( IUCEE )',
		year: '2021',
		src: 'docs/iucee-toys-popbl.jpg',
		color: '#dbeafe',
		url: '',
		categories: ['achievements'],
		slug: 'iucee-toys-appreciation',
		summary:
			'Recognition from the IUCEE Foundation for grade A work and the presentation of Toys for Autistic Kids in its Project Oriented Problem Based Learning programme, August to December 2021.',
	},
	{
		title: '2nd runner up | THINKTECH2K21 ',
		location: '',
		services: 'Don bosco college of engineering',
		year: '2021',
		src: 'docs/thinktech2k21.jpg',
		color: '#dbeafe',
		url: '',
		categories: ['achievements'],
		slug: 'thinktech2k21',
		summary:
			'ThinkTech2k21, a national-level project idea competition held on 27 November 2021 by Don Bosco College of Engineering, Goa, run by its Final Year Project Quality Assurance Committee with the Don Bosco Electronics and Telecommunication Society.',
	},
	{
		title: 'Idea Generation challenge | Sanrachna',
		location: '',
		services: 'BHEL',
		year: '2022',
		src: 'docs/bhel-idea-generation.jpg',
		color: '#dbeafe',
		url: '',
		categories: ['achievements'],
		slug: 'bhel-idea-generation',
		summary:
			'BHEL’s Idea Generation Challenge, held 10–16 January 2022 during the Azadi ka Amrit Mahotsav iconic week, with the certificate signed by its Executive Director for Corporate Strategy and Industrial Operations.',
	},
	{
		title: 'SRM PROJECT EXPO’21',
		location: '',
		services: 'SRM University ',
		year: '2021',
		src: 'docs/srm-project-expo-21.jpg',
		color: '#dbeafe',
		url: '',
		categories: ['achievements'],
		slug: 'srm-project-expo-21',
		summary:
			'Presented Toys for Autistic Kids at SRM Project Expo ’21 on 10 December 2021, hosted by the Department of Computational Intelligence with SRM-IET and the SRM MTS student chapter.',
	},
	{
		title: '2nd runner up | Milaap',
		location: '',
		services: 'Milaap 2018',
		year: '2018',
		src: 'docs/milaap-2018.jpg',
		color: '#dbeafe',
		url: '',
		categories: ['achievements'],
		slug: 'milaap-2018',
		summary:
			'Third prize for a photo essay at Milaap 2018, run by SPICMACAY — the Society for Promotion of Indian Classical Music and Culture Amongst Youth — on 28 and 29 September 2018.',
	},
	{
		title: '2nd runner up | Literaria ',
		location: '',
		services: 'Xavotsav ',
		year: '2018',
		src: 'docs/literaria-2018.jpg',
		color: '#dbeafe',
		url: '',
		categories: ['achievements'],
		slug: 'literaria-2018',
		summary:
			'Literaria 2018, the English Academy festival at St. Xavier’s College, Kolkata. The entry was Frozen, a photography event.',
	},
	{
		title: 'INFRAME | Photography workshop',
		location: '',
		services: 'SRM University ',
		year: '2020',
		src: 'docs/inframe-photography.jpg',
		color: '#dbeafe',
		url: '',
		categories: ['achievements'],
		slug: 'inframe-photography',
		summary:
			'InFrame, a photography workshop held on 20 August 2020 as part of Aaruush, SRM’s national techno-management festival, and led by a working professional photographer.',
	},
	{
		title:
			'YouthRep/Marketing | Business Development, marketing and sales, community building by creating impact in my college',
		location: '',
		services: 'MyCaptain | SRM University ',
		year: '2020',
		src: 'docs/mycaptain-youth-rep.jpg',
		color: '#dbeafe',
		url: '',
		categories: ['skills'],
		slug: 'mycaptain-youth-rep',
		summary:
			'A MyCaptain YouthRep internship, 1 April to 1 May 2020, in business development, marketing and sales — the work being to build a community on campus rather than to sell into one.',
	},
	{
		title: 'Christmas photography contest ',
		location: '',
		services: 'Kolkata sutra',
		year: '2018',
		src: 'Screenshot_2026-07-12_132544.png',
		color: '#dbeafe',
		url: '',
		categories: ['achievements'],
		slug: 'kolkata-sutra-christmas-photography',
		summary:
			'A Christmas photography contest run by Kolkata Sutra on 29 December 2018, on the theme Christmas In Kolkata.',
	},
	{
		title: 'C Programming Course ',
		location: '',
		services: 'My Captain ',
		year: '2020',
		src: 'docs/mycaptain-cpp.jpg',
		color: '#dbeafe',
		url: '',
		categories: ['skills'],
		slug: 'mycaptain-c-programming',
		summary:
			'A certificate of competency, not attendance: MyCaptain’s C programming course for October 2020, assessed on three built projects — a first program, a grade calculator and a bank management system.',
	},
	{
		title: 'Android App Development ',
		location: '',
		services: 'My Captain',
		year: '',
		src: 'docs/mycaptain-android.jpg',
		color: '#dbeafe',
		url: '',
		categories: ['skills'],
		slug: 'mycaptain-android',
		summary:
			'MyCaptain’s Android app development course, completed under a mentor and assessed on work built during the cohort rather than on a final exam.',
	},
	{
		title: 'Graphic Design',
		location: '',
		services: 'My Captain',
		year: '',
		src: 'docs/mycaptain-graphic-design.jpg',
		color: '#dbeafe',
		url: '',
		categories: ['skills'],
		slug: 'mycaptain-graphic-design',
		summary:
			'MyCaptain’s graphic design course, run as a mentored cohort with the work judged on what was actually produced during it.',
	},
	{
		title: 'Web Development',
		location: '',
		services: 'My Captain',
		year: '',
		src: 'docs/mycaptain-web-development.jpg',
		color: '#dbeafe',
		url: '',
		categories: ['skills'],
		slug: 'mycaptain-web-development',
		summary:
			'MyCaptain’s web development course, run as a mentored cohort and completed on built work rather than on coursework alone.',
	},
	{
		title: 'Python',
		location: '',
		services: 'My Captain',
		year: '',
		src: 'docs/mycaptain-python.jpg',
		color: '#dbeafe',
		url: '',
		categories: ['skills'],
		slug: 'mycaptain-python',
		summary:
			'MyCaptain’s Python programming course, taken as a mentored cohort — the second Python certificate here, alongside Google’s crash course, and the earlier of the two.',
	},
	{
		title: 'Data collection workshop | R&D project ',
		location: '',
		services: 'Samsung Research Institute',
		year: '2019',
		src: 'docs/samsung-data-collection.jpg',
		color: '#dbeafe',
		url: '',
		categories: ['skills'],
		slug: 'samsung-data-collection',
		summary:
			'A data collection workshop on 8 and 9 November 2019 for an R&D project run by SRM’s Department of Computer Science and Engineering with Samsung Research Institute, Bangalore. Issued as a certificate of gratitude for the contribution to that dataset.',
	},
	{
		title:
			'Research Paper | First international conference on technologies for smart green connected society 2021',
		location: '',
		services: 'SPAST',
		year: '2021',
		src: 'docs/spast-ictgs-2021.jpg',
		color: '#dbeafe',
		url: '',
		categories: ['skills'],
		slug: 'spast-ictgs-2021',
		summary:
			'Presented “The ENVI-CITY: Vision of a sustainable smart city of the future” at ICTSGS-1, held online on 29 and 30 November 2021. The conference was led by Yamagata University, Japan and organised by the SPAST Foundation, with ACS Publications and the Electrochemical Society as partners.',
	},
	{
		title:
			'Training Program on “Incident Response System: Basic & Intermediate” ',
		location: '',
		services:
			'National Institute of Disaster Management, Ministry of Home Affairs, Govt. of India ',
		year: '',
		src: 'docs/nidm-incident-response.jpg',
		color: '#dbeafe',
		url: '',
		categories: ['skills'],
		slug: 'nidm-incident-response',
		summary:
			'An e-training programme on the Incident Response System, basic and intermediate, run by the National Institute of Disaster Management under India’s Ministry of Home Affairs — the command structure a state actually uses when coordinating a disaster response.',
	},
	{
		title:
			'Consumer outreach program | Discussion of network usage and 5G with its efficiency',
		location: '',
		services: 'TRAI- Telecom Regulatory Authority of India, Govt. of India',
		year: '2021',
		src: 'docs/trai-consumer-outreach.jpg',
		color: '#dbeafe',
		url: '',
		categories: ['skills'],
		slug: 'trai-consumer-outreach',
		summary:
			'An online consumer outreach programme held on 21 October 2021 by the Hyderabad regional office of the Telecom Regulatory Authority of India, on network usage and the efficiency case for 5G.',
	},
	{
		title: 'Webinar | Hybrid electric technology',
		location: '',
		services: 'Toyota Kirloskar Motor pvt.Ltd',
		year: '2021',
		src: 'docs/toyota-hybrid-electric.jpg',
		color: '#dbeafe',
		url: '',
		categories: ['skills'],
		slug: 'toyota-hybrid-electric',
		summary:
			'A Toyota Kirloskar Motor webinar on hybrid electric vehicle technology, run by the company’s own Learning and Development group in India — the powertrain explained by the manufacturer building it.',
	},
	{
		title: 'Pro MFG Plant Maintenance and Asset Management Summit  2021',
		location: '',
		services: 'Pro MFG Media',
		year: '2021',
		src: 'docs/promfg-summit-2021.jpg',
		color: '#dbeafe',
		url: '',
		categories: ['skills'],
		slug: 'promfg-summit-2021',
		summary:
			'The second edition of the Pro MFG Plant Maintenance and Asset Management Summit, held 24 November 2021 — an industry gathering on maintenance strategy and asset lifecycle rather than an academic one.',
	},
];

export const filters = [
	{ key: 'all', label: 'All' },
	{ key: 'management', label: 'Management' },
	{ key: 'skills', label: 'Skills' },
	{ key: 'achievements', label: 'Achievements' },
] as const;

export type FilterKey = (typeof filters)[number]['key'];
