import type { CertificationItem } from './types';

export const certificationItems: CertificationItem[] = [
    {
        title: 'PMI Agile Certified Practitioner (PMI-ACP)',
        location: 'Null',
        services: 'Packt',
        year: '2023',
        src: 'Screenshot_2026-07-08_135720.png',
        color: '#dbeafe',
        url: 'https://drive.google.com/drive/u/0/folders/1-TjIeN--GT5WFDnu_pqU6xD5QCLOo6yx',
        categories: ['cloud', 'architecture'],
    },
    {
        title: 'Six Sigma Black Belt certification',
        location: 'Cloud Native Computing Foundation',
        services: 'Board of Regents of University System of Georgia',
        year: '2023',
        src: 'Screenshot_2026-07-08_135955.png',
        color: '#fae8ff',
        url: 'https://drive.google.com/drive/u/0/folders/1-TjIeN--GT5WFDnu_pqU6xD5QCLOo6yx',
        categories: ['devops', 'containers'],
    },
    {
        title: 'Global Student Trainee',
        location: '',
        services: 'Schneider Electric ',
        year: '',
        src: 'Screenshot_2026-07-08_135146.png',
        color: '',
        url: '',
        categories: ['development', 'frontend'],
    },
    {
        title: 'Professional Development Program on Total Digital Transformation',
        location: '',
        services: 'MSME Technology Development Centre, government of India',
        year: '',
        src: 'Screenshot_2026-07-08_135351.png',
        color: '#dbeafe',
        url: 'https://drive.google.com/drive/u/0/folders/1-TjIeN--GT5WFDnu_pqU6xD5QCLOo6yx',
        categories: ['frontend', 'development'],
    },
    {
        title: 'Geospatial Technologies for Archeological Studies ',
        location: '',
        services: 'Indian Institute of Remote Sensing, Dehradun, ISRO',
        year: '',
        src: 'Screenshot_2026-07-08_135602.png',
        color: '#ddd6fe',
        url: '',
        categories: ['development', 'backend'],
    },
    {
        title: 'Agriculture automation, CPS -Advance Skill Training workshop',
        location: '',
        services: '',
        year: '',
        src: 'Screenshot_2026-07-08_140133.png',
        color: '#dbeafe',
        url: 'IIT Ropar',
        categories: [],
    },
    {
        title: 'Introduction to iot',
        location: '',
        services: 'Cisco Networking Academy',
        year: '',
        src: 'Screenshot_2026-07-08_140354.png',
        color: '#dbeafe',
        url: '',
        categories: [],
    },
    {
        title: 'AI from the data center to the edge an optimized path',
        location: '',
        services: 'Intel\u00AE AI Academy',
        year: '',
        src: 'Screenshot_2026-07-08_140748.png',
        color: '#dbeafe',
        url: '',
        categories: [],
    },
    {
        title: 'Internship Training on IoT',
        location: '',
        services: ' MSME Technology Development Centre, government of India.',
        year: '',
        src: 'Screenshot_2026-07-09_113437.png',
        color: '#dbeafe',
        url: '',
        categories: [],
    },
    {
        title: 'Internship Program on Functional Verification using System Verilog ',
        location: '',
        services: 'CoreEL Technologies ',
        year: '',
        src: 'Screenshot_2026-07-09_113557.png',
        color: '#dbeafe',
        url: '',
        categories: [],
    },
    {
        title: 'AWS Cloud Practitioner Essentials | Building modern python application on Amazon Web Service',
        location: '',
        services: 'AWS',
        year: '',
        src: 'Screenshot_2026-07-09_113850.png',
        color: '#dbeafe',
        url: '',
        categories: [],
    },
    {
        title: 'Internship Training on Microcontroller programming',
        location: '',
        services: ' MSME Technology Development Centre, government of India.',
        year: '',
        src: 'Screenshot_2026-07-09_113959.png',
        color: '#dbeafe',
        url: '',
        categories: [],
    },
    {
        title: 'Internship Training on Computer Hardware & Networking',
        location: '',
        services: '  MSME Technology Development Centre, government of India.',
        year: '',
        src: 'Screenshot_2026-07-09_114351.png',
        color: '#dbeafe',
        url: '',
        categories: [],
    },
    {
        title: 'Internship Program on VLSI',
        location: '',
        services: 'Vyorius',
        year: '',
        src: 'Screenshot_2026-07-09_114605.png',
        color: '#dbeafe',
        url: '',
        categories: [],
    },
    {
        title: 'Internship Program on IoT ',
        location: '',
        services: 'Vyorius',
        year: '',
        src: 'Screenshot_2026-07-09_114813.png',
        color: '#dbeafe',
        url: '',
        categories: [],
    },
    {
        title: 'Student Ambassador  ',
        location: '',
        services: 'IIT Bombay',
        year: '',
        src: 'Screenshot_2026-07-09_115606.png',
        color: '#dbeafe',
        url: '',
        categories: [],
    },
    {
        title: 'Training course on introduction of Hydraulics Pneumatics and PLCs ',
        location: '',
        services: 'SRM University ',
        year: '',
        src: 'Screenshot_2026-07-12_125121.png',
        color: '#dbeafe',
        url: '',
        categories: [],
    },
    {
        title: 'Introduction to Cybersecurity course',
        location: '',
        services: 'Cisco Networking Academy\u00AE ',
        year: '',
        src: 'Screenshot_2026-07-12_125345.png',
        color: '#dbeafe',
        url: '',
        categories: [],
    },
    {
        title: 'Attempt for most users to take an online computer programming lesson in 24 hours',
        location: '',
        services: 'Guinness world records',
        year: '',
        src: 'Screenshot_2026-07-12_125530.png',
        color: '#dbeafe',
        url: '',
        categories: [],
    },
    {
        title: 'Build a Face Recognition Application using Python | AI-For-India Event ',
        location: '',
        services: 'GUVI',
        year: '',
        src: 'Screenshot_2026-07-12_125729.png',
        color: '#dbeafe',
        url: '',
        categories: [],
    },
    {
        title: 'Python',
        location: '',
        services: 'Google',
        year: '',
        src: 'Screenshot_2026-07-12_130148.png',
        color: '#dbeafe',
        url: '',
        categories: [],
    },
    {
        title: 'INFRAME | Photography workshop',
        location: '',
        services: 'SRM University ',
        year: '',
        src: 'Screenshot_2026-07-12_130512.png',
        color: '#dbeafe',
        url: '',
        categories: [],
    },
    {
        title: 'YouthRep/Marketing | Business Development, marketing and sales, community building by creating impact in my college',
        location: '',
        services: 'MyCaptain | SRM University ',
        year: '',
        src: 'Screenshot_2026-07-12_130735.png',
        color: '#dbeafe',
        url: '',
        categories: [],
    },
    {
        title: 'Christmas photography contest ',
        location: '',
        services: 'Kolkata sutra',
        year: '',
        src: 'Screenshot_2026-07-12_132544.png',
        color: '#dbeafe',
        url: '',
        categories: [],
    },
    {
        title: 'Literaria | 2nd runner up',
        location: '',
        services: 'Xavotsav ',
        year: '',
        src: 'Screenshot_2026-07-12_132817.png',
        color: '#dbeafe',
        url: '',
        categories: [],
    },
    {
        title: '2nd runner up ',
        location: '',
        services: 'Milaap 2018',
        year: '',
        src: 'Screenshot_2026-07-12_133513.png',
        color: '#dbeafe',
        url: '',
        categories: [],
    },
    {
        title: 'C Programming Course ',
        location: '',
        services: 'My Captain ',
        year: '',
        src: 'Screenshot_2026-07-12_133943.png',
        color: '#dbeafe',
        url: '',
        categories: [],
    },
    {
        title: 'AI',
        location: '',
        services: 'My Captain',
        year: '',
        src: 'Screenshot_2026-05-11_172942.png',
        color: '#dbeafe',
        url: '',
        categories: [],
    },
    {
        title: 'Android App Development ',
        location: '',
        services: 'My Captain',
        year: '',
        src: 'Screenshot_2026-07-12_134242.png',
        color: '#dbeafe',
        url: '',
        categories: [],
    },
    {
        title: 'Graphic Design',
        location: '',
        services: 'My Captain',
        year: '',
        src: 'Screenshot_2026-07-12_134357.png',
        color: '#dbeafe',
        url: '',
        categories: [],
    },
    {
        title: 'Web Development',
        location: '',
        services: 'My Captain',
        year: '',
        src: 'Screenshot_2026-07-12_134526.png',
        color: '#dbeafe',
        url: '',
        categories: [],
    },
    {
        title: 'Python',
        location: '',
        services: 'My Captain',
        year: '',
        src: 'Screenshot_2026-07-12_134638.png',
        color: '#dbeafe',
        url: '',
        categories: [],
    },
    {
        title: 'Talk | Industry 4.0 and connecting the dots with electronic sector ',
        location: '',
        services: 'IISC - EnTIISc',
        year: '',
        src: 'Screenshot_2026-07-12_135049.png',
        color: '#dbeafe',
        url: '',
        categories: [],
    },
    {
        title: '1st Prize |  Toys for Autistic kids',
        location: '',
        services: 'Indo Universal Collaboration for Engineering Education ( IUCEE ) ',
        year: '',
        src: 'Screenshot_2026-07-12_135605.png',
        color: '#dbeafe',
        url: '',
        categories: [],
    },
    {
        title: 'Appreciation | Toys for Autistic kids',
        location: '',
        services: 'Indo Universal Collaboration for Engineering Education ( IUCEE )',
        year: '',
        src: 'Screenshot_2026-07-12_140048.png',
        color: '#dbeafe',
        url: '',
        categories: [],
    },
    {
        title: 'Cloud based Analog IC Design Hackathon',
        location: '',
        services: 'IIT Hyderabad',
        year: '',
        src: 'Screenshot_2026-07-12_140421.png',
        color: '#dbeafe',
        url: '',
        categories: [],
    },
    {
        title: 'Silver Medal | Research Day',
        location: '',
        services: 'SRM University ',
        year: '',
        src: 'Screenshot_2026-07-12_140558.png',
        color: '#dbeafe',
        url: '',
        categories: [],
    },
    {
        title: 'Data collection workshop | R&D project ',
        location: '',
        services: 'Samsung Research Institute',
        year: '',
        src: 'Screenshot_2026-07-12_140803.png',
        color: '#dbeafe',
        url: '',
        categories: [],
    },
    {
        title: 'Idea Generation challenge | Sanrachna',
        location: '',
        services: 'BHEL',
        year: '',
        src: 'Screenshot_2026-07-12_141154.png',
        color: '#dbeafe',
        url: '',
        categories: [],
    },
    {
        title: 'Sachetna | Talk series for disabilities, accessibility, advocacy and awareness by parents professionals or professionals ',
        location: '',
        services: 'Sunshine Autism Care society ',
        year: '',
        src: 'Screenshot_2026-07-12_141345.png',
        color: '#dbeafe',
        url: '',
        categories: [],
    },
    {
        title: 'Research Paper | First international conference on technologies for smart green connected society 2021',
        location: '',
        services: 'SPAST',
        year: '',
        src: 'Screenshot_2026-07-12_142257.png',
        color: '#dbeafe',
        url: '',
        categories: [],
    },
    {
        title: 'SRM PROJECT EXPO’21',
        location: '',
        services: 'SRM University ',
        year: '',
        src: 'Screenshot_2026-07-12_142422.png',
        color: '#dbeafe',
        url: '',
        categories: [],
    },
    {
        title: ' THINKTECH2K21',
        location: '',
        services: 'Don bosco college of engineering',
        year: '',
        src: 'Screenshot_2026-07-12_142646.png',
        color: '#dbeafe',
        url: '',
        categories: [],
    },
    {
        title: 'Training Program on “Incident Response System: Basic & Intermediate” ',
        location: '',
        services: 'National Institute of Disaster Management, Ministry of Home Affairs, Govt. of India ',
        year: '',
        src: 'Screenshot_2026-07-12_142914.png',
        color: '#dbeafe',
        url: '',
        categories: [],
    },
    {
        title: 'Consumer outreach program | Discussion of network usage and 5G with its efficiency',
        location: '',
        services: 'TRAI- Telecom Regulatory Authority of India, Govt. of India',
        year: '',
        src: 'Screenshot_2026-07-12_143106.png',
        color: '#dbeafe',
        url: '',
        categories: [],
    },
    {
        title: 'Webinar | Hybrid electric technology',
        location: '',
        services: 'Toyota Kirloskar Motor pvt.Ltd',
        year: '',
        src: 'Screenshot_2026-07-12_143455.png',
        color: '#dbeafe',
        url: '',
        categories: [],
    },
    {
        title: 'Pro MFG Plant Maintenance and Asset Management Summit  2021',
        location: '',
        services: 'Pro MFG Media',
        year: '',
        src: 'Screenshot_2026-07-12_143616.png',
        color: '#dbeafe',
        url: '',
        categories: [],
    },
    {
        title: 'Generative AI Leader',
        location: '',
        services: 'Google',
        year: '',
        src: 'Screenshot_2026-07-12_144203.png',
        color: '#dbeafe',
        url: '',
        categories: [],
    },
    {
        title: 'PMP | AI',
        location: '',
        services: 'Google',
        year: '',
        src: 'Gemini_Generated_Image_2fjvgu2fjvgu2fjv.png',
        color: '#dbeafe',
        url: '',
        categories: [],
    },
    {
        title: 'Product Manager | AI ',
        location: '',
        services: 'IBM ',
        year: '',
        src: 'Gemini_Generated_Image_2fjvgu2fjvgu2fjv.png',
        color: '#dbeafe',
        url: '',
        categories: [],
    },
    {
        title: 'Microsoft 365 | Generative AI',
        location: '',
        services: 'Microsoft ',
        year: '',
        src: 'Screenshot_2026-07-12_145319.png',
        color: '#dbeafe',
        url: '',
        categories: [],
    },
];

export const filters = [
    { key: 'all', label: 'All' },
    { key: 'cloud', label: 'Cloud' },
    { key: 'development', label: 'Development' },
    { key: 'devops', label: 'DevOps' },
] as const;

export type FilterKey = (typeof filters)[number]['key'];
