/**
 * The shelf.
 *
 * Four categories, taken from how the books are actually filed rather than
 * invented here. Covers live in /static/images/books as small webp
 * thumbnails — a picture of a jacket, never the book itself.
 *
 * `note` is what the book did, in two or three lines. Three of them —
 * Christensen, Grove and Miller — already have their say on /about; those
 * notes carry that voice across rather than writing a second opinion.
 */

export type BookCategory = 'Life' | 'Physics' | 'Product' | 'Self help';

export interface Book {
	slug: string;
	title: string;
	author: string;
	year?: string;
	category: BookCategory;
	/** Under /static/images/books/. */
	cover: string;
	/** True where the jacket is a typographic card, not a scan. */
	coverIsCard?: boolean;
	note: string;
	/**
	 * Ten things worth keeping, summarised rather than quoted — the ideas in
	 * my own words, not the author's sentences. Nothing here reproduces the
	 * book, which is the whole point of a shelf that carries no PDFs.
	 */
	takeaways: string[];
}

/**
 * Section order: how the shelves are meant to be walked, not how full they
 * are. Physics sits last — it is the one you arrive at rather than start on.
 */
export const categories: BookCategory[] = [
	'Life',
	'Product',
	'Self help',
	'Physics',
];

/** One line under each category heading, saying what the shelf is for. */
export const categoryBlurb: Record<BookCategory, string> = {
	Life: 'The Gītā and the commentaries around it — read slowly, and more than once.',
	Product:
		'How things get built, why good companies miss the turn, and who the work is actually for.',
	Physics: 'The large questions, written for people who are not physicists.',
	'Self help':
		'Habits, attention and nerve — the ones about getting out of your own way.',
};

export const books: Book[] = [
	// ── Life ──────────────────────────────────────────────────
	{
		slug: 'bhagavad-gita-as-it-is',
		title: 'Bhagavad-gītā As It Is',
		author: 'A. C. Bhaktivedanta Swami Prabhupāda',
		category: 'Life',
		cover: 'bhagavad-gita-as-it-is.webp',
		note: 'Seven hundred verses on duty, action and detachment, framed as a conversation on the morning of a battle nobody in it wants. This is the edition with the commentary I keep returning to, which argues rather than summarises.',
		takeaways: [
			'Do the work in front of you; the result was never the part you controlled.',
			'Acting without attachment to the reward is what keeps the act from owning you.',
			'Your own duty done imperfectly beats someone else’s done well.',
			'Grief for the body misreads what is actually being lost.',
			'Steadiness of mind is a practice, not a temperament you are born with.',
			'Doubt is answered by acting, not by deliberating longer.',
			'Everyone acts from their nature; suppressing it produces hypocrisy, not virtue.',
			'Equanimity in success and failure is the definition of yoga offered here.',
			'Knowledge, action and devotion are three routes up the same hill.',
			'The argument ends in surrender, which is presented as maturity rather than defeat.',
		],
	},
	{
		slug: 'autobiography-of-a-yogi',
		title: 'Autobiography of a Yogi',
		author: 'Paramahansa Yogananda',
		year: '1946',
		category: 'Life',
		cover: 'autobiography-of-a-yogi.webp',
		coverIsCard: true,
		note: 'Yogananda’s account of his own training, and the book that carried the Indian contemplative tradition to a great many readers outside it. Read as a life rather than as doctrine, it is mostly about persistence.',
		takeaways: [
			'Find the teacher before the technique; method without transmission goes stale.',
			'Discipline compounds quietly — the results arrive long after the work does.',
			'Rigour and devotion are not opposites; the author trained in both.',
			'Doubt is a stage to move through, not an enemy to defeat.',
			'The extraordinary episodes matter less than the ordinary daily sitting.',
			'Attention is the faculty being trained; everything else follows from it.',
			'Study widens the frame but never substitutes for practice.',
			'A lineage carries method that no book can fully write down.',
			'A life organised around one aim looks strange outside and coherent inside.',
			'The real subject of the book is persistence measured in decades.',
		],
	},
	{
		slug: 'science-of-self-realization',
		title: 'The Science of Self-Realization',
		author: 'A. C. Bhaktivedanta Swami Prabhupāda',
		year: '1977',
		category: 'Life',
		cover: 'science-of-self-realization.webp',
		note: 'Essays and interviews rather than scripture — the tradition put in conversation with journalists, scientists and sceptics. The most useful of these for seeing how an argument holds up outside its own vocabulary.',
		takeaways: [
			'A position is best tested outside its own vocabulary.',
			'The interview format exposes where an argument is strong and where it leans.',
			'Consciousness is treated as the datum, not as an output of matter.',
			'Material progress and human progress are separable, and often are separated.',
			'Practice is proposed as evidence you gather yourself rather than accept.',
			'A teacher’s job is to be questioned, not agreed with.',
			'Simple living is argued as a precondition for clear thinking.',
			'The book is most useful where it is challenged hardest.',
			'Answers are given in the questioner’s language, not the tradition’s.',
			'Scepticism is treated as respect, which is why the exchanges hold up.',
		],
	},
	{
		slug: 'perfect-questions-perfect-answers',
		title: 'Perfect Questions, Perfect Answers',
		author: 'A. C. Bhaktivedanta Swami Prabhupāda and Bob Cohen',
		year: '1977',
		category: 'Life',
		cover: 'perfect-questions-perfect-answers.webp',
		note: 'A Peace Corps worker in India asks the questions a newcomer would actually ask, in the order they would occur to them, and gets each one answered. The plainest entry point on this shelf.',
		takeaways: [
			'A beginner’s questions are usually the honest ones.',
			'Answering in order beats answering in depth when someone is new.',
			'Sincerity is treated as the qualification, not scholarship.',
			'Doubt voiced plainly gets a better answer than doubt kept polite.',
			'Practice is offered before philosophy, not after it.',
			'The exchange is a conversation, which is why it stays readable.',
			'Cultural distance is acknowledged rather than argued away.',
			'What you do daily matters more than what you have concluded.',
			'The teacher meets the questioner where the questioner is standing.',
			'A short book can carry a whole position if the questions are right.',
		],
	},
	{
		slug: 'life-comes-from-life',
		title: 'Life Comes from Life',
		author: 'A. C. Bhaktivedanta Swami Prabhupāda',
		category: 'Life',
		cover: 'life-comes-from-life.webp',
		note: 'Morning walks transcribed into a running argument with the scientific account of how life began. Worth reading for the shape of the disagreement, whichever side of it you end up on.',
		takeaways: [
			'A disagreement is clearer than an assertion — the format does the work.',
			'The question of how life begins is separated from how life develops.',
			'Origin claims and mechanism claims are not the same claim.',
			'Consciousness is proposed as irreducible rather than emergent.',
			'The argument is with a worldview, not with any particular experiment.',
			'Watch which side is answering the question actually asked.',
			'Confidence and evidence are two different quantities.',
			'Reading opposition carefully sharpens whichever side you end on.',
			'The walks format keeps the exchange concrete rather than abstract.',
			'Worth reading for the shape of the disagreement more than the verdict.',
		],
	},
	{
		slug: 'beyond-birth-and-death',
		title: 'Beyond Birth and Death',
		author: 'A. C. Bhaktivedanta Swami Prabhupāda',
		year: '1974',
		category: 'Life',
		cover: 'beyond-birth-and-death.webp',
		note: 'A short book on what the tradition holds survives the body, and why it treats that as a matter of fact rather than of comfort. Short enough to finish in a sitting, and difficult to put down again afterwards.',
		takeaways: [
			'The claim is framed as fact to be examined, not comfort to be accepted.',
			'Identity is placed in the observer, not in what is observed.',
			'Change of body is treated the way change of clothing is treated.',
			'Fear of death is read as a category error about what you are.',
			'The argument is short because it does not hedge.',
			'What you attend to during life is said to shape what follows it.',
			'Detachment is presented as clarity, not coldness.',
			'The book asks to be tested rather than believed.',
			'Brevity is the point: one claim, followed all the way down.',
			'It is harder to dismiss after reading than before.',
		],
	},
	{
		slug: 'path-of-perfection',
		title: 'The Path of Perfection',
		author: 'A. C. Bhaktivedanta Swami Prabhupāda',
		category: 'Life',
		cover: 'path-of-perfection.webp',
		note: 'The sixth chapter of the Gītā, opened out — yoga as a discipline of attention rather than of the body. Subtitled “yoga for the modern age”, and mostly about what modern attention has lost.',
		takeaways: [
			'Yoga here is a discipline of attention, not of the body.',
			'Posture is a means; concentration is the object.',
			'Regularity beats intensity — a little daily outlasts a lot occasionally.',
			'The mind is described as trainable, which is the whole premise.',
			'Withdrawal from distraction precedes any deeper practice.',
			'Moderation in food, sleep and work is treated as method, not virtue.',
			'The practice is measured in steadiness, not in experiences.',
			'Failure to sustain it is expected and planned for.',
			'The sixth chapter of the Gītā is enough material for a whole book.',
			'What modern attention has lost is the book’s real subject.',
		],
	},
	{
		slug: 'on-the-way-to-krsna',
		title: 'On the Way to Kṛṣṇa',
		author: 'A. C. Bhaktivedanta Swami Prabhupāda',
		year: '1973',
		category: 'Life',
		cover: 'on-the-way-to-krsna.webp',
		note: 'On happiness that does not depend on circumstances, and the practice the tradition proposes for reaching it. Read alongside the Gītā rather than before it.',
		takeaways: [
			'Happiness contingent on circumstances is not stability, it is timing.',
			'Pleasure and satisfaction are separated early and stay separated.',
			'A practice is proposed rather than a conclusion argued.',
			'Consistency matters more than intensity in anything devotional.',
			'The obstacles named are ordinary — distraction, habit, company.',
			'Company shapes practice more than resolve does.',
			'Doing precedes understanding here, deliberately.',
			'Small daily observance is treated as the whole of the method.',
			'Read alongside the Gītā rather than before it.',
			'The tone is encouraging where the other books are argumentative.',
		],
	},
	{
		slug: 'civilization-and-transcendence',
		title: 'Civilization and Transcendence',
		author: 'A. C. Bhaktivedanta Swami Prabhupāda',
		category: 'Life',
		cover: 'civilization-and-transcendence.webp',
		note: 'A conversation with a journalist about what a civilisation is for once it has met its material needs. The questions are sceptical, which is what makes it worth reading.',
		takeaways: [
			'What a civilisation is for, once its material needs are met.',
			'Progress measured only materially will report success while people worsen.',
			'The sceptical questions are what make the answers worth reading.',
			'Technology changes capability without changing purpose.',
			'A society’s aims are visible in what it teaches its young.',
			'Comfort and meaning are not the same currency.',
			'The interviewer’s doubts are left in, which is the book’s strength.',
			'Culture is treated as a claim about ends, not a set of customs.',
			'The critique lands hardest where it is most specific.',
			'A short exchange can hold a large question.',
		],
	},
	{
		slug: 'hare-krsna-challenge',
		title: 'The Hare Kṛṣṇa Challenge',
		author: 'A. C. Bhaktivedanta Swami Prabhupāda',
		category: 'Life',
		cover: 'hare-krsna-challenge.webp',
		note: 'Subtitled “exposing a misdirected civilization”. The most confrontational book on the shelf, and a fair test of how well the position holds when it stops being polite.',
		takeaways: [
			'The most confrontational book here, and a fair test of the position.',
			'An argument is best judged when it stops being polite.',
			'Modern civilisation is charged with optimising the wrong variable.',
			'Consumption is framed as a treadmill rather than a goal.',
			'The book asks what education is actually producing.',
			'Directness is a rhetorical choice, and it costs something.',
			'Disagreeing with it usefully requires reading it closely.',
			'The strongest passages are diagnostic rather than prescriptive.',
			'Being provoked is not the same as being wrong.',
			'Read it after the gentler books, not instead of them.',
		],
	},

	// ── Product ───────────────────────────────────────────────
	{
		slug: 'innovators-dilemma',
		title: 'The Innovator’s Dilemma',
		author: 'Clayton M. Christensen',
		year: '2000',
		category: 'Product',
		cover: 'innovators-dilemma.webp',
		note: 'Christensen explains why careful companies, doing everything right for their best customers, still get overtaken. I think about it whenever a roadmap starts to feel safe.',
		takeaways: [
			'Good management is what causes the failure, not bad management.',
			'Listening closely to your best customers is how you miss the next market.',
			'Disruptive technology arrives worse on the metrics that currently matter.',
			'Small emerging markets cannot solve a large company’s growth problem.',
			'Resource allocation follows margin, and margin follows the existing customer.',
			'Markets that do not exist yet cannot be analysed, only entered.',
			'Value networks decide what a company is able to see.',
			'A separate organisation is often the only way to pursue a low-margin bet.',
			'Technology usually overshoots what customers can absorb.',
			'When a roadmap starts to feel safe, that is the signal.',
		],
	},
	{
		slug: 'only-the-paranoid-survive',
		title: 'Only the Paranoid Survive',
		author: 'Andrew S. Grove',
		year: '1996',
		category: 'Product',
		cover: 'only-the-paranoid-survive.webp',
		coverIsCard: true,
		note: 'Grove named something I had already met: a strategic inflection point arrives quietly, and the 10X force behind it does not announce itself. A venture of mine that went nowhere taught me the rest.',
		takeaways: [
			'A strategic inflection point arrives quietly and is only obvious afterwards.',
			'A 10X change in any one force reshapes the whole business.',
			'Middle managers see the shift before executives do — listen downward.',
			'Debate the change loudly before committing, then commit completely.',
			'Data confirms an inflection point only after it is too late to act cheaply.',
			'The first version of the new strategy will be wrong; start anyway.',
			'Cassandras are useful precisely because they are uncomfortable.',
			'You cannot manage through a transition and reassure everyone at once.',
			'Clarity about what business you are now in is most of the work.',
			'Paranoia here means attention, not anxiety.',
		],
	},
	{
		slug: 'chip-war',
		title: 'Chip War',
		author: 'Chris Miller',
		category: 'Product',
		cover: 'chip-war.webp',
		note: 'A reminder that in deep tech the thing you are building is also the thing countries are counting. Read while working on wearable silicon, it changes what a supply chain feels like.',
		takeaways: [
			'Semiconductors are infrastructure, and infrastructure is geopolitics.',
			'The supply chain is a chokepoint map, not a logistics diagram.',
			'A handful of firms hold irreplaceable steps in the process.',
			'Manufacturing capability, once lost, takes decades to rebuild.',
			'Export controls are industrial policy conducted by other means.',
			'Moore’s law was as much an economic commitment as a technical one.',
			'Talent concentrates geographically and is slow to relocate.',
			'Fabs are capital bets placed years ahead of the demand they serve.',
			'What you build in deep tech is also what countries are counting.',
			'Technical decisions and national strategy are no longer separable.',
		],
	},
	{
		slug: 'apple-in-china',
		title: 'Apple in China',
		author: 'Patrick McGee',
		category: 'Product',
		cover: 'apple-in-china.webp',
		note: 'How one company’s manufacturing decisions built another country’s industrial capability. The counterpart to Chip War — the same story told from inside a product line rather than from inside a policy.',
		takeaways: [
			'Supplier development transfers capability, not just orders.',
			'Optimising a supply chain can build a competitor’s industrial base.',
			'Scale creates dependency in both directions at once.',
			'Manufacturing expertise migrates toward wherever the volume is.',
			'Concentration is efficient until the moment it is exposed.',
			'Corporate decisions accumulate into industrial policy nobody voted for.',
			'Diversifying a supply chain is a decade of work, not a quarter of it.',
			'The counterpart to Chip War, told from inside a product line.',
			'Leverage looks different depending on which end of the contract you hold.',
			'Cost, speed and resilience have never been simultaneously optimisable.',
		],
	},
	{
		slug: 'steve-jobs',
		title: 'Steve Jobs',
		author: 'Walter Isaacson',
		year: '2011',
		category: 'Product',
		cover: 'steve-jobs.webp',
		note: 'The life of the person whose instinct I recognised early: reading what people would want before they could say it. It is also a long argument for taste as a discipline rather than a gift.',
		takeaways: [
			'Taste is a discipline that can be practised, not a gift you are issued.',
			'Reading what people want before they can articulate it is a learnable habit.',
			'Integrating hardware and software buys coherence at the cost of flexibility.',
			'Saying no to good ideas is what protects the great ones.',
			'Simplicity is the last step of a long process, not the first.',
			'Small teams of excellent people outrun large teams of adequate ones.',
			'Craft in the parts nobody sees still shows up in the parts they do.',
			'Focus means a short product line, deliberately.',
			'The difficult behaviour is documented, not excused.',
			'Conviction and evidence are different things; the book shows both costs.',
		],
	},
	{
		slug: 'inspired',
		title: 'Inspired',
		author: 'Marty Cagan',
		category: 'Product',
		cover: 'inspired.webp',
		note: 'The clearest account of what a product manager is actually for — not writing specifications, but making sure the right thing gets built. The book to hand someone stepping into the role.',
		takeaways: [
			'A product manager is accountable for value and viability, not for specs.',
			'Discovery and delivery are separate activities with separate risks.',
			'Test the riskiest assumption first, not the easiest one.',
			'Empowered teams are given problems; feature teams are given solutions.',
			'A roadmap of dates is a list of outputs, not of outcomes.',
			'Engineers belong in discovery, not just at the end of it.',
			'Prototypes are for learning; the cheapest one that answers the question wins.',
			'Most ideas fail, so the loop matters more than any single bet.',
			'The strongest product decisions come from direct customer contact.',
			'Vision persuades; a backlog does not.',
		],
	},
	{
		slug: 'zero-to-one',
		title: 'Zero to One',
		author: 'Peter Thiel with Blake Masters',
		category: 'Product',
		cover: 'zero-to-one.webp',
		note: 'An argument for building something genuinely new rather than a better copy of something that exists. More useful as a test to run against your own idea than as a playbook to follow.',
		takeaways: [
			'Copying what works takes the world from one to n; new things go zero to one.',
			'Competition erodes margin — monopoly on something genuinely new preserves it.',
			'Start by dominating a small market you can actually own.',
			'Ask what important truth very few people agree with you on.',
			'Distribution is a product decision, not a marketing afterthought.',
			'Returns are power-law distributed, so concentration beats diversification.',
			'A definite view of the future beats an indefinite optimism about it.',
			'Technology compounds; globalisation only copies.',
			'The last mover in a category often takes the value.',
			'Use it as a test against your own idea, not as a playbook.',
		],
	},
	{
		slug: 'managers-handbook',
		title: 'HBR Manager’s Handbook',
		author: 'Harvard Business Review',
		category: 'Product',
		cover: 'managers-handbook.webp',
		note: 'A reference rather than a read: seventeen skills, each short enough to look up on the day it is needed. It stays within reach for exactly that reason.',
		takeaways: [
			'A reference to consult on the day, not a book to read through.',
			'Delegation is a design problem: decide the outcome, not the method.',
			'Feedback is most useful when it is specific, timely and quiet.',
			'Meetings need a decision owner or they become status theatre.',
			'Managing up is a skill, not a character flaw.',
			'Hiring slowly is cheaper than managing a mismatch.',
			'Difficult conversations get harder the longer they are deferred.',
			'Priorities that are not written down are not priorities.',
			'Development conversations are separate from performance reviews.',
			'Consistency of process is what makes fairness legible to a team.',
		],
	},

	// ── Physics ───────────────────────────────────────────────
	{
		slug: 'a-brief-history-of-time',
		title: 'A Brief History of Time',
		author: 'Stephen Hawking',
		category: 'Physics',
		cover: 'a-brief-history-of-time.webp',
		note: 'The book that made the very large feel discussable. It set a standard I still hold explanations to: if a thing cannot be said plainly, it is probably not yet understood.',
		takeaways: [
			'If it cannot be said plainly, it is probably not yet understood.',
			'Space and time are participants in physics, not the stage it happens on.',
			'The universe has a history, and that history has a beginning.',
			'A black hole is defined by a boundary, not by an object.',
			'Black holes radiate, which ties gravity to thermodynamics.',
			'The arrow of time is a statement about entropy, not about clocks.',
			'A good theory is one that could be shown to be wrong.',
			'Quantum mechanics and general relativity are not yet on speaking terms.',
			'Asking what came before may be the wrong shape of question.',
			'Analogy carries a lay reader further than mathematics does.',
		],
	},
	{
		slug: 'universe-in-a-nutshell',
		title: 'The Universe in a Nutshell',
		author: 'Stephen Hawking',
		year: '2001',
		category: 'Physics',
		cover: 'universe-in-a-nutshell.webp',
		note: 'The sequel, and the more visual of the two. Where the first book argues in sequence, this one shows — and is the better of them to return to rather than to start with.',
		takeaways: [
			'The sequel shows where the first book argued.',
			'Diagrams can carry an idea that a paragraph cannot.',
			'Branes and extra dimensions are presented as candidates, not conclusions.',
			'Different theories can describe the same reality equally well.',
			'The holographic idea says information may live on a boundary.',
			'Time behaves differently near mass, and that is measurable.',
			'Prediction has limits that are structural, not technical.',
			'The book is better to return to than to start with.',
			'Speculation is labelled as speculation throughout.',
			'Physics is shown as unfinished, which is the honest position.',
		],
	},
	{
		slug: 'the-grand-design',
		title: 'The Grand Design',
		author: 'Stephen Hawking and Leonard Mlodinow',
		category: 'Physics',
		cover: 'the-grand-design.webp',
		note: 'On whether the universe needs a designer, and on what a physical theory is entitled to claim about reality. The most philosophical of the Hawking shelf, and the most arguable.',
		takeaways: [
			'A theory is a model, and models are judged by usefulness.',
			'Model-dependent realism sidesteps asking which description is the real one.',
			'Laws of nature may not require a lawgiver.',
			'The fine-tuning argument has a multiverse answer, whether or not you like it.',
			'Quantum history is summed over, not traced.',
			'Philosophy is declared dead, which is itself a philosophical claim.',
			'The most arguable book on the shelf, and the most worth arguing with.',
			'M-theory is presented as a family of theories, not one.',
			'The universe can be described without invoking a beginning cause.',
			'Confidence in the conclusion outruns the evidence, and that is visible.',
		],
	},
	{
		slug: 'brief-answers-to-the-big-questions',
		title: 'Brief Answers to the Big Questions',
		author: 'Stephen Hawking',
		year: '2018',
		category: 'Physics',
		cover: 'brief-answers-to-the-big-questions.webp',
		note: 'The last one, assembled from his own notes: ten questions, answered directly and without hedging. It reads like someone deciding what was still worth saying while there was time to say it.',
		takeaways: [
			'Ten questions, answered directly and without hedging.',
			'The tone is of someone deciding what was still worth saying.',
			'Science is defended as a public good, not a specialist hobby.',
			'Artificial intelligence is treated as the largest near-term question.',
			'Space settlement is argued as insurance rather than adventure.',
			'Optimism and warning are held together rather than traded off.',
			'Complex ideas are compressed without being falsified.',
			'Curiosity is presented as the thing worth protecting in education.',
			'The personal passages give the physics its weight.',
			'A good last book: short, clear, and unafraid of the questions.',
		],
	},
	{
		slug: 'theory-of-everything',
		title: 'The Theory of Everything',
		author: 'Stephen Hawking',
		category: 'Physics',
		cover: 'theory-of-everything.webp',
		note: 'The lectures underneath the popular books — the origin and fate of the universe, taken in order. Closer to hearing him teach than to reading him write.',
		takeaways: [
			'The lectures underneath the popular books, taken in order.',
			'Cosmology is built up historically, which makes it easier to follow.',
			'The expanding universe implies a beginning, and that took time to accept.',
			'Black hole thermodynamics links information, entropy and gravity.',
			'A no-boundary universe removes the need for an initial edge.',
			'Unification is described as a programme, not an achievement.',
			'Hearing him teach is different from reading him write.',
			'Repetition across lectures is a feature for a lay reader.',
			'The limits of the theories are stated as plainly as the theories.',
			'Short enough to read in a sitting, dense enough to reread.',
		],
	},
	{
		slug: 'parallel-worlds',
		title: 'Parallel Worlds',
		author: 'Michio Kaku',
		category: 'Physics',
		cover: 'parallel-worlds.webp',
		note: 'Kaku takes the same territory and pushes further out, into higher dimensions and the multiverse. Speculative where Hawking stays careful, which is its own kind of useful.',
		takeaways: [
			'The same territory as Hawking, pushed considerably further out.',
			'Higher dimensions are introduced as mathematics before as spectacle.',
			'Multiverse models are catalogued rather than endorsed.',
			'String theory is presented as promise, not as settled result.',
			'Cosmology and particle physics meet at the very early universe.',
			'The far future of the universe is a physics question, not a poetic one.',
			'Speculation is enjoyable and should still be labelled.',
			'Popular science can be generous with ideas and thin on caveats.',
			'Read after Hawking, as the counterweight rather than the introduction.',
			'Ambition in a science book is worth something on its own.',
		],
	},
	{
		slug: 'relativity',
		title: 'Relativity',
		author: 'Albert Einstein',
		year: '1916',
		category: 'Physics',
		cover: 'relativity.webp',
		coverIsCard: true,
		note: 'Einstein explaining relativity himself, for readers without the mathematics. Worth it for the tone as much as the physics — the person who found it, explaining it without hurry.',
		takeaways: [
			'The person who found it, explaining it without hurry.',
			'Simultaneity depends on the observer, and that is the hinge.',
			'The speed of light being constant forces everything else to give.',
			'Special relativity comes from two postulates and careful bookkeeping.',
			'Thought experiments do real work, not just illustrative work.',
			'Gravity and acceleration are locally indistinguishable.',
			'Mass tells space how to curve; curvature tells mass how to move.',
			'The theory was written down with testable predictions attached.',
			'Written for readers without the mathematics, and it holds.',
			'Worth it for the tone as much as for the physics.',
		],
	},

	// ── Self help ─────────────────────────────────────────────
	{
		slug: 'subtle-art',
		title: 'The Subtle Art of Not Giving a F*ck',
		author: 'Mark Manson',
		category: 'Self help',
		cover: 'subtle-art.webp',
		note: 'The argument is that attention is the scarce resource, not positivity: you are going to care about something, so choose it on purpose. Blunter than it needs to be, and right about the central point.',
		takeaways: [
			'Attention is the scarce resource; positivity is not.',
			'You will care about something, so choose it deliberately.',
			'Problems do not end — you trade them for better ones.',
			'Choosing what to struggle for matters more than choosing what to want.',
			'Taking responsibility is separable from being at fault.',
			'Certainty is comfortable and usually a sign you have stopped looking.',
			'Values chosen badly produce misery no amount of effort fixes.',
			'Rejection of some things is what makes commitment to others mean anything.',
			'Entitlement and self-loathing are the same error in different directions.',
			'Blunter than it needs to be, and right about the central point.',
		],
	},
	{
		slug: 'atomic-habits',
		title: 'Atomic Habits',
		author: 'James Clear',
		year: '2018',
		category: 'Self help',
		cover: 'atomic-habits.webp',
		note: 'The mechanics of habit, taken apart into cue, craving, response and reward, and then put back together as something you can design. The most practical book on this shelf, and the least interested in motivation.',
		takeaways: [
			'You do not rise to your goals; you fall to your systems.',
			'Habits are the compound interest of self-improvement.',
			'Make it obvious, attractive, easy and satisfying — and invert all four to break one.',
			'Change the identity first: decide who you are, and the behaviour follows.',
			'Environment beats willpower, so design the room rather than the resolve.',
			'Reduce the friction on what you want and add friction to what you do not.',
			'Two minutes is enough to start; the point is showing up, not the volume.',
			'Never miss twice — one lapse is an accident, two is the new pattern.',
			'Measure what you want to move, but do not mistake the measure for the goal.',
			'Progress is invisible until it is obvious, which is why most people stop early.',
		],
	},
	{
		slug: 'power-of-your-subconscious-mind',
		title: 'The Power of Your Subconscious Mind',
		author: 'Joseph Murphy',
		year: '1963',
		category: 'Self help',
		cover: 'power-of-your-subconscious-mind.webp',
		note: 'An argument that what you repeat to yourself gets treated as an instruction. Dated in its examples and overreaching in its claims, but the core point about attention and repetition has aged better than the packaging.',
		takeaways: [
			'What you repeat to yourself is eventually treated as an instruction.',
			'The subconscious does not argue with a premise, it acts on it.',
			'Anxiety rehearses an outcome as thoroughly as preparation does.',
			'Belief and expectation shape what you notice and therefore what you find.',
			'Repetition is the mechanism; sincerity is what makes repetition stick.',
			'The state you fall asleep in is the one that gets the most rehearsal.',
			'Imagination directed deliberately is more useful than imagination left running.',
			'Resentment is a loop you maintain at your own cost.',
			'Read the claims as psychology rather than as physics.',
			'The practical residue is simple: mind what you keep telling yourself.',
		],
	},
	{
		slug: '48-laws-of-power',
		title: 'The 48 Laws of Power',
		author: 'Robert Greene',
		year: '1998',
		category: 'Self help',
		cover: '48-laws-of-power.webp',
		note: 'A catalogue of how power has actually been taken and held, illustrated from history and stated without apology. Best read as a description of behaviour you will meet rather than a set of instructions to follow.',
		takeaways: [
			'A description of how power operates, not a recommendation for how to live.',
			'Never outshine the person you depend on.',
			'Reputation is built slowly and spent instantly; guard it accordingly.',
			'Say less than necessary — ambiguity leaves room you can use.',
			'Actions persuade; arguments create opponents.',
			'Court attention, but never let anyone see the effort behind it.',
			'Make people come to you by controlling the terms of the meeting.',
			'Plan to the end, because most failures are failures of the last mile.',
			'Recognising these moves in others is the defensive half of the book.',
			'The amorality is deliberate and is the main thing to read critically.',
		],
	},
	{
		slug: 'how-to-win-friends',
		title: 'How to Win Friends and Influence People',
		author: 'Dale Carnegie',
		year: '1936',
		category: 'Self help',
		cover: 'how-to-win-friends.webp',
		note: 'Nearly a century old and still the clearest short book on paying attention to other people. Almost all of it reduces to taking a genuine interest and saying so, which is easier to agree with than to practise.',
		takeaways: [
			'Criticism puts people on the defensive and rarely changes the behaviour.',
			'Become genuinely interested in other people and most of the rest follows.',
			'A person’s name is the word they most want to hear said correctly.',
			'Listen more than you talk, and ask about what they care about.',
			'Let the other person do most of the talking about their own idea.',
			'Admit your mistakes quickly and completely, before they are pointed out.',
			'Begin with what you agree on rather than what you dispute.',
			'Give the other person credit and let the idea be theirs.',
			'Appreciation is specific; flattery is generic — the difference is audible.',
			'The techniques only work when the interest behind them is real.',
		],
	},
	{
		slug: 'stop-worrying-start-living',
		title: 'How to Stop Worrying and Start Living',
		author: 'Dale Carnegie',
		year: '1948',
		category: 'Self help',
		cover: 'stop-worrying-start-living.webp',
		note: 'The companion volume, and the more useful of the two. Its method is unglamorous: define the worry precisely, decide what you would actually do, then get on with the doing.',
		takeaways: [
			'Live in day-tight compartments — today is the only unit you can act in.',
			'Ask what the worst outcome actually is, accept it, then work to improve on it.',
			'Worry is a decision deferred; making the decision usually ends it.',
			'Get the facts before you get an opinion about your own situation.',
			'Keep busy — an occupied mind has less room for rehearsal.',
			'Do not agitate over things too small to be worth the cost.',
			'Play the odds: most feared outcomes are statistically rare.',
			'Accept the inevitable rather than spending on it repeatedly.',
			'Put a stop-loss order on a worry, the way you would on a trade.',
			'Act your way into a feeling rather than waiting to feel your way into action.',
		],
	},
	{
		slug: 'ikigai',
		title: 'Ikigai',
		author: 'Héctor García and Francesc Miralles',
		year: '2016',
		category: 'Self help',
		cover: 'ikigai.webp',
		note: 'A short book on why people in Okinawa live long and stay engaged. Lighter than its reputation, and most useful for one idea: purpose is a daily practice, not a destination you arrive at.',
		takeaways: [
			'Purpose is something practised daily, not discovered once.',
			'A reason to get up in the morning is the whole definition.',
			'Retirement from work is not retirement from usefulness.',
			'Community and routine do more for longevity than intensity does.',
			'Eat until roughly eighty per cent full, and stop there.',
			'Constant gentle movement beats occasional hard exercise.',
			'Flow — absorption in a task — is where the satisfaction actually sits.',
			'Small rituals hold a day together better than large plans.',
			'Slowness is treated as a method rather than a lack of ambition.',
			'The evidence is thin in places; the practices are still worth trying.',
		],
	},
	{
		slug: 'wings-of-fire',
		title: 'Wings of Fire',
		author: 'A. P. J. Abdul Kalam with Arun Tiwari',
		year: '1999',
		category: 'Self help',
		cover: 'wings-of-fire.webp',
		note: 'Kalam’s account of getting from Rameswaram to India’s missile programme, written without self-congratulation. The engineering chapters are the good ones: what it takes to build hard things inside a system that is learning as it goes.',
		takeaways: [
			'Where you start does not determine what you can build.',
			'Failure is reported honestly here, including the launches that did not work.',
			'A leader’s job is to absorb blame and distribute credit.',
			'Large engineering programmes are held together by people, not by plans.',
			'Teachers change trajectories, and he names every one of his.',
			'Self-reliance was a national argument before it was a technical one.',
			'Dreams that keep you awake are the ones worth working on.',
			'Discipline and simplicity are treated as the same habit.',
			'Science and faith are held together without apology or conflict.',
			'The tone is the lesson: ambition without self-importance.',
		],
	},
	{
		slug: 'dont-believe-everything-you-think',
		title: 'Don’t Believe Everything You Think',
		author: 'Joseph Nguyen',
		year: '2022',
		category: 'Self help',
		cover: 'dont-believe-everything-you-think.webp',
		note: 'A very short book with one argument: thinking about a feeling is what sustains it. Repetitive by design, and the repetition is the method rather than a flaw.',
		takeaways: [
			'Thoughts arrive on their own; thinking about them is the part you add.',
			'Suffering is generated by the commentary, not by the event.',
			'You are not obliged to believe a thought just because you had it.',
			'Feelings pass quickly unless thinking keeps them running.',
			'Peace is the default state, not an achievement to be earned.',
			'Trying to control thought is itself more thought.',
			'Clarity tends to arrive in the gaps, not during the effort.',
			'Awareness of a pattern is most of what breaks it.',
			'The book is repetitive on purpose — it is a practice, not an argument.',
			'Short enough to reread whenever the loop starts again.',
		],
	},
	{
		slug: 'mindset',
		title: 'Mindset',
		author: 'Carol S. Dweck',
		year: '2006',
		category: 'Self help',
		cover: 'mindset.webp',
		note: 'The research behind a distinction that has been flattened by repetition: whether you treat ability as fixed or as developable changes what you attempt. Better than its slogan, and more careful about the limits.',
		takeaways: [
			'Treating ability as fixed or as developable changes what you attempt.',
			'A fixed mindset makes effort feel like evidence of inadequacy.',
			'Praise the process, not the person — praising talent makes it fragile.',
			'Failure becomes information rather than identity in a growth mindset.',
			'Nobody holds one mindset everywhere; it varies by domain and by day.',
			'Challenge is sought when improvement seems possible and avoided when it does not.',
			'Organisations have mindsets too, and they show up in how they hire.',
			'“Not yet” is a more useful verdict than “failed”.',
			'The idea is often cited more loosely than the research supports.',
			'The distinction is most useful applied to yourself, not to other people.',
		],
	},
	{
		slug: 'think-and-grow-rich',
		title: 'Think and Grow Rich',
		author: 'Napoleon Hill',
		year: '1937',
		category: 'Self help',
		cover: 'think-and-grow-rich.webp',
		note: 'The ancestor of most of this shelf. The evidence is anecdotal and some of it is invented, but its emphasis on definiteness of purpose and persistence explains why it has outlasted almost everything written since.',
		takeaways: [
			'A vague aim produces vague effort; definiteness of purpose comes first.',
			'Desire has to be specific enough to be measured against.',
			'Persistence is described as a habit that can be built deliberately.',
			'A mastermind group — deliberate peers — outperforms working alone.',
			'Decisions made slowly and changed quickly are the pattern to avoid.',
			'Plan, fail, replace the plan; do not replace the objective.',
			'Fear is catalogued specifically so it can be addressed specifically.',
			'Specialised knowledge beats general knowledge for a defined aim.',
			'Much of the evidence is anecdotal and some of it is fabricated.',
			'Read it as the origin of a genre, and discount accordingly.',
		],
	},
	{
		slug: 'the-alchemist',
		title: 'The Alchemist',
		author: 'Paulo Coelho',
		year: '1988',
		category: 'Self help',
		cover: 'the-alchemist.webp',
		note: 'A fable about leaving to find something and learning where it was. Simple enough to be dismissed and durable enough to keep being read; it works better as a mood than as a philosophy.',
		takeaways: [
			'The journey teaches what the destination cannot.',
			'Fear of loss is a heavier tax than loss itself.',
			'Omens are a way of describing attention, not prophecy.',
			'What you are looking for is often near where you started.',
			'Beginner’s luck gets you moving; persistence gets you there.',
			'Every setback is presented as tuition rather than as a verdict.',
			'Listening to your own restlessness is treated as data.',
			'The simplicity is the form, and it is easy to mistake for shallowness.',
			'Comfort is the most common reason a personal legend is abandoned.',
			'A fable, so read it for the mood rather than the argument.',
		],
	},
];

export const bookBySlug = new Map(books.map((b) => [b.slug, b]));

export const booksIn = (category: BookCategory): Book[] =>
	books.filter((b) => b.category === category);
