/**
 * The shelf.
 *
 * Four categories, taken from how the books are actually filed rather than
 * invented here. Covers live in /static/images/books as small webp
 * thumbnails — a picture of a jacket, never the book itself.
 *
 * `note` is what the book did, in two or three lines. Three of them —
 * Christensen, Grove and Miller — already have their say on /about; those
 * notes carry that voice across rather than writing a second opinion.
 */

export type BookCategory = 'Life' | 'Physics' | 'Product' | 'Self help';

export interface Book {
	slug: string;
	title: string;
	author: string;
	year?: string;
	category: BookCategory;
	/** Under /static/images/books/. */
	cover: string;
	/** True where the jacket is a typographic card, not a scan. */
	coverIsCard?: boolean;
	note: string;
	/**
	 * Ten things worth keeping, summarised rather than quoted — the ideas in
	 * my own words, not the author's sentences. Nothing here reproduces the
	 * book, which is the whole point of a shelf that carries no PDFs.
	 */
	takeaways: string[];
}

/**
 * Section order: how the shelves are meant to be walked, not how full they
 * are. Physics sits last — it is the one you arrive at rather than start on.
 */
export const categories: BookCategory[] = [
	'Life',
	'Product',
	'Self help',
	'Physics',
];

/** One line under each category heading, saying what the shelf is for. */
export const categoryBlurb: Record<BookCategory, string> = {
	Life: 'The Gītā and the commentaries around it — read slowly, and more than once.',
	Product:
		'How things get built, why good companies miss the turn, and who the work is actually for.',
	Physics: 'The large questions, written for people who are not physicists.',
	'Self help':
		'Habits, attention and nerve — the ones about getting out of your own way.',
};

export const books: Book[] = [
	// ── Life ──────────────────────────────────────────────────
	{
		slug: 'bhagavad-gita-as-it-is',
		title: 'Bhagavad-gītā As It Is',
		author: 'A. C. Bhaktivedanta Swami Prabhupāda',
		category: 'Life',
		cover: 'bhagavad-gita-as-it-is.webp',
		note: 'Seven hundred verses on duty, action and detachment, framed as a conversation on the morning of a battle nobody in it wants. This is the edition with the commentary I keep returning to, which argues rather than summarises.',
		takeaways: [
			'Do the work in front of you; the result was never the part you controlled.',
			'Acting without attachment to the reward is what keeps the act from owning you.',
			'Your own duty done imperfectly beats someone else’s done well.',
			'Grief for the body misreads what is actually being lost.',
			'Steadiness of mind is a practice, not a temperament you are born with.',
			'Doubt is answered by acting, not by deliberating longer.',
			'Everyone acts from their nature; suppressing it produces hypocrisy, not virtue.',
			'Equanimity in success and failure is the definition of yoga offered here.',
			'Knowledge, action and devotion are three routes up the same hill.',
			'The argument ends in surrender, which is presented as maturity rather than defeat.',
		],
	},
	{
		slug: 'autobiography-of-a-yogi',
		title: 'Autobiography of a Yogi',
		author: 'Paramahansa Yogananda',
		year: '1946',
		category: 'Life',
		cover: 'autobiography-of-a-yogi.webp',
		coverIsCard: true,
		note: 'Yogananda’s account of his own training, and the book that carried the Indian contemplative tradition to a great many readers outside it. Read as a life rather than as doctrine, it is mostly about persistence.',
		takeaways: [
			'Find the teacher before the technique; method without transmission goes stale.',
			'Discipline compounds quietly — the results arrive long after the work does.',
			'Rigour and devotion are not opposites; the author trained in both.',
			'Doubt is a stage to move through, not an enemy to defeat.',
			'The extraordinary episodes matter less than the ordinary daily sitting.',
			'Attention is the faculty being trained; everything else follows from it.',
			'Study widens the frame but never substitutes for practice.',
			'A lineage carries method that no book can fully write down.',
			'A life organised around one aim looks strange outside and coherent inside.',
			'The real subject of the book is persistence measured in decades.',
		],
	},
	{
		slug: 'science-of-self-realization',
		title: 'The Science of Self-Realization',
		author: 'A. C. Bhaktivedanta Swami Prabhupāda',
		year: '1977',
		category: 'Life',
		cover: 'science-of-self-realization.webp',
		note: 'Essays and interviews rather than scripture — the tradition put in conversation with journalists, scientists and sceptics. The most useful of these for seeing how an argument holds up outside its own vocabulary.',
		takeaways: [
			'A position is best tested outside its own vocabulary.',
			'The interview format exposes where an argument is strong and where it leans.',
			'Consciousness is treated as the datum, not as an output of matter.',
			'Material progress and human progress are separable, and often are separated.',
			'Practice is proposed as evidence you gather yourself rather than accept.',
			'A teacher’s job is to be questioned, not agreed with.',
			'Simple living is argued as a precondition for clear thinking.',
			'The book is most useful where it is challenged hardest.',
			'Answers are given in the questioner’s language, not the tradition’s.',
			'Scepticism is treated as respect, which is why the exchanges hold up.',
		],
	},
	{
		slug: 'perfect-questions-perfect-answers',
		title: 'Perfect Questions, Perfect Answers',
		author: 'A. C. Bhaktivedanta Swami Prabhupāda and Bob Cohen',
		year: '1977',
		category: 'Life',
		cover: 'perfect-questions-perfect-answers.webp',
		note: 'A Peace Corps worker in India asks the questions a newcomer would actually ask, in the order they would occur to them, and gets each one answered. The plainest entry point on this shelf.',
		takeaways: [
			'A beginner’s questions are usually the honest ones.',
			'Answering in order beats answering in depth when someone is new.',
			'Sincerity is treated as the qualification, not scholarship.',
			'Doubt voiced plainly gets a better answer than doubt kept polite.',
			'Practice is offered before philosophy, not after it.',
			'The exchange is a conversation, which is why it stays readable.',
			'Cultural distance is acknowledged rather than argued away.',
			'What you do daily matters more than what you have concluded.',
			'The teacher meets the questioner where the questioner is standing.',
			'A short book can carry a whole position if the questions are right.',
		],
	},
	{
		slug: 'life-comes-from-life',
		title: 'Life Comes from Life',
		author: 'A. C. Bhaktivedanta Swami Prabhupāda',
		category: 'Life',
		cover: 'life-comes-from-life.webp',
		note: 'Morning walks transcribed into a running argument with the scientific account of how life began. Worth reading for the shape of the disagreement, whichever side of it you end up on.',
		takeaways: [
			'A disagreement is clearer than an assertion — the format does the work.',
			'The question of how life begins is separated from how life develops.',
			'Origin claims and mechanism claims are not the same claim.',
			'Consciousness is proposed as irreducible rather than emergent.',
			'The argument is with a worldview, not with any particular experiment.',
			'Watch which side is answering the question actually asked.',
			'Confidence and evidence are two different quantities.',
			'Reading opposition carefully sharpens whichever side you end on.',
			'The walks format keeps the exchange concrete rather than abstract.',
			'Worth reading for the shape of the disagreement more than the verdict.',
		],
	},
	{
		slug: 'beyond-birth-and-death',
		title: 'Beyond Birth and Death',
		author: 'A. C. Bhaktivedanta Swami Prabhupāda',
		year: '1974',
		category: 'Life',
		cover: 'beyond-birth-and-death.webp',
		note: 'A short book on what the tradition holds survives the body, and why it treats that as a matter of fact rather than of comfort. Short enough to finish in a sitting, and difficult to put down again afterwards.',
		takeaways: [
			'The claim is framed as fact to be examined, not comfort to be accepted.',
			'Identity is placed in the observer, not in what is observed.',
			'Change of body is treated the way change of clothing is treated.',
			'Fear of death is read as a category error about what you are.',
			'The argument is short because it does not hedge.',
			'What you attend to during life is said to shape what follows it.',
			'Detachment is presented as clarity, not coldness.',
			'The book asks to be tested rather than believed.',
			'Brevity is the point: one claim, followed all the way down.',
			'It is harder to dismiss after reading than before.',
		],
	},
	{
		slug: 'path-of-perfection',
		title: 'The Path of Perfection',
		author: 'A. C. Bhaktivedanta Swami Prabhupāda',
		category: 'Life',
		cover: 'path-of-perfection.webp',
		note: 'The sixth chapter of the Gītā, opened out — yoga as a discipline of attention rather than of the body. Subtitled “yoga for the modern age”, and mostly about what modern attention has lost.',
		takeaways: [
			'Yoga here is a discipline of attention, not of the body.',
			'Posture is a means; concentration is the object.',
			'Regularity beats intensity — a little daily outlasts a lot occasionally.',
			'The mind is described as trainable, which is the whole premise.',
			'Withdrawal from distraction precedes any deeper practice.',
			'Moderation in food, sleep and work is treated as method, not virtue.',
			'The practice is measured in steadiness, not in experiences.',
			'Failure to sustain it is expected and planned for.',
			'The sixth chapter of the Gītā is enough material for a whole book.',
			'What modern attention has lost is the book’s real subject.',
		],
	},
	{
		slug: 'on-the-way-to-krsna',
		title: 'On the Way to Kṛṣṇa',
		author: 'A. C. Bhaktivedanta Swami Prabhupāda',
		year: '1973',
		category: 'Life',
		cover: 'on-the-way-to-krsna.webp',
		note: 'On happiness that does not depend on circumstances, and the practice the tradition proposes for reaching it. Read alongside the Gītā rather than before it.',
		takeaways: [
			'Happiness contingent on circumstances is not stability, it is timing.',
			'Pleasure and satisfaction are separated early and stay separated.',
			'A practice is proposed rather than a conclusion argued.',
			'Consistency matters more than intensity in anything devotional.',
			'The obstacles named are ordinary — distraction, habit, company.',
			'Company shapes practice more than resolve does.',
			'Doing precedes understanding here, deliberately.',
			'Small daily observance is treated as the whole of the method.',
			'Read alongside the Gītā rather than before it.',
			'The tone is encouraging where the other books are argumentative.',
		],
	},
	{
		slug: 'civilization-and-transcendence',
		title: 'Civilization and Transcendence',
		author: 'A. C. Bhaktivedanta Swami Prabhupāda',
		category: 'Life',
		cover: 'civilization-and-transcendence.webp',
		note: 'A conversation with a journalist about what a civilisation is for once it has met its material needs. The questions are sceptical, which is what makes it worth reading.',
		takeaways: [
			'What a civilisation is for, once its material needs are met.',
			'Progress measured only materially will report success while people worsen.',
			'The sceptical questions are what make the answers worth reading.',
			'Technology changes capability without changing purpose.',
			'A society’s aims are visible in what it teaches its young.',
			'Comfort and meaning are not the same currency.',
			'The interviewer’s doubts are left in, which is the book’s strength.',
			'Culture is treated as a claim about ends, not a set of customs.',
			'The critique lands hardest where it is most specific.',
			'A short exchange can hold a large question.',
		],
	},
	{
		slug: 'hare-krsna-challenge',
		title: 'The Hare Kṛṣṇa Challenge',
		author: 'A. C. Bhaktivedanta Swami Prabhupāda',
		category: 'Life',
		cover: 'hare-krsna-challenge.webp',
		note: 'Subtitled “exposing a misdirected civilization”. The most confrontational book on the shelf, and a fair test of how well the position holds when it stops being polite.',
		takeaways: [
			'The most confrontational book here, and a fair test of the position.',
			'An argument is best judged when it stops being polite.',
			'Modern civilisation is charged with optimising the wrong variable.',
			'Consumption is framed as a treadmill rather than a goal.',
			'The book asks what education is actually producing.',
			'Directness is a rhetorical choice, and it costs something.',
			'Disagreeing with it usefully requires reading it closely.',
			'The strongest passages are diagnostic rather than prescriptive.',
			'Being provoked is not the same as being wrong.',
			'Read it after the gentler books, not instead of them.',
		],
	},
	{
		slug: 'sing-dance-and-lead',
		title: 'Sing, Dance and Lead',
		author: 'Hindol Sengupta',
		year: '2025',
		category: 'Life',
		cover: 'sing-dance-and-lead.webp',
		note: 'Subtitled “leadership lessons from the teachings of Srila Prabhupada”. A historian reads the founding of a global movement — begun at sixty-nine, with almost nothing, and built in eleven years — as a case study in leadership by service. The one book on this shelf written for the office rather than the temple.',
		takeaways: [
			'Leadership is framed as service first; authority is what follows, not what starts it.',
			'Starting late with nothing is treated as a fact of the case, not an excuse in it.',
			'A movement scales on the people it trains, so training is the leader’s main work.',
			'Joy is a management tool — the singing and dancing are the method, not a break from it.',
			'Discipline is set as a small daily routine and then never negotiated.',
			'Thousands of letters: the leader wrote back, and the writing back held the organisation together.',
			'Delegate early, and to people who are not yet ready, because that is how they become ready.',
			'Purpose fixed once lets every other decision be made quickly.',
			'Tolerance of criticism is the price of being visible, and it is paid without complaint.',
			'The modern management vocabulary is mapped onto the tradition, and the fit is closer than expected.',
		],
	},

	{
		slug: 'sri-namamrta',
		title: 'Śrī Nāmāmṛta: The Nectar of the Holy Name',
		author: 'A. C. Bhaktivedanta Swami Prabhupāda (compiled)',
		year: '1982',
		category: 'Life',
		cover: 'sri-namamrta.webp',
		note: 'Not a book he sat down to write: every passage Prabhupāda left on the holy name, gathered from the purports, the lectures and the letters and arranged by subject. A reference to open at a heading rather than read front to back, and the one on this shelf that answers the question the others keep raising — what, practically, is one meant to do.',
		takeaways: [
			'One practice is put at the centre, and everything else on the shelf is read as commentary on it.',
			'The arrangement is by topic, so a question finds its answer without a search through eighteen volumes.',
			'Chanting is treated as a method with stages, not a mood; the stages are named and the obstacles listed.',
			'Attention is the whole discipline — the count matters less than where the mind was during it.',
			'The offences are spelled out plainly, which makes the practice checkable rather than vague.',
			'Sound is argued to carry the thing it names, which is the claim the entire book rests on.',
			'The letters show the same instruction given to beginners and to the senior, unchanged.',
			'Community is presented as the practice’s natural form — sung together before it is done alone.',
			'Progress is described as taste arriving, not as effort increasing.',
			'A compilation, so the voice is consistent and the repetition is the point.',
		],
	},

	// ── Product ───────────────────────────────────────────────
	{
		slug: 'innovators-dilemma',
		title: 'The Innovator’s Dilemma',
		author: 'Clayton M. Christensen',
		year: '2000',
		category: 'Product',
		cover: 'innovators-dilemma.webp',
		note: 'Christensen explains why careful companies, doing everything right for their best customers, still get overtaken. I think about it whenever a roadmap starts to feel safe.',
		takeaways: [
			'Good management is what causes the failure, not bad management.',
			'Listening closely to your best customers is how you miss the next market.',
			'Disruptive technology arrives worse on the metrics that currently matter.',
			'Small emerging markets cannot solve a large company’s growth problem.',
			'Resource allocation follows margin, and margin follows the existing customer.',
			'Markets that do not exist yet cannot be analysed, only entered.',
			'Value networks decide what a company is able to see.',
			'A separate organisation is often the only way to pursue a low-margin bet.',
			'Technology usually overshoots what customers can absorb.',
			'When a roadmap starts to feel safe, that is the signal.',
		],
	},
	{
		slug: 'only-the-paranoid-survive',
		title: 'Only the Paranoid Survive',
		author: 'Andrew S. Grove',
		year: '1996',
		category: 'Product',
		cover: 'only-the-paranoid-survive.webp',
		coverIsCard: true,
		note: 'Grove named something I had already met: a strategic inflection point arrives quietly, and the 10X force behind it does not announce itself. A venture of mine that went nowhere taught me the rest.',
		takeaways: [
			'A strategic inflection point arrives quietly and is only obvious afterwards.',
			'A 10X change in any one force reshapes the whole business.',
			'Middle managers see the shift before executives do — listen downward.',
			'Debate the change loudly before committing, then commit completely.',
			'Data confirms an inflection point only after it is too late to act cheaply.',
			'The first version of the new strategy will be wrong; start anyway.',
			'Cassandras are useful precisely because they are uncomfortable.',
			'You cannot manage through a transition and reassure everyone at once.',
			'Clarity about what business you are now in is most of the work.',
			'Paranoia here means attention, not anxiety.',
		],
	},
	{
		slug: 'chip-war',
		title: 'Chip War',
		author: 'Chris Miller',
		category: 'Product',
		cover: 'chip-war.webp',
		note: 'A reminder that in deep tech the thing you are building is also the thing countries are counting. Read while working on wearable silicon, it changes what a supply chain feels like.',
		takeaways: [
			'Semiconductors are infrastructure, and infrastructure is geopolitics.',
			'The supply chain is a chokepoint map, not a logistics diagram.',
			'A handful of firms hold irreplaceable steps in the process.',
			'Manufacturing capability, once lost, takes decades to rebuild.',
			'Export controls are industrial policy conducted by other means.',
			'Moore’s law was as much an economic commitment as a technical one.',
			'Talent concentrates geographically and is slow to relocate.',
			'Fabs are capital bets placed years ahead of the demand they serve.',
			'What you build in deep tech is also what countries are counting.',
			'Technical decisions and national strategy are no longer separable.',
		],
	},
	{
		slug: 'apple-in-china',
		title: 'Apple in China',
		author: 'Patrick McGee',
		category: 'Product',
		cover: 'apple-in-china.webp',
		note: 'How one company’s manufacturing decisions built another country’s industrial capability. The counterpart to Chip War — the same story told from inside a product line rather than from inside a policy.',
		takeaways: [
			'Supplier development transfers capability, not just orders.',
			'Optimising a supply chain can build a competitor’s industrial base.',
			'Scale creates dependency in both directions at once.',
			'Manufacturing expertise migrates toward wherever the volume is.',
			'Concentration is efficient until the moment it is exposed.',
			'Corporate decisions accumulate into industrial policy nobody voted for.',
			'Diversifying a supply chain is a decade of work, not a quarter of it.',
			'The counterpart to Chip War, told from inside a product line.',
			'Leverage looks different depending on which end of the contract you hold.',
			'Cost, speed and resilience have never been simultaneously optimisable.',
		],
	},
	{
		slug: 'steve-jobs',
		title: 'Steve Jobs',
		author: 'Walter Isaacson',
		year: '2011',
		category: 'Product',
		cover: 'steve-jobs.webp',
		note: 'The life of the person whose instinct I recognised early: reading what people would want before they could say it. It is also a long argument for taste as a discipline rather than a gift.',
		takeaways: [
			'Taste is a discipline that can be practised, not a gift you are issued.',
			'Reading what people want before they can articulate it is a learnable habit.',
			'Integrating hardware and software buys coherence at the cost of flexibility.',
			'Saying no to good ideas is what protects the great ones.',
			'Simplicity is the last step of a long process, not the first.',
			'Small teams of excellent people outrun large teams of adequate ones.',
			'Craft in the parts nobody sees still shows up in the parts they do.',
			'Focus means a short product line, deliberately.',
			'The difficult behaviour is documented, not excused.',
			'Conviction and evidence are different things; the book shows both costs.',
		],
	},
	{
		slug: 'inspired',
		title: 'Inspired',
		author: 'Marty Cagan',
		category: 'Product',
		cover: 'inspired.webp',
		note: 'The clearest account of what a product manager is actually for — not writing specifications, but making sure the right thing gets built. The book to hand someone stepping into the role.',
		takeaways: [
			'A product manager is accountable for value and viability, not for specs.',
			'Discovery and delivery are separate activities with separate risks.',
			'Test the riskiest assumption first, not the easiest one.',
			'Empowered teams are given problems; feature teams are given solutions.',
			'A roadmap of dates is a list of outputs, not of outcomes.',
			'Engineers belong in discovery, not just at the end of it.',
			'Prototypes are for learning; the cheapest one that answers the question wins.',
			'Most ideas fail, so the loop matters more than any single bet.',
			'The strongest product decisions come from direct customer contact.',
			'Vision persuades; a backlog does not.',
		],
	},
	{
		slug: 'zero-to-one',
		title: 'Zero to One',
		author: 'Peter Thiel with Blake Masters',
		category: 'Product',
		cover: 'zero-to-one.webp',
		note: 'An argument for building something genuinely new rather than a better copy of something that exists. More useful as a test to run against your own idea than as a playbook to follow.',
		takeaways: [
			'Copying what works takes the world from one to n; new things go zero to one.',
			'Competition erodes margin — monopoly on something genuinely new preserves it.',
			'Start by dominating a small market you can actually own.',
			'Ask what important truth very few people agree with you on.',
			'Distribution is a product decision, not a marketing afterthought.',
			'Returns are power-law distributed, so concentration beats diversification.',
			'A definite view of the future beats an indefinite optimism about it.',
			'Technology compounds; globalisation only copies.',
			'The last mover in a category often takes the value.',
			'Use it as a test against your own idea, not as a playbook.',
		],
	},
	{
		slug: 'managers-handbook',
		title: 'HBR Manager’s Handbook',
		author: 'Harvard Business Review',
		category: 'Product',
		cover: 'managers-handbook.webp',
		note: 'A reference rather than a read: seventeen skills, each short enough to look up on the day it is needed. It stays within reach for exactly that reason.',
		takeaways: [
			'A reference to consult on the day, not a book to read through.',
			'Delegation is a design problem: decide the outcome, not the method.',
			'Feedback is most useful when it is specific, timely and quiet.',
			'Meetings need a decision owner or they become status theatre.',
			'Managing up is a skill, not a character flaw.',
			'Hiring slowly is cheaper than managing a mismatch.',
			'Difficult conversations get harder the longer they are deferred.',
			'Priorities that are not written down are not priorities.',
			'Development conversations are separate from performance reviews.',
			'Consistency of process is what makes fairness legible to a team.',
		],
	},

	{
		slug: 'the-lean-startup',
		title: 'The Lean Startup',
		author: 'Eric Ries',
		year: '2011',
		category: 'Product',
		cover: 'the-lean-startup.webp',
		note: 'The book that gave product work its vocabulary: the minimum viable product, the build–measure–learn loop, the pivot. Written for founders and adopted by everyone, sometimes as a licence to ship half-finished things. Read for the discipline underneath — every feature is a hypothesis, and a hypothesis needs a test you could fail.',
		takeaways: [
			'A startup is defined as an institution for learning under uncertainty, which reframes what progress means.',
			'Build–measure–learn is a loop, and the object is to get around it faster, not to build more per lap.',
			'The minimum viable product is the smallest thing that tests the riskiest assumption, not the smallest thing you can ship.',
			'Validated learning is the unit of progress; features shipped and revenue booked are lagging indicators of it.',
			'Vanity metrics are named as the enemy, and cohort and split tests as the antidote.',
			'A pivot is a structured change of strategy without a change of vision — the vision is what does not move.',
			'The five whys is borrowed from manufacturing to turn every failure into a process fix.',
			'Small batches make mistakes cheap and visible, which is the only way anyone learns from them.',
			'Innovation accounting asks the team to show that the numbers moved because of what it did.',
			'The method has been used to excuse sloppiness; the book itself asks for more rigour, not less.',
		],
	},

	{
		slug: 'high-output-management',
		title: 'High Output Management',
		author: 'Andrew S. Grove',
		year: '1983',
		category: 'Product',
		cover: 'high-output-management.webp',
		note: 'Grove’s other book, and the one managers actually use: a manager’s output is the output of the teams they lead, so the job is leverage — meetings, decisions, training, and knowing which indicator to read. Written by an engineer running a fab, which is why the metaphors are production lines and it never wastes a page.',
		takeaways: [
			'A manager’s output is measured by their organisation’s output, not their own activity.',
			'Leverage is the unit of managerial work: a one-to-one that saves ten wrong decisions is worth the hour.',
			'The breakfast factory teaches the whole book — find the limiting step and build everything around it.',
			'Indicators are paired so that improving one cannot quietly break another; the guardrail idea in one page.',
			'Meetings are a medium of work, not an interruption to it, and each kind has a purpose and a shape.',
			'Training is the highest-leverage activity a manager has, and the one most often delegated away.',
			'Task-relevant maturity decides how closely to manage someone, not seniority.',
			'Decisions are made at the lowest competent level, with the people who have the information in the room.',
			'Performance reviews exist to improve performance, so the hard sentence has to be in them.',
			'Forty years old and nothing in it has aged, which is rare for the genre.',
		],
	},
	{
		slug: 'design-of-everyday-things',
		title: 'The Design of Everyday Things',
		author: 'Don Norman',
		year: '1988',
		category: 'Product',
		cover: 'design-of-everyday-things.webp',
		note: 'Doors that need instructions, hobs whose knobs do not match the rings, the switch nobody can find. Norman argues that when a person fails to use a thing, the thing failed, and gives the vocabulary — affordances, signifiers, feedback, mappings — that every product review since has borrowed, usually without credit.',
		takeaways: [
			'When the user errs, blame the design; the user is the one thing you cannot ship a fix for.',
			'Affordances are what a thing allows; signifiers are how it tells you. Most bad design confuses the two.',
			'Feedback closes the loop — an action with no visible result will be repeated, then abandoned.',
			'Natural mapping: controls arranged like the things they control need no label.',
			'Constraints do more work than instructions; the well-designed thing cannot be used wrong.',
			'The gulf of execution and the gulf of evaluation name the two places a user gets lost.',
			'Knowledge in the world beats knowledge in the head — do not ask people to remember what the object could show.',
			'Slips and mistakes are different errors with different fixes, and most systems only guard against one.',
			'Human-centred design is iterative because the first model of the user is always wrong.',
			'Read it and you will never open a door the same way again.',
		],
	},
	{
		slug: 'crossing-the-chasm',
		title: 'Crossing the Chasm',
		author: 'Geoffrey A. Moore',
		year: '1991',
		category: 'Product',
		cover: 'crossing-the-chasm.webp',
		note: 'Why technology products that delight early adopters die before the mainstream buys them: the two groups want different things, and the gap between them is where most companies run out of money. The prescription — pick one niche, win it whole, then move — is the most useful piece of go-to-market thinking I know for hardware.',
		takeaways: [
			'Early adopters buy a change; the early majority buys a productivity improvement from a safe vendor. Same product, different sale.',
			'The chasm is the gap between those two, and reference customers do not carry across it.',
			'Cross by dominating one niche completely — a big fish in a small pond — before widening.',
			'The whole product is what the customer needs to get the job done; the core product is what you shipped.',
			'Choose the niche by pain and reachability, not by size.',
			'Positioning is a claim about the competition as much as about yourself; name the alternative.',
			'Pragmatists buy from the market leader, so in a small niche you must become one quickly.',
			'Pricing on the far side of the chasm follows value to the mainstream buyer, not cost to the innovator.',
			'Distribution is chosen for the target customer, and it is rarely the channel that reached the early adopters.',
			'For silicon, the chasm is where the dev kit goes out and the design-in does not come back; this book explains why.',
		],
	},
	{
		slug: 'the-mom-test',
		title: 'The Mom Test',
		author: 'Rob Fitzpatrick',
		year: '2013',
		category: 'Product',
		cover: 'the-mom-test.webp',
		note: 'How to ask customers about your idea without them lying to you — because they will, out of kindness. Short, blunt and practical: talk about their life, not your idea; ask about the past, not the future; and treat compliments as the sound of a conversation failing.',
		takeaways: [
			'Your mother will say your idea is great; so will everyone else. The fix is questions she could not lie to.',
			'Ask about specifics in the past — what they did last time — never about hypotheticals.',
			'Compliments are the failure signal, not the success signal.',
			'Talking about your idea ends the learning; delay the pitch as long as possible.',
			'A commitment — time, money, a reputation — is the only real evidence of interest.',
			'Zoom out before zooming in: understand the whole day before asking about your slice of it.',
			'Bad meetings are ones you leave feeling good and knowing nothing new.',
			'Write down what they said, not what you concluded — the note should survive your optimism.',
			'Segment until the customer is specific enough to find and talk to this week.',
			'The book is a hundred pages because the method is a hundred pages; there is nothing to skim.',
		],
	},
	{
		slug: 'hooked',
		title: 'Hooked',
		author: 'Nir Eyal',
		year: '2014',
		category: 'Product',
		cover: 'hooked.webp',
		note: 'The mechanics of habit-forming products laid out as a loop: trigger, action, variable reward, investment. Useful as a diagnostic — it explains exactly why some tools become daily and others are forgotten — and uncomfortable as a manual, which the author eventually admitted in a second book.',
		takeaways: [
			'A habit is a behaviour done with little or no conscious thought; products earn one by removing the thought.',
			'External triggers start the loop; the goal is an internal one — a feeling that reaches for the product.',
			'Action follows when motivation and ability meet a trigger; ability is usually the cheaper lever.',
			'Variable reward is what keeps attention — rewards of the tribe, the hunt and the self.',
			'Investment is the user putting something in — data, followers, effort — which loads the next trigger.',
			'Frequency matters more than perceived utility for habit formation, which explains a lot of what wins.',
			'The manipulation matrix asks whether you would use the product yourself and whether it improves lives.',
			'Internal tools rarely need hooks; they need the trigger to arrive where the work already is.',
			'The model explains adoption curves better than most adoption-metrics decks do.',
			'Read it with the author’s later Indistractable beside it; together they are honest.',
		],
	},
	{
		slug: 'build',
		title: 'Build',
		author: 'Tony Fadell',
		year: '2022',
		category: 'Product',
		cover: 'build.webp',
		note: 'From the iPod and iPhone teams to founding Nest: an unorthodox guide to making things worth making, told as stories with a lesson at the end of each. The rare product book by someone who shipped hardware at scale, and it reads that way — the chapters on the first version, the second version and when to stop are the ones I return to.',
		takeaways: [
			'Version one is for early adopters and should be; version two is where the product earns the mainstream.',
			'Hardware forces discipline because you cannot patch atoms; the schedule is real in a way software forgets.',
			'The story of the product is written before the product, and it should fit on one page.',
			'Data helps you decide; it does not decide for you, and opinion-led decisions are still allowed.',
			'The most dangerous phase is when the thing works and everyone relaxes.',
			'Managing is a different job from making, and most people should be told that before they take it.',
			'Assholes come in kinds, and only one kind is worth keeping.',
			'Perks are not culture; what the leaders tolerate is.',
			'When you are not learning any more, leave — the same rule for a job and for a product.',
			'Practical to a fault, which is exactly the fault the genre needed.',
		],
	},
	{
		slug: 'continuous-discovery-habits',
		title: 'Continuous Discovery Habits',
		author: 'Teresa Torres',
		year: '2021',
		category: 'Product',
		cover: 'continuous-discovery-habits.webp',
		note: 'Discovery as a weekly habit rather than a phase: talk to customers every week, map opportunities against a desired outcome, and test assumptions in small, cheap experiments before anything gets built. The opportunity solution tree is the one artefact I have kept from it.',
		takeaways: [
			'Discovery is a cadence — weekly customer conversations — not a project that ends.',
			'Start from an outcome, not a feature; the tree hangs opportunities and solutions under it.',
			'Opportunities are unmet needs, pains and desires in the customer’s words, never solutions in disguise.',
			'Compare several solutions per opportunity, so the first idea does not win by default.',
			'Test assumptions, not whole ideas — the smallest experiment that could kill the riskiest one.',
			'The product trio — product, design, engineering — does discovery together or it does not stick.',
			'Interview snapshots turn a conversation into something the team can reuse.',
			'Story-based interviewing asks about a specific past instance, which is the Mom Test with a template.',
			'Measuring impact closes the loop on whether the outcome moved at all.',
			'The book is a method; adopt the habit even if you drop the diagrams.',
		],
	},
	{
		slug: 'hard-thing-about-hard-things',
		title: 'The Hard Thing About Hard Things',
		author: 'Ben Horowitz',
		year: '2014',
		category: 'Product',
		cover: 'hard-thing-about-hard-things.webp',
		note: 'A founder’s account of running a company through the dot-com crash, and then the advice he wished he had: how to fire an executive, how to demote a friend, what to do when there is no good move. The chapter titled the struggle is the most honest description of the job I have read.',
		takeaways: [
			'There is no recipe for the hard things; the book’s honesty is admitting that before offering advice anyway.',
			'The struggle — when nothing works and you cannot say so — is the normal state, not the exception.',
			'Tell the truth inside the company; a culture that hears bad news early is the only one that can act on it.',
			'Hire for strength in the one thing you need, not for the absence of weakness.',
			'Peacetime and wartime CEOs run different playbooks, and knowing which time it is comes first.',
			'Training your people is your job; delegating it to HR is how companies stop being able to do anything.',
			'Titles are cheap to give and expensive to take back; decide the policy before the first request.',
			'One-to-ones belong to the employee, and the manager’s job in them is to listen.',
			'Lead by taking care of the people, the products and the profits, in that order.',
			'Read it before the crisis; during one there is no time.',
		],
	},
	{
		slug: 'working-backwards',
		title: 'Working Backwards',
		author: 'Colin Bryar and Bill Carr',
		year: '2021',
		category: 'Product',
		cover: 'working-backwards.webp',
		note: 'Two long-serving Amazon executives on the mechanisms behind the company — the six-page memo instead of the slide deck, the press release written before the product, single-threaded leaders, bar raisers, and metrics that measure inputs. The most concrete description of how a large company keeps deciding well, and most of it transfers.',
		takeaways: [
			'Write the press release and the FAQ first; if the announcement is not exciting, the product will not be.',
			'Narratives over slides — six pages, read in silence at the start of the meeting, so the thinking is complete before the discussion.',
			'A single-threaded leader owns one thing and nothing else, which is how anything ships in a big company.',
			'Bar raisers protect hiring from the pressure of the open role.',
			'Controllable input metrics — what the team can move — beat output metrics that only report the weather.',
			'Two-pizza teams and separable, single-threaded ownership are the organisational form of the API.',
			'Good intentions do not scale; mechanisms — a process, an owner, an audit — do.',
			'The weekly business review reads hundreds of metrics quickly because the format never changes.',
			'Customer obsession is operationalised as working backwards from the customer’s experience, in writing.',
			'Take the memo culture even if nothing else fits; a page that has to survive silent reading is a better decision than any deck.',
		],
	},

	// ── Physics ───────────────────────────────────────────────
	{
		slug: 'a-brief-history-of-time',
		title: 'A Brief History of Time',
		author: 'Stephen Hawking',
		category: 'Physics',
		cover: 'a-brief-history-of-time.webp',
		note: 'The book that made the very large feel discussable. It set a standard I still hold explanations to: if a thing cannot be said plainly, it is probably not yet understood.',
		takeaways: [
			'If it cannot be said plainly, it is probably not yet understood.',
			'Space and time are participants in physics, not the stage it happens on.',
			'The universe has a history, and that history has a beginning.',
			'A black hole is defined by a boundary, not by an object.',
			'Black holes radiate, which ties gravity to thermodynamics.',
			'The arrow of time is a statement about entropy, not about clocks.',
			'A good theory is one that could be shown to be wrong.',
			'Quantum mechanics and general relativity are not yet on speaking terms.',
			'Asking what came before may be the wrong shape of question.',
			'Analogy carries a lay reader further than mathematics does.',
		],
	},
	{
		slug: 'universe-in-a-nutshell',
		title: 'The Universe in a Nutshell',
		author: 'Stephen Hawking',
		year: '2001',
		category: 'Physics',
		cover: 'universe-in-a-nutshell.webp',
		note: 'The sequel, and the more visual of the two. Where the first book argues in sequence, this one shows — and is the better of them to return to rather than to start with.',
		takeaways: [
			'The sequel shows where the first book argued.',
			'Diagrams can carry an idea that a paragraph cannot.',
			'Branes and extra dimensions are presented as candidates, not conclusions.',
			'Different theories can describe the same reality equally well.',
			'The holographic idea says information may live on a boundary.',
			'Time behaves differently near mass, and that is measurable.',
			'Prediction has limits that are structural, not technical.',
			'The book is better to return to than to start with.',
			'Speculation is labelled as speculation throughout.',
			'Physics is shown as unfinished, which is the honest position.',
		],
	},
	{
		slug: 'the-grand-design',
		title: 'The Grand Design',
		author: 'Stephen Hawking and Leonard Mlodinow',
		category: 'Physics',
		cover: 'the-grand-design.webp',
		note: 'On whether the universe needs a designer, and on what a physical theory is entitled to claim about reality. The most philosophical of the Hawking shelf, and the most arguable.',
		takeaways: [
			'A theory is a model, and models are judged by usefulness.',
			'Model-dependent realism sidesteps asking which description is the real one.',
			'Laws of nature may not require a lawgiver.',
			'The fine-tuning argument has a multiverse answer, whether or not you like it.',
			'Quantum history is summed over, not traced.',
			'Philosophy is declared dead, which is itself a philosophical claim.',
			'The most arguable book on the shelf, and the most worth arguing with.',
			'M-theory is presented as a family of theories, not one.',
			'The universe can be described without invoking a beginning cause.',
			'Confidence in the conclusion outruns the evidence, and that is visible.',
		],
	},
	{
		slug: 'brief-answers-to-the-big-questions',
		title: 'Brief Answers to the Big Questions',
		author: 'Stephen Hawking',
		year: '2018',
		category: 'Physics',
		cover: 'brief-answers-to-the-big-questions.webp',
		note: 'The last one, assembled from his own notes: ten questions, answered directly and without hedging. It reads like someone deciding what was still worth saying while there was time to say it.',
		takeaways: [
			'Ten questions, answered directly and without hedging.',
			'The tone is of someone deciding what was still worth saying.',
			'Science is defended as a public good, not a specialist hobby.',
			'Artificial intelligence is treated as the largest near-term question.',
			'Space settlement is argued as insurance rather than adventure.',
			'Optimism and warning are held together rather than traded off.',
			'Complex ideas are compressed without being falsified.',
			'Curiosity is presented as the thing worth protecting in education.',
			'The personal passages give the physics its weight.',
			'A good last book: short, clear, and unafraid of the questions.',
		],
	},
	{
		slug: 'theory-of-everything',
		title: 'The Theory of Everything',
		author: 'Stephen Hawking',
		category: 'Physics',
		cover: 'theory-of-everything.webp',
		note: 'The lectures underneath the popular books — the origin and fate of the universe, taken in order. Closer to hearing him teach than to reading him write.',
		takeaways: [
			'The lectures underneath the popular books, taken in order.',
			'Cosmology is built up historically, which makes it easier to follow.',
			'The expanding universe implies a beginning, and that took time to accept.',
			'Black hole thermodynamics links information, entropy and gravity.',
			'A no-boundary universe removes the need for an initial edge.',
			'Unification is described as a programme, not an achievement.',
			'Hearing him teach is different from reading him write.',
			'Repetition across lectures is a feature for a lay reader.',
			'The limits of the theories are stated as plainly as the theories.',
			'Short enough to read in a sitting, dense enough to reread.',
		],
	},
	{
		slug: 'parallel-worlds',
		title: 'Parallel Worlds',
		author: 'Michio Kaku',
		category: 'Physics',
		cover: 'parallel-worlds.webp',
		note: 'Kaku takes the same territory and pushes further out, into higher dimensions and the multiverse. Speculative where Hawking stays careful, which is its own kind of useful.',
		takeaways: [
			'The same territory as Hawking, pushed considerably further out.',
			'Higher dimensions are introduced as mathematics before as spectacle.',
			'Multiverse models are catalogued rather than endorsed.',
			'String theory is presented as promise, not as settled result.',
			'Cosmology and particle physics meet at the very early universe.',
			'The far future of the universe is a physics question, not a poetic one.',
			'Speculation is enjoyable and should still be labelled.',
			'Popular science can be generous with ideas and thin on caveats.',
			'Read after Hawking, as the counterweight rather than the introduction.',
			'Ambition in a science book is worth something on its own.',
		],
	},
	{
		slug: 'relativity',
		title: 'Relativity',
		author: 'Albert Einstein',
		year: '1916',
		category: 'Physics',
		cover: 'relativity.webp',
		coverIsCard: true,
		note: 'Einstein explaining relativity himself, for readers without the mathematics. Worth it for the tone as much as the physics — the person who found it, explaining it without hurry.',
		takeaways: [
			'The person who found it, explaining it without hurry.',
			'Simultaneity depends on the observer, and that is the hinge.',
			'The speed of light being constant forces everything else to give.',
			'Special relativity comes from two postulates and careful bookkeeping.',
			'Thought experiments do real work, not just illustrative work.',
			'Gravity and acceleration are locally indistinguishable.',
			'Mass tells space how to curve; curvature tells mass how to move.',
			'The theory was written down with testable predictions attached.',
			'Written for readers without the mathematics, and it holds.',
			'Worth it for the tone as much as for the physics.',
		],
	},

	// ── Self help ─────────────────────────────────────────────
	{
		slug: 'subtle-art',
		title: 'The Subtle Art of Not Giving a F*ck',
		author: 'Mark Manson',
		category: 'Self help',
		cover: 'subtle-art.webp',
		note: 'The argument is that attention is the scarce resource, not positivity: you are going to care about something, so choose it on purpose. Blunter than it needs to be, and right about the central point.',
		takeaways: [
			'Attention is the scarce resource; positivity is not.',
			'You will care about something, so choose it deliberately.',
			'Problems do not end — you trade them for better ones.',
			'Choosing what to struggle for matters more than choosing what to want.',
			'Taking responsibility is separable from being at fault.',
			'Certainty is comfortable and usually a sign you have stopped looking.',
			'Values chosen badly produce misery no amount of effort fixes.',
			'Rejection of some things is what makes commitment to others mean anything.',
			'Entitlement and self-loathing are the same error in different directions.',
			'Blunter than it needs to be, and right about the central point.',
		],
	},
	{
		slug: 'atomic-habits',
		title: 'Atomic Habits',
		author: 'James Clear',
		year: '2018',
		category: 'Self help',
		cover: 'atomic-habits.webp',
		note: 'The mechanics of habit, taken apart into cue, craving, response and reward, and then put back together as something you can design. The most practical book on this shelf, and the least interested in motivation.',
		takeaways: [
			'You do not rise to your goals; you fall to your systems.',
			'Habits are the compound interest of self-improvement.',
			'Make it obvious, attractive, easy and satisfying — and invert all four to break one.',
			'Change the identity first: decide who you are, and the behaviour follows.',
			'Environment beats willpower, so design the room rather than the resolve.',
			'Reduce the friction on what you want and add friction to what you do not.',
			'Two minutes is enough to start; the point is showing up, not the volume.',
			'Never miss twice — one lapse is an accident, two is the new pattern.',
			'Measure what you want to move, but do not mistake the measure for the goal.',
			'Progress is invisible until it is obvious, which is why most people stop early.',
		],
	},
	{
		slug: 'power-of-your-subconscious-mind',
		title: 'The Power of Your Subconscious Mind',
		author: 'Joseph Murphy',
		year: '1963',
		category: 'Self help',
		cover: 'power-of-your-subconscious-mind.webp',
		note: 'An argument that what you repeat to yourself gets treated as an instruction. Dated in its examples and overreaching in its claims, but the core point about attention and repetition has aged better than the packaging.',
		takeaways: [
			'What you repeat to yourself is eventually treated as an instruction.',
			'The subconscious does not argue with a premise, it acts on it.',
			'Anxiety rehearses an outcome as thoroughly as preparation does.',
			'Belief and expectation shape what you notice and therefore what you find.',
			'Repetition is the mechanism; sincerity is what makes repetition stick.',
			'The state you fall asleep in is the one that gets the most rehearsal.',
			'Imagination directed deliberately is more useful than imagination left running.',
			'Resentment is a loop you maintain at your own cost.',
			'Read the claims as psychology rather than as physics.',
			'The practical residue is simple: mind what you keep telling yourself.',
		],
	},
	{
		slug: '48-laws-of-power',
		title: 'The 48 Laws of Power',
		author: 'Robert Greene',
		year: '1998',
		category: 'Self help',
		cover: '48-laws-of-power.webp',
		note: 'A catalogue of how power has actually been taken and held, illustrated from history and stated without apology. Best read as a description of behaviour you will meet rather than a set of instructions to follow.',
		takeaways: [
			'A description of how power operates, not a recommendation for how to live.',
			'Never outshine the person you depend on.',
			'Reputation is built slowly and spent instantly; guard it accordingly.',
			'Say less than necessary — ambiguity leaves room you can use.',
			'Actions persuade; arguments create opponents.',
			'Court attention, but never let anyone see the effort behind it.',
			'Make people come to you by controlling the terms of the meeting.',
			'Plan to the end, because most failures are failures of the last mile.',
			'Recognising these moves in others is the defensive half of the book.',
			'The amorality is deliberate and is the main thing to read critically.',
		],
	},
	{
		slug: 'how-to-win-friends',
		title: 'How to Win Friends and Influence People',
		author: 'Dale Carnegie',
		year: '1936',
		category: 'Self help',
		cover: 'how-to-win-friends.webp',
		note: 'Nearly a century old and still the clearest short book on paying attention to other people. Almost all of it reduces to taking a genuine interest and saying so, which is easier to agree with than to practise.',
		takeaways: [
			'Criticism puts people on the defensive and rarely changes the behaviour.',
			'Become genuinely interested in other people and most of the rest follows.',
			'A person’s name is the word they most want to hear said correctly.',
			'Listen more than you talk, and ask about what they care about.',
			'Let the other person do most of the talking about their own idea.',
			'Admit your mistakes quickly and completely, before they are pointed out.',
			'Begin with what you agree on rather than what you dispute.',
			'Give the other person credit and let the idea be theirs.',
			'Appreciation is specific; flattery is generic — the difference is audible.',
			'The techniques only work when the interest behind them is real.',
		],
	},
	{
		slug: 'stop-worrying-start-living',
		title: 'How to Stop Worrying and Start Living',
		author: 'Dale Carnegie',
		year: '1948',
		category: 'Self help',
		cover: 'stop-worrying-start-living.webp',
		note: 'The companion volume, and the more useful of the two. Its method is unglamorous: define the worry precisely, decide what you would actually do, then get on with the doing.',
		takeaways: [
			'Live in day-tight compartments — today is the only unit you can act in.',
			'Ask what the worst outcome actually is, accept it, then work to improve on it.',
			'Worry is a decision deferred; making the decision usually ends it.',
			'Get the facts before you get an opinion about your own situation.',
			'Keep busy — an occupied mind has less room for rehearsal.',
			'Do not agitate over things too small to be worth the cost.',
			'Play the odds: most feared outcomes are statistically rare.',
			'Accept the inevitable rather than spending on it repeatedly.',
			'Put a stop-loss order on a worry, the way you would on a trade.',
			'Act your way into a feeling rather than waiting to feel your way into action.',
		],
	},
	{
		slug: 'ikigai',
		title: 'Ikigai',
		author: 'Héctor García and Francesc Miralles',
		year: '2016',
		category: 'Self help',
		cover: 'ikigai.webp',
		note: 'A short book on why people in Okinawa live long and stay engaged. Lighter than its reputation, and most useful for one idea: purpose is a daily practice, not a destination you arrive at.',
		takeaways: [
			'Purpose is something practised daily, not discovered once.',
			'A reason to get up in the morning is the whole definition.',
			'Retirement from work is not retirement from usefulness.',
			'Community and routine do more for longevity than intensity does.',
			'Eat until roughly eighty per cent full, and stop there.',
			'Constant gentle movement beats occasional hard exercise.',
			'Flow — absorption in a task — is where the satisfaction actually sits.',
			'Small rituals hold a day together better than large plans.',
			'Slowness is treated as a method rather than a lack of ambition.',
			'The evidence is thin in places; the practices are still worth trying.',
		],
	},
	{
		slug: 'wings-of-fire',
		title: 'Wings of Fire',
		author: 'A. P. J. Abdul Kalam with Arun Tiwari',
		year: '1999',
		category: 'Self help',
		cover: 'wings-of-fire.webp',
		note: 'Kalam’s account of getting from Rameswaram to India’s missile programme, written without self-congratulation. The engineering chapters are the good ones: what it takes to build hard things inside a system that is learning as it goes.',
		takeaways: [
			'Where you start does not determine what you can build.',
			'Failure is reported honestly here, including the launches that did not work.',
			'A leader’s job is to absorb blame and distribute credit.',
			'Large engineering programmes are held together by people, not by plans.',
			'Teachers change trajectories, and he names every one of his.',
			'Self-reliance was a national argument before it was a technical one.',
			'Dreams that keep you awake are the ones worth working on.',
			'Discipline and simplicity are treated as the same habit.',
			'Science and faith are held together without apology or conflict.',
			'The tone is the lesson: ambition without self-importance.',
		],
	},
	{
		slug: 'dont-believe-everything-you-think',
		title: 'Don’t Believe Everything You Think',
		author: 'Joseph Nguyen',
		year: '2022',
		category: 'Self help',
		cover: 'dont-believe-everything-you-think.webp',
		note: 'A very short book with one argument: thinking about a feeling is what sustains it. Repetitive by design, and the repetition is the method rather than a flaw.',
		takeaways: [
			'Thoughts arrive on their own; thinking about them is the part you add.',
			'Suffering is generated by the commentary, not by the event.',
			'You are not obliged to believe a thought just because you had it.',
			'Feelings pass quickly unless thinking keeps them running.',
			'Peace is the default state, not an achievement to be earned.',
			'Trying to control thought is itself more thought.',
			'Clarity tends to arrive in the gaps, not during the effort.',
			'Awareness of a pattern is most of what breaks it.',
			'The book is repetitive on purpose — it is a practice, not an argument.',
			'Short enough to reread whenever the loop starts again.',
		],
	},
	{
		slug: 'mindset',
		title: 'Mindset',
		author: 'Carol S. Dweck',
		year: '2006',
		category: 'Self help',
		cover: 'mindset.webp',
		note: 'The research behind a distinction that has been flattened by repetition: whether you treat ability as fixed or as developable changes what you attempt. Better than its slogan, and more careful about the limits.',
		takeaways: [
			'Treating ability as fixed or as developable changes what you attempt.',
			'A fixed mindset makes effort feel like evidence of inadequacy.',
			'Praise the process, not the person — praising talent makes it fragile.',
			'Failure becomes information rather than identity in a growth mindset.',
			'Nobody holds one mindset everywhere; it varies by domain and by day.',
			'Challenge is sought when improvement seems possible and avoided when it does not.',
			'Organisations have mindsets too, and they show up in how they hire.',
			'“Not yet” is a more useful verdict than “failed”.',
			'The idea is often cited more loosely than the research supports.',
			'The distinction is most useful applied to yourself, not to other people.',
		],
	},
	{
		slug: 'think-and-grow-rich',
		title: 'Think and Grow Rich',
		author: 'Napoleon Hill',
		year: '1937',
		category: 'Self help',
		cover: 'think-and-grow-rich.webp',
		note: 'The ancestor of most of this shelf. The evidence is anecdotal and some of it is invented, but its emphasis on definiteness of purpose and persistence explains why it has outlasted almost everything written since.',
		takeaways: [
			'A vague aim produces vague effort; definiteness of purpose comes first.',
			'Desire has to be specific enough to be measured against.',
			'Persistence is described as a habit that can be built deliberately.',
			'A mastermind group — deliberate peers — outperforms working alone.',
			'Decisions made slowly and changed quickly are the pattern to avoid.',
			'Plan, fail, replace the plan; do not replace the objective.',
			'Fear is catalogued specifically so it can be addressed specifically.',
			'Specialised knowledge beats general knowledge for a defined aim.',
			'Much of the evidence is anecdotal and some of it is fabricated.',
			'Read it as the origin of a genre, and discount accordingly.',
		],
	},
	{
		slug: 'the-alchemist',
		title: 'The Alchemist',
		author: 'Paulo Coelho',
		year: '1988',
		category: 'Self help',
		cover: 'the-alchemist.webp',
		note: 'A fable about leaving to find something and learning where it was. Simple enough to be dismissed and durable enough to keep being read; it works better as a mood than as a philosophy.',
		takeaways: [
			'The journey teaches what the destination cannot.',
			'Fear of loss is a heavier tax than loss itself.',
			'Omens are a way of describing attention, not prophecy.',
			'What you are looking for is often near where you started.',
			'Beginner’s luck gets you moving; persistence gets you there.',
			'Every setback is presented as tuition rather than as a verdict.',
			'Listening to your own restlessness is treated as data.',
			'The simplicity is the form, and it is easy to mistake for shallowness.',
			'Comfort is the most common reason a personal legend is abandoned.',
			'A fable, so read it for the mood rather than the argument.',
		],
	},
	{
		slug: 'the-secret',
		title: 'The Secret',
		author: 'Rhonda Byrne',
		year: '2006',
		category: 'Self help',
		cover: 'the-secret.webp',
		note: 'The law of attraction as a self-help bestseller: ask, believe, receive. The mechanism it proposes does not survive a moment’s scrutiny, and the habit it teaches — deciding what you want and holding it in mind — does. Read for the second and discount the first.',
		takeaways: [
			'Naming what you want, specifically, is worth doing whatever you believe about the universe.',
			'Attention goes where it is pointed; the book dresses that up as physics.',
			'Gratitude is prescribed as a daily practice, and that part holds up on its own.',
			'Visualisation is rehearsal — useful for the doing, not a substitute for it.',
			'The mechanism claimed is causation; the effect observed is mostly selection and effort.',
			'A wish with a deadline behaves like a plan; a wish without one behaves like a wish.',
			'Complaint is treated as a rehearsal of what you do not want, which is at least a useful habit to notice.',
			'The book confuses confidence with certainty, and the two cost different things when wrong.',
			'Its worst failure is blaming misfortune on the thoughts of the person it happened to.',
			'Take the optimism and the ritual; leave the cosmology.',
		],
	},
	{
		slug: 'do-epic-shit',
		title: 'Do Epic Shit',
		author: 'Ankur Warikoo',
		year: '2021',
		category: 'Self help',
		cover: 'do-epic-shit.webp',
		note: 'Short entries — a page, a paragraph, sometimes a line — on money, work, relationships and the self, from someone who built and lost a company in public. It reads like a feed because it came from one, and it is more honest than the format suggests: the failures are in it.',
		takeaways: [
			'Small decisions repeated are the whole of a life; the book keeps returning to compounding.',
			'Being wrong in public and saying so is treated as a skill, and practised on the page.',
			'Money is framed as time bought back rather than things bought.',
			'Saying no early is cheaper than saying yes and leaving late.',
			'Doing the thing badly first is the only way the thing gets done well later.',
			'Regret is priced higher than failure, deliberately.',
			'Relationships are described as the compounding asset most people never invest in on purpose.',
			'The format — one idea per page — is the argument: attention is short, so make the thought land whole.',
			'Discipline is described as what shows up on the days motivation does not.',
			'Aphorisms, so keep the ones that name something you already knew and were avoiding.',
		],
	},
	{
		slug: 'get-epic-shit-done',
		title: 'Get Epic Shit Done',
		author: 'Ankur Warikoo',
		year: '2022',
		category: 'Self help',
		cover: 'get-epic-shit-done.webp',
		note: 'The sequel narrows from how to think to how to work: a mentor and a student, in dialogue, on habits, time, focus and the fear of starting. Less quotable than the first and more useful, because the advice comes with the situation it was for.',
		takeaways: [
			'Start before you are ready, because readiness is a feeling that arrives after starting.',
			'Time is budgeted like money — written down, allocated, reconciled at the end of the week.',
			'A habit is designed around the trigger, not around the willpower.',
			'The dialogue form lets the objections be voiced, which is where most self-help books go quiet.',
			'Consistency is defined as a minimum you never miss, not a maximum you sometimes hit.',
			'Learning in public is the fastest feedback loop available to someone with no network.',
			'Distraction is treated as a design problem of the environment, not a character flaw.',
			'Career advice: choose the room you are learning most in, and stay until you are not.',
			'Fear is not removed; it is made smaller than the cost of not acting.',
			'A workbook more than a book — the value is in what you write in the margins.',
		],
	},
	{
		slug: 'everything-is-fucked',
		title: 'Everything Is F*cked',
		author: 'Mark Manson',
		year: '2019',
		category: 'Self help',
		cover: 'everything-is-fucked.webp',
		note: 'Subtitled “a book about hope”. Manson argues that a comfortable, safe generation has never been more anxious, because hope needs something to be for — and that the modern replacements for religion mostly fail at the job. Broader and less tidy than the first book, and the better argument.',
		takeaways: [
			'Hope is framed as a requirement, not a comfort: without a thing worth working for, comfort turns to dread.',
			'The two brains — the feeling one that decides and the thinking one that justifies — is the working model of the whole book.',
			'Values are what you are willing to suffer for; anything you are not is a preference.',
			'Every belief system that promises the end of struggle is read as a religion, whatever it calls itself.',
			'Pain is treated as the constant, and the question shifts to which pain is worth choosing.',
			'Comfort is described as a slow anaesthetic — it removes the small pains and leaves the large ones unaddressed.',
			'Kant is borrowed for one idea: treat people, including yourself, as ends and not means.',
			'Outrage is diagnosed as a substitute for meaning, and a poor one.',
			'The book distrusts its own genre and says so, which is why it is more trustworthy than most of it.',
			'A wide-ranging essay rather than a method; take the frame, not the footnotes.',
		],
	},
	{
		slug: 'the-5-am-club',
		title: 'The 5 AM Club',
		author: 'Robin Sharma',
		year: '2018',
		category: 'Self help',
		cover: 'the-5-am-club.webp',
		note: 'A parable wrapped around one routine: up at five, then twenty minutes each of movement, reflection and learning before the day gets a vote. The story is padded and the routine is sound; it is on this shelf because the hour before anyone needs you is the only one you fully own.',
		takeaways: [
			'The first hour is the one nobody else has a claim on, which is the whole case for taking it.',
			'Twenty minutes each — move, reflect, learn — is small enough to keep and large enough to matter.',
			'The morning is spent on the self so the day can be spent on the work, in that order.',
			'Willpower is treated as strongest early and rationed accordingly.',
			'Sleep is the other half of the routine; five o’clock without ten o’clock is just tiredness.',
			'Mastery is framed as consistency over years, not intensity over weeks.',
			'A distraction-free first hour is worth more than a productive tenth one.',
			'Rituals are the mechanism; motivation is what the rituals eventually produce.',
			'The parable is the weakest part — read past it to the schedule.',
			'Sixty-six days is the number the book gives for a habit to stop needing effort; treat it as a horizon, not a promise.',
		],
	},
];

export const bookBySlug = new Map(books.map((b) => [b.slug, b]));

export const booksIn = (category: BookCategory): Book[] =>
	books.filter((b) => b.category === category);
